In [ ]:
import json, re
from pathlib import Path
from tqdm import tqdm
import fitz  # PyMuPDF
import pandas as pd
from openai import OpenAI

In [ ]:
#! pip install tools fitz openai
#!pip install --upgrade --force-reinstall pymupdf

In [ ]:
PDF_PATH = "/content/chung2020chamorro.pdf"
MODEL = "gpt-5.2"
MAX_CHARS = 36000
OVERLAP_PAGES = 1

In [ ]:
OUT_JSONL = "/content/chung2020_parallel_extracted.jsonl"
OUT_CSV   = "/content/chung2020_parallel_extracted.csv"

OPENAI_API_KEY=YOUR_API_HERE

In [ ]:
client = OpenAI(api_key=OPENAI_API_KEY)
from tqdm.auto import tqdm

In [ ]:

SYSTEM_PROMPT = r"""
You are extracting parallel data from Sandra Chung (2020) "Chamorro Grammar".
Your job is to identify and reconstruct three kinds of parallel examples:

(1) IGT BLOCKS (glossed examples):
Usually formatted as:
(14) a. <Chamorro line(s)>
     <gloss line(s) with Leipzig tags like AGR, PROG, COMP, UNM, etc.>
     ‘<English free translation>’
     (<source like Alamagan 16>)
Subexamples a/b/c are common. The Chamorro line may wrap across lines.
Gloss may wrap across multiple lines.
The translation may be on a separate line and may be followed by a source line in parentheses.

(2) INLINE EXAMPLES:
Object-language phrase/sentence embedded in running prose, with an English translation nearby
(often in quotes). Extract only when there is an unambiguous Chamorro ↔ English pairing.

(3) TRANSLATED TEXTS:
Running Chamorro text with an English translation section. Align sentence-by-sentence if possible,
else align paragraph-by-paragraph.

OUTPUT
Return STRICT JSON ONLY (no markdown), as a list of objects.
Each object must contain:
- "type": "igt" | "inline" | "text"
- "example_id": string like "14a", "14b", "14c" if available; else null
- "object_language": Chamorro text ONLY (no gloss tags, no English, no Leipzig abbreviations)
- "gloss": gloss line(s) ONLY if type="igt", else null
- "translation": English free translation ONLY
- "source_ref": source/citation in parentheses like "(Alamagan 16)" if present, else null
- "page_hint": page label if present in the excerpt (e.g., "=== PAGE 39 ==="), else null
- "context_before": up to 1 sentence of surrounding explanatory prose immediately before the example (exclude other examples)
- "context_after": up to 1 sentence of surrounding explanatory prose immediately after the example (exclude other examples)

CRITICAL RULES (NO EXCEPTIONS)
- Do not include gloss leakage in "object_language". Remove tokens such as AGR, PROG, COMP, UNM, 1/2/3, SG/PL, etc.
- Do not include example labels "(14)", "a.", etc. inside object_language/gloss/translation. Put them in example_id only.
- If the Chamorro line is split across multiple lines, join them into one clean sentence.
- For IGT, ensure gloss is captured (non-empty). If gloss is missing, do NOT output as type="igt".
- Ensure every object has non-empty object_language and translation.
- Deduplicate: do not output two objects with identical (object_language, translation).

Now extract examples from the excerpt below.
""".strip()

def chunk_pages(doc, max_chars=MAX_CHARS, overlap_pages=OVERLAP_PAGES):
    pages_text = [doc.load_page(i).get_text("text") or "" for i in range(doc.page_count)]
    i = 0
    while i < doc.page_count:
        start = i
        end = i
        buff = ""
        while end < doc.page_count and len(buff) + len(pages_text[end]) < max_chars:
            buff += f"\n\n=== PAGE {end+1} ===\n" + pages_text[end]
            end += 1

        ov_start = max(0, start - overlap_pages)
        ov_buff = ""
        for p in range(ov_start, start):
            ov_buff += f"\n\n=== PAGE {p+1} ===\n" + pages_text[p]

        yield (ov_start + 1, end, ov_buff + buff)  # 1-indexed
        i = end

def parse_json_list(text: str):
    text = text.strip()
    if text.startswith("["):
        return json.loads(text)
    a = text.find("[")
    b = text.rfind("]")
    if a != -1 and b != -1 and b > a:
        return json.loads(text[a:b+1])
    raise ValueError("Model did not return a JSON list.")

# minimal “leakage guard” (NOT a parser): just rejects obvious bad outputs
LEAK = re.compile(r"\b(AGR|PROG|COMP|UNM|SG|PL|PST|PRF|ERG|ABS|DAT|GEN|LOC|INSTR|NMLZ)\b")

In [ ]:

doc = fitz.open(PDF_PATH)

rows = []
seen = set()

chunks = list(chunk_pages(doc))

for page_start, page_end, chunk_text in tqdm(
        chunks,
        desc="Extracting Chung2020 examples",
        unit="chunk"
    ):


    resp = client.responses.create(
        model=MODEL,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": chunk_text},
        ],
        # temperature=0,
    )
    items = parse_json_list(resp.output_text)

    for it in items:
        if not isinstance(it, dict):
            continue
        obj = (it.get("object_language") or "").strip()
        trn = (it.get("translation") or "").strip()

        if not obj or not trn:
            continue
        if LEAK.search(obj):
            continue  # reject leaked-gloss object-language

        key = (it.get("type"), obj, trn)
        if key in seen:
            continue
        seen.add(key)

        if not it.get("page_hint"):
            it["page_hint"] = f"{page_start}-{page_end}"

        rows.append(it)

# Save
with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print("Extracted:", len(df))
display(df.head(30))
print("Saved:", OUT_JSONL)
print("Saved:", OUT_CSV)

Extracting Chung2020 examples:   0%|          | 0/44 [00:00<?, ?chunk/s]

Extracted: 2414

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,igt,1a,Kumåkati.,AGR.cry.PROG,S/he is crying.,None,=== PAGE 34 ===,The predicate can be from any of the major par...,None
1,igt,1b,Hu po’lu.,AGR put,I put it (there).,None,=== PAGE 34 ===,The predicate can be from any of the major par...,None
2,igt,2a,Manlokka’.,AGR.tall,They are tall.,None,=== PAGE 34 ===,The predicate can be from any of the major par...,None
3,igt,2b,Agaga’.,AGR.red,It is red.,None,=== PAGE 34 ===,The predicate can be from any of the major par...,None
4,igt,3a,Ma’estru.,teacher,He is a teacher.,None,=== PAGE 34 ===,The predicate can be from any of the major par...,None
5,igt,3b,Ga’lågu.,dog,It’s a dog.,None,=== PAGE 34 ===,The predicate can be from any of the major par...,The predicate can also be a preposition (but s...
6,igt,4,Para månu?,to where?,Where are they heading?,None,=== PAGE 35 ===,The predicate can also be a preposition (but s...,Predicates that are verbs or adjectives agree ...
7,igt,5a,Kumåkati i neni.,AGR.cry.PROG the baby,The baby is crying.,None,=== PAGE 35 ===,Chamorro is a predicate-first language.,None
8,igt,5b,Hu po’lu i nengkanu’ gi hilu’ lamasa.,AGR put the food LCL top.L table,I put the food on top of the table.,None,=== PAGE 35 ===,Chamorro is a predicate-first language.,None
9,igt,5c,Manlokka’ siha.,AGR.tall they,They are tall.,None,=== PAGE 35 ===,Chamorro is a predicate-first language.,None
10,igt,5d,Ma’estra atyu na palåo’an.,teacher that L woman,That woman is a teacher.,None,=== PAGE 35 ===,Chamorro is a predicate-first language.,None
11,igt,5e,Para i tenda i famagu’un.,to the store the PL.child,The children are heading to the store.,None,=== PAGE 35 ===,Chamorro is a predicate-first language.,The word order of clauses is described in grea...
12,igt,10a,Manmalak månu?,AGR.go.to where?,Where did they go?,None,=== PAGE 37 ===,To illustrate: Even though the orthography rep...,None
13,igt,10b,Para i tenda.,to the store,He headed to the store.,None,=== PAGE 37 ===,To illustrate: Even though the orthography rep...,None
14,igt,11a,Manmalak måmanu?,AGR.go.to where.PROG,Where are they going?,None,=== PAGE 38 ===,"When these predicates are in the progressive, ...",None
15,igt,11b,Para i tetenda.,to the store.PROG,He is heading to the store.,None,=== PAGE 38 ===,"When these predicates are in the progressive, ...",Another illustration: Every possessed noun tha...
16,igt,12,Ma’estrun Juan.,teacher.L Juan,He is Juan’s teacher.,None,=== PAGE 38 ===,"In (12), this phonological word is enclosed in...",None
17,igt,13,Ma’estrun Juajuan ha’.,teacher.L Juan.PROG EMP,He is still Juan’s teacher.,None,=== PAGE 38 ===,When a possessed noun of this sort is in the p...,None
18,igt,14a,"Si Paul Santos, guiya esti hu penta anai ha fa...",UNM Paul Santos he this AGR draw when AGR wash...,Paul Santos is the one I drew while he was was...,(Alamagan 16),=== PAGE 39 ===,The progressive is used for events that are on...,None
19,igt,14b,Ha li’i’ na ginin i Gima’ Yuyu’us si nanå-ña.,AGR see COMP from the church.PROG UNM mother-AGR,She saw that her mother was heading from the c...,(Dibota 7-8),=== PAGE 39 ===,The progressive is used for events that are on...,None
20,igt,14c,U’uchan.,AGR.rain.PROG,It’s raining.,None,=== PAGE 39 ===,The progressive is used for events that are on...,The neutral aspect is used for events that are...
21,igt,15a,"Anai ma baba, humuyung påtgun.",when AGR open AGR.go.out child,"When they opened it, a child came out.",(Cooreman 1983: 107),=== PAGE 39 ===,"In (15), none of the events is viewed as ongoi...",None
22,igt,15b,Ha nå’i guatu ni na’-ña ya sinangåni na para u...,AGR give to.there OBL food-AGR and.then AGR.PA...,She gave him his food and told him that he sho...,(Cooreman 1983: 79-80),=== PAGE 39 ===,"In (15), none of the events is viewed as ongoi...",None
23,igt,15c,Pues duru uchan.,so hard AGR.rain,Then it rained hard.,None,=== PAGE 39 ===,"In (15), none of the events is viewed as ongoi...","In (16), the event lasts for a specific time p..."
24,igt,16,Todu diha nai umåssun gi tatalo’-ña.,all day COMP AGR.lie LCL back-AGR,All day [the turtle] lay on its back.,(Igu 4),=== PAGE 40 ===,"In (16), the event lasts for a specific time p...",Either the progressive or the neutral aspect c...
25,igt,17,"Mana’kabålis i kareta, mana’kabåbalis i kareta...",AGR.PASS.make.complete the car AGR.PASS.make.c...,"[a factory where] the car is assembled, the ca...",(from a tape-recorded narrative),=== PAGE 40 ===,Either the progressive or the neutral aspect c...,The use of the progressive for repeated events...
26,igt,18a,Manhåhatsa guma’.,AGR.ANTIP.build.PROG house,He builds houses (e.g. as his profession).,None,=== PAGE 40 ===,"In (18), the progressive provides the only lin...",None
27,igt,18b,Maila’ ya ta aplika giya hita håfa ta sangånga...,come and.then AGR apply LCL us.INCL what? AGR ...,Come and let us (incl.) apply to ourselves (in...,"(Ginen I Obispo August 9, 2009)",=== PAGE 40 ===,"In (18), the progressive provides the only lin...",None
28,igt,19a,Sessu yu’ di mapångun as nanå-hu yan tatå-hu.,often I PRT AGR.PASS.wake OBL mother-AGR and f...,Often I was awakened by my mother and father.,(Familia 4),=== PAGE 41 ===,"But in (19), the repetition of the event is ma...",None
29,igt,19b,"Kada ma kumprendi una kosa, umannuk ottra kosa...",whenever AGR understand one thing AGR.appear o...,"Every time they understand one thing, another ...","(Ginen I Obispo August 9, 2009)",=== PAGE 41 ===,"But in (19), the repetition of the event is ma...",None

Saved: /content/chung2020_parallel_extracted.jsonl
Saved: /content/chung2020_parallel_extracted.csv

In [ ]:
df_small = df[["type","example_id","object_language","translation","source_ref","page_hint"]]
display(df_small.head(50))

,type,example_id,object_language,translation,source_ref,page_hint
0,igt,1a,Kumåkati.,S/he is crying.,None,=== PAGE 34 ===
1,igt,1b,Hu po’lu.,I put it (there).,None,=== PAGE 34 ===
2,igt,2a,Manlokka’.,They are tall.,None,=== PAGE 34 ===
3,igt,2b,Agaga’.,It is red.,None,=== PAGE 34 ===
4,igt,3a,Ma’estru.,He is a teacher.,None,=== PAGE 34 ===
5,igt,3b,Ga’lågu.,It’s a dog.,None,=== PAGE 34 ===
6,igt,4,Para månu?,Where are they heading?,None,=== PAGE 35 ===
7,igt,5a,Kumåkati i neni.,The baby is crying.,None,=== PAGE 35 ===
8,igt,5b,Hu po’lu i nengkanu’ gi hilu’ lamasa.,I put the food on top of the table.,None,=== PAGE 35 ===
9,igt,5c,Manlokka’ siha.,They are tall.,None,=== PAGE 35 ===
10,igt,5d,Ma’estra atyu na palåo’an.,That woman is a teacher.,None,=== PAGE 35 ===
11,igt,5e,Para i tenda i famagu’un.,The children are heading to the store.,None,=== PAGE 35 ===
12,igt,10a,Manmalak månu?,Where did they go?,None,=== PAGE 37 ===
13,igt,10b,Para i tenda.,He headed to the store.,None,=== PAGE 37 ===
14,inline,8,dies,ten,None,=== PAGE 37 ===
15,inline,8,guaiya,love,None,=== PAGE 37 ===
16,inline,8,kuentus,speak,None,=== PAGE 37 ===
17,inline,9,plånta,set,None,=== PAGE 37 ===
18,inline,9,tristi,sad,None,=== PAGE 37 ===
19,igt,11a,Manmalak måmanu?,Where are they going?,None,=== PAGE 38 ===
20,igt,11b,Para i tetenda.,He is heading to the store.,None,=== PAGE 38 ===
21,igt,12,Ma’estrun Juan.,He is Juan’s teacher.,None,=== PAGE 38 ===
22,igt,13,Ma’estrun Juajuan ha’.,He is still Juan’s teacher.,None,=== PAGE 38 ===
23,igt,14a,"Si Paul Santos, guiya esti hu penta anai ha fa...",Paul Santos is the one I drew while he was was...,(Alamagan 16),=== PAGE 39 ===
24,igt,14b,Ha li’i’ na ginin i Gima’ Yuyu’us si nanå-ña.,She saw that her mother was heading from the c...,(Dibota 7-8),=== PAGE 39 ===
25,igt,14c,U’uchan.,It’s raining.,None,=== PAGE 39 ===
26,igt,15a,"Anai ma baba, humuyung påtgun.","When they opened it, a child came out.",(Cooreman 1983: 107),=== PAGE 39 ===
27,igt,15b,Ha nå’i guatu ni na’-ña ya sinangåni na para u...,She gave him his food and told him that he sho...,(Cooreman 1983: 79-80),=== PAGE 39 ===
28,igt,15c,Pues duru uchan.,Then it rained hard.,None,=== PAGE 39 ===
29,igt,16,Todu diha nai umåssun gi tatalo’-ña.,All day [the turtle] lay on its back.,(Igu 4),=== PAGE 40 ===
30,igt,17,"Mana’kabålis i kareta, mana’kabåbalis i kareta...","[a factory where] the car is assembled, the ca...",(from a tape-recorded narrative),=== PAGE 40 ===
31,igt,18a,Manhåhatsa guma’.,He builds houses (e.g. as his profession).,None,=== PAGE 40 ===
32,igt,18b,Maila’ ya ta aplika giya hita håfa ta sangånga...,Come and let us (incl.) apply to ourselves (in...,"(Ginen I Obispo August 9, 2009)",=== PAGE 40 ===
33,igt,19a,Sessu yu’ di mapångun as nanå-hu yan tatå-hu.,Often I was awakened by my mother and father.,(Familia 4),=== PAGE 41 ===
34,igt,19b,"Kada ma kumprendi una kosa, umannuk ottra kosa...","Every time they understand one thing, another ...","(Ginen I Obispo August 9, 2009)",=== PAGE 41 ===
35,igt,19c,Magåhit na uchan todu i tiempu giya Guåhan.,It’s true that it rains all the time in Guam.,None,=== PAGE 41 ===
36,igt,20,Na’tutungu’ ham håfa hinassosom-mu put esti na...,Keep on letting us (excl.) know what you think...,(from an e-mail message),=== PAGE 41 ===
37,igt,21a,Guaha gaigi gi papa’ lamasa.,There’s someone who is under the table.,None,=== PAGE 41 ===
38,igt,21b,Ha tungu’ ha’ na mahettuk kaskarå-ña.,[The turtle] knew that its shell was hard.,(Igu 3),=== PAGE 41 ===
39,igt,21c,Ti gof maipi an puengi.,It’s not so hot when it’s evening.,None,=== PAGE 42 ===
40,igt,21d,"Kada tristi håo, lalålu’ yu’.","Every time you’re sad, I’m angry.",None,=== PAGE 42 ===
41,igt,22a,Ya-hu ha’ mofo’na påpa’ gi chalan.,I would enjoy going ahead down the road.,None,=== PAGE 42 ===
42,igt,22b,"Lokkui’ hunggan, hu kumprendi ha’ na siempri b...","And yes, I do understand that you are really k...",(from a letter),=== PAGE 42 ===
43,igt,23a,Esta mamaipi.,It was getting hotter.,None,=== PAGE 42 ===
44,igt,23b,"Intri mås tiempu, mås triristi yu’.","As time goes on, I get sadder and sadder.",None,=== PAGE 42 ===
45,igt,24a,Guaha gagaigi ha’ gi papa’ lamasa.,There’s someone who is still under the table.,None,=== PAGE 42 ===
46,igt,24b,Todu i tiempu siempri meggagai-ña ha’ kuestion...,Always there will surely be more questions tha...,"(Ginen I Obispo August 9, 2009)",=== PAGE 43 ===
47,igt,24c,Hu hahassu ha’ atyu na tiempu anai påpatgun yu’.,I still remember the time when I was a child.,None,=== PAGE 43 ===
48,igt,25a,Frefresku i hanum kada manhånåo ham guatu.,The water is fresh every time we (excl.) go th...,None,=== PAGE 43 ===
49,igt,25b,Fresku i hanum kada manhånåo ham guatu.,The water is fresh every time we (excl.) go th...,None,=== PAGE 43 ===

In [ ]:
PDF_PATH = "/content/emenanjo2015grammar.pdf"
OUT_JSONL = "/content/emenanjo2015_parallel_extracted.jsonl"
OUT_CSV   = "/content/emenanjo2015_parallel_extracted.csv"

In [ ]:
doc = fitz.open(PDF_PATH)

rows = []
seen = set()

chunks = list(chunk_pages(doc))

for page_start, page_end, chunk_text in tqdm(
        chunks,
        desc="Extracting emenanjo2015 examples",
        unit="chunk"
    ):

    resp = client.responses.create(
        model=MODEL,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": chunk_text},
        ],
        # temperature=0,
    )
    try:
      items = parse_json_list(resp.output_text)

      for it in items:
          if not isinstance(it, dict):
              continue

          obj = (it.get("object_language") or "").strip()
          trn = (it.get("translation") or "").strip()

          if not obj or not trn:
              continue
          if LEAK.search(obj):
              continue

          key = (it.get("type"), obj, trn)
          if key in seen:
              continue
          seen.add(key)

          if not it.get("page_hint"):
              it["page_hint"] = f"{page_start}-{page_end}"

          rows.append(it)
    except:
      pass



# Save
with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print("Extracted:", len(df))
display(df.head(30))
print("Saved:", OUT_JSONL)
print("Saved:", OUT_CSV)

Extracting emenanjo2015 examples:   0%|          | 0/38 [00:00<?, ?chunk/s]

Extracted: 1094

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,inline,None,oke,None,male,None,=== PAGE 59 ===,In noun class languages as those found in Afri...,"The use of oke ‘male’, nwunyè ‘female’ to mark..."
1,inline,None,nwunyè,None,female,None,=== PAGE 59 ===,In noun class languages as those found in Afri...,"The use of oke ‘male’, nwunyè ‘female’ to mark..."
2,inline,None,uri/akwukwo mmuo,None,different indigenous writing systems,None,=== PAGE 69 ===,Different indigenous writing systems called ur...,But the orthography first used in a pan-Igbo w...
3,inline,None,Òtu Sùbakwanù Ìgbò,None,Society for Promoting Igbo Language and Cultur...,None,=== PAGE 72 ===,the emergence of learned societies like the Ig...,All of the above are designed to complement th...
4,inline,None,bùre-è-kì,None,break,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
5,inline,None,bì-re-è-kì,None,break,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
6,inline,None,sùkulù,None,school,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
7,inline,None,sùkuùlù,None,school,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
8,inline,None,bo͠tù͠lù͠,None,bottle,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
9,inline,None,ka-pi͠-ti͠-nʌ,None,captain,None,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...
10,inline,None,-bi͠a,None,come,None,=== PAGE 85 ===,In view of the restrictions observed above abo...,"There are, at least, three ways of treating th..."
11,inline,None,-gwa,None,tell,None,=== PAGE 85 ===,In view of the restrictions observed above abo...,"There are, at least, three ways of treating th..."
12,inline,None,bìa,None,come,None,=== PAGE 86 ===,simple verbs have a LH pattern.,"Besides, it is observed that in different lect..."
13,inline,None,hìè,None,tie,None,=== PAGE 86 ===,simple verbs have a LH pattern.,"Besides, it is observed that in different lect..."
14,inline,None,jèé,None,go,None,=== PAGE 86 ===,simple verbs have a LH pattern.,"Besides, it is observed that in different lect..."
15,inline,None,bàá,None,enter,None,=== PAGE 86 ===,simple verbs have a LH pattern.,"Besides, it is observed that in different lect..."
16,inline,None,ò͠bí͠á,None,visitor,None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
17,inline,None,ò͠bì͠à,None,visitor,None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
18,inline,None,ò͠bí͠à,None,visitor,None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
19,inline,None,óchìè,None,old; ancestor(s),None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
20,inline,None,òchíè,None,"old, ancestor(s)",None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
21,inline,None,óchíé,None,"old, ancestor(s)",None,=== PAGE 86 ===,"Besides, it is observed that in different lect...","In 1(a), 1(b)and 2(a) where the [CjS] is the e..."
22,inline,None,-ŋwà,None,try,None,=== PAGE 87 ===,Since the semi-vowel /w/ cannot be a consonant...,In the same way /kw/ in [kwu͠]’say’ is a unit ...
23,inline,None,kwu͠,None,say,None,=== PAGE 87 ===,In the same way /ŋw/ in /-ŋwà] ‘try’ is a unit...,"For in the Imperative: Affirmative, we have [k..."
24,inline,None,m͠pe,None,smallness,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:
25,inline,None,mbè,None,tortoise,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:
26,inline,None,m͠fe,None,lightness,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:
27,inline,None,mkpà,None,importance,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:
28,inline,None,m͠gba,None,wrestling; contest,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:
29,inline,None,mma̋,None,beauty,None,=== PAGE 87 ===,"Orthographically, however, the syllabic nasal ...",and n before other consonants:

Saved: /content/emenanjo2015_parallel_extracted.jsonl
Saved: /content/emenanjo2015_parallel_extracted.csv

In [ ]:
PDF_PATH = "/content/hewitt1995georgian.pdf"
OUT_JSONL = "/content/hewitt1995georgian_parallel_extracted.jsonl"
OUT_CSV   = "/content/hewitt1995georgian_parallel_extracted.csv"

doc = fitz.open(PDF_PATH)

rows = []
seen = set()

chunks = list(chunk_pages(doc))

for page_start, page_end, chunk_text in tqdm(
        chunks,
        desc="Extracting emenanjo2015 examples",
        unit="chunk"
    ):

    resp = client.responses.create(
        model=MODEL,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": chunk_text},
        ],
        # temperature=0,
    )
    try:

      items = parse_json_list(resp.output_text)

      for it in items:
          if not isinstance(it, dict):
              continue

          obj = (it.get("object_language") or "").strip()
          trn = (it.get("translation") or "").strip()

          if not obj or not trn:
              continue
          if LEAK.search(obj):
              continue

          key = (it.get("type"), obj, trn)
          if key in seen:
              continue
          seen.add(key)

          if not it.get("page_hint"):
              it["page_hint"] = f"{page_start}-{page_end}"

          rows.append(it)
    except:
      pass



# Save
with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print("Extracted:", len(df))
display(df.head(30))
print("Saved:", OUT_JSONL)
print("Saved:", OUT_CSV)

Extracting emenanjo2015 examples:   0%|          | 0/42 [00:00<?, ?chunk/s]

Extracted: 1105

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,inline,None,kart-v-el-i,None,Georgian,None,=== PAGE 29 ===,The origin of this confused thinking is perhap...,A Georgian calls himself kart-v-el-i (cf. sa-k...
1,inline,None,sa-kart-v-el-o,None,Georgia,None,=== PAGE 29 ===,The origin of this confused thinking is perhap...,A Georgian calls himself kart-v-el-i (cf. sa-k...
2,inline,None,kart-ul-i,None,Georgian (non-human),None,=== PAGE 29 ===,The origin of this confused thinking is perhap...,The Georgian expression for 'Kartvelian langua...
3,inline,None,kart-v-el-ur-i en-eb-i,None,Kartvelian languages,None,=== PAGE 29 ===,A Georgian calls himself kart-v-el-i (cf. sa-k...,"Regrettably, the language lacks the equivalent..."
4,inline,None,šušanik'is c'ameba,None,Martyrdom of St. Shushanik,None,=== PAGE 27 ===,The first native work of Georgian literature (...,The oldest dated manuscript thus far discovere...
5,inline,None,vepxist'q'aosani,None,The Man in the Panther's Skin,None,=== PAGE 28 ===,The most famous work of the mediaeval period i...,"It consists of 1598 quatrains, end-rhyming for..."
6,inline,None,kartlis cxovreba,None,History of Georgia,None,=== PAGE 28 ===,Mention should also be made of the chronicles ...,The three most important literary figures of t...
7,igt,None,ga+mo+m+cxv+ar-i,baked-AGR,baked,None,=== PAGE 34 ===,"For example, we could gloss each component of ...",To illustrate the second case let us take the ...
8,inline,None,sxiv-osan-i,None,spreading rays,None,=== PAGE 44 ===,That we are here dealing with morpho-phonemic ...,and sxiv-ur-i energia 'ray-energy/electro-magn...
9,inline,None,sxiv-ur-i energia,None,ray-energy/electro-magnetic energy,None,=== PAGE 44 ===,That we are here dealing with morpho-phonemic ...,"Indeed, the epenthetic rules outlined above ar..."
10,inline,None,sv-am,None,you drink,None,=== PAGE 44 ===,"In certain forms, such as the masdar, this suf...",(e.g. sv-am 'you drink' => s-m-a <= *sv-m-a 'd...
11,inline,None,s-m-a,None,drinking,None,=== PAGE 44 ===,"In certain forms, such as the masdar, this suf...",For roots ending in -v but accompanied by the ...
12,inline,None,jarcv-av,None,you rob X/them,None,=== PAGE 44 ===,For roots ending in -v but accompanied by the ...,(e.g. jarcv-av 'you rob X/them' => jarcv-a 'ro...
13,inline,None,jarcv-a,None,robbing,None,=== PAGE 44 ===,For roots ending in -v but accompanied by the ...,2.2.4.2 Radical vowels
14,inline,None,da-m-mal-a,None,X hid me,None,=== PAGE 45 ===,Geminate consonants are usually pronounced as ...,"(e.g. da-m-mal-a [dam:ala] 'X hid me', pas-s [..."
15,inline,None,pas-s a-d-eb-en,None,they put a price on X/them,None,=== PAGE 45 ===,Geminate consonants are usually pronounced as ...,"(e.g. da-m-mal-a [dam:ala] 'X hid me', pas-s [..."
16,inline,None,m-mart-v-el-i,None,governor,None,=== PAGE 45 ===,Geminate consonants are usually pronounced as ...,"(e.g. da-m-mal-a [dam:ala] 'X hid me', pas-s [..."
17,inline,None,v-c'ev-v-a+r,None,I am lying (prostrate),None,=== PAGE 45 ===,Geminate consonants are usually pronounced as ...,"(e.g. da-m-mal-a [dam:ala] 'X hid me', pas-s [..."
18,inline,None,v-varǰiš-ob,None,I exercise,None,=== PAGE 45 ===,Geminate consonants are usually pronounced as ...,"(e.g. da-m-mal-a [dam:ala] 'X hid me', pas-s [..."
19,inline,None,g-a-xl-a-v-a+r,None,I am,None,=== PAGE 45 ===,"However, there are instances where the grammat...","(e.g. g-a-xl-a-v-a+r <= *g-a-xl-av-v-a+r, whic..."
20,inline,None,v-a+r,None,I am,None,=== PAGE 45 ===,"However, there are instances where the grammat...","(e.g. g-a-xl-a-v-a+r <= *g-a-xl-av-v-a+r, whic..."
21,inline,None,g-a-xl-av-s,None,X is,None,=== PAGE 45 ===,"However, there are instances where the grammat...","(e.g. g-a-xl-a-v-a+r <= *g-a-xl-av-v-a+r, whic..."
22,inline,None,c'a-val,None,I shall go,None,=== PAGE 45 ===,"However, there are instances where the grammat...","(e.g. g-a-xl-a-v-a+r <= *g-a-xl-av-v-a+r, whic..."
23,inline,None,v-u-nax-av-v-a+r,None,X has/they have seen me,None,=== PAGE 45 ===,"Contrast, however,",2.2.5 Metathesis
24,inline,None,k'l-av,None,you kill X/them,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,(e.g. k'l-av 'you kill X/them' => k'vl-a <= Ol...
25,inline,None,k'vl-a,None,killing,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,(e.g. k'l-av 'you kill X/them' => k'vl-a <= Ol...
26,inline,None,xn-av,None,you plough X/them,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,(e.g. k'l-av 'you kill X/them' => k'vl-a <= Ol...
27,inline,None,xvn-a,None,ploughing,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,(e.g. k'l-av 'you kill X/them' => k'vl-a <= Ol...
28,inline,None,jr-av,None,you set X/them in motion,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,(e.g. k'l-av 'you kill X/them' => k'vl-a <= Ol...
29,inline,None,jvr-a,None,setting in motion,None,=== PAGE 45 ===,If this fricative comes into contact with one ...,The numeral '8' is rva.

Saved: /content/hewitt1995georgian_parallel_extracted.jsonl
Saved: /content/hewitt1995georgian_parallel_extracted.csv

In [ ]:
PDF_PATH = "/content/hualde2003grammar.pdf"
OUT_JSONL = "/content/hualde2003_parallel_extracted.jsonl"
OUT_CSV   = "/content/hualde2003_parallel_extracted.csv"

doc = fitz.open(PDF_PATH)

rows = []
seen = set()

chunks = list(chunk_pages(doc))

for page_start, page_end, chunk_text in tqdm(
        chunks,
        desc="Extracting emenanjo2015 examples",
        unit="chunk"
    ):

    resp = client.responses.create(
        model=MODEL,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": chunk_text},
        ],
        # temperature=0,
    )
    try:
      items = parse_json_list(resp.output_text)

      for it in items:
          if not isinstance(it, dict):
              continue

          obj = (it.get("object_language") or "").strip()
          trn = (it.get("translation") or "").strip()

          if not obj or not trn:
              continue
          if LEAK.search(obj):
              continue

          key = (it.get("type"), obj, trn)
          if key in seen:
              continue
          seen.add(key)

          if not it.get("page_hint"):
              it["page_hint"] = f"{page_start}-{page_end}"

          rows.append(it)
    except:
      pass


# Save
with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print("Extracted:", len(df))
display(df.head(30))
print("Saved:", OUT_JSONL)
print("Saved:", OUT_CSV)

Extracting emenanjo2015 examples:   0%|          | 0/50 [00:00<?, ?chunk/s]

Extracted: 3077

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,inline,None,euskara,None,Basque (the Basques’ name for their language).,None,=== PAGE 31 ===,"In post-Renaissance Spain, the name vizcaino, ...",Euskara is opposed to erdara (or erdera) 'fore...
1,inline,None,erdara,None,foreign language.,None,=== PAGE 31 ===,The Basques call their language euskara (and d...,Both words have an ending which very likely de...
2,inline,None,ibilera,None,way of walking.,None,=== PAGE 31 ===,Both words have an ending which very likely de...,In erdara the first element appears to be erdi...
3,inline,None,Euskal Herria,None,country of the Basque language.,None,=== PAGE 32 ===,Basque speakers refer to the land where their ...,"In the first decades of the 20th century, the ..."
4,inline,None,euskaldunak,None,those who have the Basque language.,None,=== PAGE 32 ===,Basque speakers refer to the land where their ...,"In the first decades of the 20th century, the ..."
5,inline,None,euzkera,None,a respelling of 'euskara' (used in the early 2...,None,=== PAGE 32 ===,"In the first decades of the 20th century, the ...",Related coinages of that vintage are the words...
6,inline,None,Euzkadi,None,Basque Country.,None,=== PAGE 32 ===,"In the first decades of the 20th century, the ...",The truly great and very influential Basque li...
7,inline,None,euzko,None,"Basque, in an ethnic or political sense.",None,=== PAGE 32 ===,Related coinages of that vintage are the words...,The truly great and very influential Basque li...
8,inline,None,euzkotar,None,Basque citizen; ethnic Basque.,None,=== PAGE 32 ===,Related coinages of that vintage are the words...,The truly great and very influential Basque li...
9,inline,None,Eusko jaurlaritza,None,Basque government.,None,=== PAGE 32 ===,His wish was to avoid the misuse of words like...,He succesfully campaigned for terms like Eusko...
10,inline,None,euskara batua,None,unified Basque.,None,=== PAGE 35 ===,Taking these sociolinguistic facts into accoun...,"The resulting standard language, euskara batua..."
11,inline,None,ume zahar,None,old child.,None,=== PAGE 37 ===,"In Navarre, the land of the Vascones of Roman ...","In the medieval Kingdom of Navarre, the most i..."
12,inline,None,gizon,None,man.,None,=== PAGE 37 ===,"To give a couple of examples, these inscriptio...","The Aquitanians, of whom classical authors lik..."
13,inline,None,andere,None,woman.,None,=== PAGE 37 ===,"To give a couple of examples, these inscriptio...","The Aquitanians, of whom classical authors lik..."
14,inline,None,guec ajutuezdugu,None,we have not V-ed it (or: we do not have it V-ed).,None,=== PAGE 39 ===,"The Basque evidence consists of two sentences,...",One of them is guec ajutuezdugu 'we have not V...
15,inline,None,ikastolak,None,language schools,None,=== PAGE 41 ===,Brief overview of the external history 11 lang...,"After a hiatus, the Basque Academy was also al..."
16,inline,None,euskara batua,None,unified Basque,None,=== PAGE 41 ===,"After a hiatus, the Basque Academy was also al...","After General Franco's death in 1975, the Basq..."
17,inline,None,jan,None,to eat,None,=== PAGE 56 ===,"Some Bizkaian, Low Navarrese and High Navarres...",Some speakers also pronounce intervocalic i as...
18,inline,None,leiho,None,window,None,=== PAGE 56 ===,Some speakers also pronounce intervocalic i as...,None
19,inline,None,mahaia,None,the table,None,=== PAGE 56 ===,Some speakers also pronounce intervocalic i as...,None
20,inline,None,zürra,None,beat up,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
21,inline,None,apärta,None,blow,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
22,inline,None,aizina,None,leisure,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
23,inline,None,bedezi,None,physician,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
24,inline,None,loza,None,slate,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
25,inline,None,aiza,None,easy,(examples from Lafon 1958),=== PAGE 56 ===,The phonemes /z/ and /g/ occur almost exclusiv...,Word-finally the voiced/voiceless distinction ...
26,inline,None,jo,None,money,None,=== PAGE 56 ===,Word-finally the voiced/voiceless distinction ...,"Like in Gascon and other Romance languages, wo..."
27,inline,None,soza,None,the money,None,=== PAGE 56 ===,Word-finally the voiced/voiceless distinction ...,"Like in Gascon and other Romance languages, wo..."
28,inline,None,ez axol,None,nonchalant,None,=== PAGE 56 ===,"Like in Gascon and other Romance languages, wo...",In Zuberoan iy is also the result of *j- (see ...
29,inline,None,dana jan dau,None,has eaten everything,(examples from Lekeitio),=== PAGE 56 ===,The voiced prepalatal fricative /y also occurs...,None

Saved: /content/hualde2003_parallel_extracted.jsonl
Saved: /content/hualde2003_parallel_extracted.csv

In [ ]:
t

In [ ]:
PDF_PATH = "/content/martin1992reference.pdf"
OUT_JSONL = "/content/martin1992_parallel_extracted.jsonl"
OUT_CSV   = "/content/martin1992_parallel_extracted.csv"

doc = fitz.open(PDF_PATH)

rows = []
seen = set()

chunks = list(chunk_pages(doc))

for page_start, page_end, chunk_text in tqdm(
        chunks,
        desc="Extracting emenanjo2015 examples",
        unit="chunk"
    ):

    resp = client.responses.create(
        model=MODEL,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": chunk_text},
        ],
        # temperature=0,
    )
    try:
      items = parse_json_list(resp.output_text)

      for it in items:
          if not isinstance(it, dict):
              continue

          obj = (it.get("object_language") or "").strip()
          trn = (it.get("translation") or "").strip()

          if not obj or not trn:
              continue
          if LEAK.search(obj):
              continue

          key = (it.get("type"), obj, trn)
          if key in seen:
              continue
          seen.add(key)

          if not it.get("page_hint"):
              it["page_hint"] = f"{page_start}-{page_end}"

          rows.append(it)
    except:
      pass


# Save
with open(OUT_JSONL, "w", encoding="utf-8") as f:
    for r in rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

print("Extracted:", len(df))
display(df.head(30))
print("Saved:", OUT_JSONL)
print("Saved:", OUT_CSV)

Extracting emenanjo2015 examples:   0%|          | 0/112 [00:00<?, ?chunk/s]

Extracted: 513

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,inline,None,koki,None,meat,None,=== PAGE 16 ===,When a Korean citation is within an English se...,The macron is usctl to mlrk long vowels in nxr...
1,inline,None,rer 'time' - a'ni han te't ey,None,in a short while,None,=== PAGE 71 ===,A number of nouns suppress the high pitch on a...,For at least one word this holds for the genit...
2,inline,None,ti tpo'l ay,None,in this village,(1459 Wel 8:94a),=== PAGE 71 ===,Monosyllabic nouns which do not lose their acc...,'s/cwurn 'dream'.
3,inline,None,'mwo'h ay s,None,mountain,None,=== PAGE 71 ===,In the same environment (before the locative m...,"""swo,t 'deep inside' * 'swo.kay s (1481 Twusi ..."
4,inline,None,'nvol.h ay,None,to the beams,(1481 Twusi 7:5a),=== PAGE 71 ===,In the same environment (before the locative m...,Usually the double dot is retained: nwu n ey s...
5,inline,None,nwu n ey s 'tol,None,moonlight on the snow,(1482 Kum-sam 2:6lb),=== PAGE 71 ===,Usually the double dot is retained:,'mul s 'ko'z ay (1459 Wel 8:99a) 'at the water...
6,inline,None,'mul s 'ko'z ay,None,at the water's edge,(1459 Wel 8:99a),=== PAGE 71 ===,Usually the double dot is retained: nwu n ey s...,"f- s) ""i'I ey (1475 Nay 2:2:47b) 'in the event..."
7,inline,None,'wiy'h ey 'sye,None,in back,None,=== PAGE 71 ===,Usually the double dot is retained: ... 'wiy'h...,The modern dialects of Hamkyeng and Kyengsang ...
8,inline,None,'srvoy ku'lus'tiki 'yey s'swo.h i'lo,None,it is a mold for making metal vessels,(1465 Wen l:l:2:l8la),=== PAGE 72 ===,"The summative -'li is nonleniting, and that ac...","Interestingly, when the summative -'li started..."
9,inline,None,Salkem sallye cwii,None,Save me!,None,=== PAGE 89 ===,The last word of Salkem sallye cwii 'Save me!'...,Similar are I ke(s) pr-l 'Look at this!'and Ka...
10,inline,None,Na com cwii,None,Give me some!,None,=== PAGE 89 ===,The last word of Salkem sallye cwii 'Save me!'...,Similar are I ke(s) pr-l 'Look at this!'and Ka...
11,inline,None,I ke(s) pr-l,None,Look at this!,None,=== PAGE 89 ===,Similar are I ke(s) pr-l 'Look at this!'and Ka...,CM 1:119 is confused about these forms and tho...
12,inline,None,Ka-p6,None,Go and see!,None,=== PAGE 89 ===,Similar are I ke(s) pr-l 'Look at this!'and Ka...,CM 1:119 is confused about these forms and tho...
13,inline,None,twii si 'myen,None,if it's two o'clock,None,=== PAGE 89 ===,The stems i- 'it is' and hu- 'does; is' are of...,In this book the abbreviation is shown by an a...
14,inline,None,pala'ci,None,it's the sea,None,=== PAGE 89 ===,The stems i- 'it is' and hu- 'does; is' are of...,In this book the abbreviation is shown by an a...
15,inline,None,ka ya'keyss.ta,None,I'll have to go,None,=== PAGE 89 ===,The stems i- 'it is' and hu- 'does; is' are of...,In this book the abbreviation is shown by an a...
16,inline,None,Ese ka,None,Go on!,None,=== PAGE 89 ===,The infinitive has a zero alternant after cert...,In the intimate style we find commands like Es...
17,inline,None,I ke l'sa,None,Buy this!,None,=== PAGE 89 ===,The infinitive has a zero alternant after cert...,In the intimate style we find commands like Es...
18,inline,None,po' to tut' lo mds hanta,None,can neither see nor hear,None,=== PAGE 89 ===,There are a few word abbreviations like po' to...,In Middle Korean the l.- forms could attach di...
19,inline,None,o' lo kl' to ulds hnnlu,None,can neither come nor go,None,=== PAGE 89 ===,There are a few word abbreviations like po' to...,In Middle Korean the l.- forms could attach di...
20,inline,None,olut lo nayti' io m(is hunlir,None,can neither rise nor fall,None,=== PAGE 89 ===,There are a few word abbreviations like po' to...,In Middle Korean the l.- forms could attach di...
21,inline,None,wuli nala 'ta,None,it's our country,None,=== PAGE 91 ===,"On the other hand, it sounds pedantic or booki...",The shortened forms of the plain and prospecti...
22,inline,None,salkhoki,None,red meat,None,=== PAGE 103 ===,"Historically, there are nouns that once endetl...",The etyma have left rnorphophonemic relics in ...
23,inline,None,anphakk,None,inside and outside,None,=== PAGE 103 ===,"Historically, there are nouns that once endetl...",The etyma have left rnorphophonemic relics in ...
24,inline,None,swukhay,None,male dog,None,=== PAGE 103 ===,"Historically, there are nouns that once endetl...",The etyma have left rnorphophonemic relics in ...
25,inline,None,amkhay,None,female dog,None,=== PAGE 103 ===,"Historically, there are nouns that once endetl...",The etyma have left rnorphophonemic relics in ...
26,inline,None,pyepssi,None,rice seed,None,=== PAGE 103 ===,There are also relics of excess at the beginni...,"For the inflectional stems ending in -.1-, whi..."
27,inline,None,ipssal,None,raw rice,None,=== PAGE 103 ===,There are also relics of excess at the beginni...,"For the inflectional stems ending in -.1-, whi..."
28,inline,None,chiptte,None,looking with raised eyes,None,=== PAGE 103 ===,There are also relics of excess at the beginni...,"For the inflectional stems ending in -.1-, whi..."
29,inline,None,namk,None,tree,None,=== PAGE 103 ===,There are a tbw archaic examples of excess mk ...,These go back to MK nouns that had two allomor...

Saved: /content/martin1992_parallel_extracted.jsonl
Saved: /content/martin1992_parallel_extracted.csv