In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

import numpy as np
import json

from google.colab import userdata
import os

In [ ]:
%%capture
!pip install sacrebleu evaluate
!pip install -U huggingface_hub

In [ ]:
from huggingface_hub import login
hf_token = userdata.get('hf_token')
login(token=hf_token)

In [ ]:
!hf auth whoami

✓ Logged in
  user: dotnw

## API

In [ ]:
import openai
import time

api_key = userdata.get('openai_token')
client = openai.OpenAI(api_key=api_key)

In [ ]:
import evaluate
chrf = evaluate.load("chrf")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
#!pip install --upgrade jax jaxlib

In [ ]:
import tiktoken

def truncate_to_limit(text, model, limit=120000):

    enc = tiktoken.get_encoding("o200k_base")

    tokens = enc.encode(text)

    if len(tokens) > limit:
        tokens = tokens[:limit]

    return enc.decode(tokens)

## Datasets

In [ ]:
%%capture
!pip install datasets
!pip install pycountry
from datasets import load_dataset
import pycountry

In [ ]:
def get_iso_codes(lang_name):
    """Автоматически находит коды 639-1 и 639-3 по названию языка"""
    try:
        language = pycountry.languages.lookup(lang_name)
        return {
            'alpha_2': getattr(language, 'alpha_2', None), # 'ig'
            'alpha_3': getattr(language, 'alpha_3', None)  # 'ibo'
        }
    except LookupError:
        return None

In [ ]:
def load_all_corpora():
    """Загружает основные датасеты один раз и возвращает словарь с объектами."""
    print("Loading data...")
    corpora = {}

    try:
        print("FLORES+")
        corpora['flores'] = load_dataset("openlanguagedata/flores_plus", split="devtest")

        print("OLDI...")
        corpora['oldi'] = load_dataset("openlanguagedata/oldi_seed", split="train")

        print("Done.")
    except Exception as e:
        print(f" Error: {e}")

    return corpora

# Запускаем один раз
loaded_corpora = load_all_corpora()

Loading data...
FLORES+

README.md:   0%|          | 0.00/74.4k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/226 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/226 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/226 [00:00<?, ?files/s]

acq_Arab.jsonl:   0%|          | 0.00/496k [00:00<?, ?B/s]

ary_Arab.jsonl:   0%|          | 0.00/493k [00:00<?, ?B/s]

ars_Arab.jsonl:   0%|          | 0.00/498k [00:00<?, ?B/s]

ace_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

apc_Arab_sout3123.jsonl:   0%|          | 0.00/484k [00:00<?, ?B/s]

amh_Ethi.jsonl:   0%|          | 0.00/516k [00:00<?, ?B/s]

ace_Arab.jsonl:   0%|          | 0.00/487k [00:00<?, ?B/s]

arg_Latn.jsonl:   0%|          | 0.00/445k [00:00<?, ?B/s]

afr_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

als_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

acm_Arab.jsonl:   0%|          | 0.00/494k [00:00<?, ?B/s]

apc_Arab_nort3139.jsonl:   0%|          | 0.00/484k [00:00<?, ?B/s]

arz_Arab.jsonl:   0%|          | 0.00/494k [00:00<?, ?B/s]

aeb_Arab.jsonl:   0%|          | 0.00/491k [00:00<?, ?B/s]

arb_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

arb_Arab.jsonl:   0%|          | 0.00/498k [00:00<?, ?B/s]

ayr_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

ast_Latn.jsonl:   0%|          | 0.00/430k [00:00<?, ?B/s]

asm_Beng.jsonl:   0%|          | 0.00/620k [00:00<?, ?B/s]

awa_Deva.jsonl:   0%|          | 0.00/613k [00:00<?, ?B/s]

azb_Arab.jsonl:   0%|          | 0.00/502k [00:00<?, ?B/s]

bam_Latn.jsonl:   0%|          | 0.00/428k [00:00<?, ?B/s]

bak_Cyrl.jsonl:   0%|          | 0.00/531k [00:00<?, ?B/s]

ban_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

azj_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

bel_Cyrl.jsonl:   0%|          | 0.00/560k [00:00<?, ?B/s]

bod_Tibt.jsonl:   0%|          | 0.00/716k [00:00<?, ?B/s]

bjn_Arab.jsonl:   0%|          | 0.00/509k [00:00<?, ?B/s]

bem_Latn.jsonl:   0%|          | 0.00/453k [00:00<?, ?B/s]

bho_Deva.jsonl:   0%|          | 0.00/608k [00:00<?, ?B/s]

ben_Beng.jsonl:   0%|          | 0.00/627k [00:00<?, ?B/s]

bjn_Latn.jsonl:   0%|          | 0.00/430k [00:00<?, ?B/s]

bos_Latn.jsonl:   0%|          | 0.00/427k [00:00<?, ?B/s]

bug_Latn.jsonl:   0%|          | 0.00/436k [00:00<?, ?B/s]

brx_Deva.jsonl:   0%|          | 0.00/650k [00:00<?, ?B/s]

bul_Cyrl.jsonl:   0%|          | 0.00/535k [00:00<?, ?B/s]

ceb_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

cat_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

cjk_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

ces_Latn.jsonl:   0%|          | 0.00/433k [00:00<?, ?B/s]

chv_Cyrl.jsonl:   0%|          | 0.00/539k [00:00<?, ?B/s]

ckb_Arab.jsonl:   0%|          | 0.00/530k [00:00<?, ?B/s]

dar_Cyrl.jsonl:   0%|          | 0.00/564k [00:00<?, ?B/s]

cmn_Hant.jsonl:   0%|          | 0.00/409k [00:00<?, ?B/s]

dan_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

crh_Latn.jsonl:   0%|          | 0.00/439k [00:00<?, ?B/s]

cym_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

cmn_Hans.jsonl:   0%|          | 0.00/414k [00:00<?, ?B/s]

deu_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/423k [00:00<?, ?B/s]

dyu_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

dgo_Deva.jsonl:   0%|          | 0.00/639k [00:00<?, ?B/s]

dzo_Tibt.jsonl:   0%|          | 0.00/761k [00:00<?, ?B/s]

eus_Latn.jsonl:   0%|          | 0.00/431k [00:00<?, ?B/s]

epo_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

ell_Grek.jsonl:   0%|          | 0.00/571k [00:00<?, ?B/s]

ekk_Latn.jsonl:   0%|          | 0.00/424k [00:00<?, ?B/s]

fao_Latn.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

dik_Latn.jsonl:   0%|          | 0.00/419k [00:00<?, ?B/s]

ewe_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

fij_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

fil_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

fin_Latn.jsonl:   0%|          | 0.00/436k [00:00<?, ?B/s]

fon_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

fur_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

fuv_Latn.jsonl:   0%|          | 0.00/418k [00:00<?, ?B/s]

fra_Latn.jsonl:   0%|          | 0.00/452k [00:00<?, ?B/s]

glg_Latn.jsonl:   0%|          | 0.00/439k [00:00<?, ?B/s]

gaz_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

gla_Latn.jsonl:   0%|          | 0.00/459k [00:00<?, ?B/s]

guj_Gujr.jsonl:   0%|          | 0.00/612k [00:00<?, ?B/s]

gle_Latn.jsonl:   0%|          | 0.00/452k [00:00<?, ?B/s]

hat_Latn.jsonl:   0%|          | 0.00/416k [00:00<?, ?B/s]

gug_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

gom_Deva.jsonl:   0%|          | 0.00/617k [00:00<?, ?B/s]

hin_Deva.jsonl:   0%|          | 0.00/619k [00:00<?, ?B/s]

hau_Latn.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

heb_Hebr.jsonl:   0%|          | 0.00/472k [00:00<?, ?B/s]

hne_Deva.jsonl:   0%|          | 0.00/608k [00:00<?, ?B/s]

hrv_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

hun_Latn.jsonl:   0%|          | 0.00/442k [00:00<?, ?B/s]

ind_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

ibo_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

hye_Armn.jsonl:   0%|          | 0.00/555k [00:00<?, ?B/s]

isl_Latn.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

ilo_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

jpn_Jpan.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

jav_Latn.jsonl:   0%|          | 0.00/428k [00:00<?, ?B/s]

kam_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

kac_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

ita_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

kab_Latn.jsonl:   0%|          | 0.00/430k [00:00<?, ?B/s]

kan_Knda.jsonl:   0%|          | 0.00/655k [00:00<?, ?B/s]

kas_Deva.jsonl:   0%|          | 0.00/599k [00:00<?, ?B/s]

kas_Arab.jsonl:   0%|          | 0.00/514k [00:00<?, ?B/s]

kaz_Cyrl.jsonl:   0%|          | 0.00/534k [00:00<?, ?B/s]

kbp_Latn.jsonl:   0%|          | 0.00/471k [00:00<?, ?B/s]

kat_Geor.jsonl:   0%|          | 0.00/670k [00:00<?, ?B/s]

kea_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

khm_Khmr.jsonl:   0%|          | 0.00/725k [00:00<?, ?B/s]

kin_Latn.jsonl:   0%|          | 0.00/441k [00:00<?, ?B/s]

kmb_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

khk_Cyrl.jsonl:   0%|          | 0.00/539k [00:00<?, ?B/s]

kik_Latn.jsonl:   0%|          | 0.00/461k [00:00<?, ?B/s]

kir_Cyrl.jsonl:   0%|          | 0.00/533k [00:00<?, ?B/s]

kmr_Latn.jsonl:   0%|          | 0.00/436k [00:00<?, ?B/s]

kjh_Cyrl.jsonl:   0%|          | 0.00/549k [00:00<?, ?B/s]

knc_Arab.jsonl:   0%|          | 0.00/498k [00:00<?, ?B/s]

ktu_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

kor_Hang.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

knc_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

lao_Laoo.jsonl:   0%|          | 0.00/642k [00:00<?, ?B/s]

lit_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

lim_Latn.jsonl:   0%|          | 0.00/431k [00:00<?, ?B/s]

lld_Latn_gard1241.jsonl:   0%|          | 0.00/436k [00:00<?, ?B/s]

ltz_Latn.jsonl:   0%|          | 0.00/442k [00:00<?, ?B/s]

lin_Latn.jsonl:   0%|          | 0.00/433k [00:00<?, ?B/s]

lld_Latn.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

ltg_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

lij_Latn.jsonl:   0%|          | 0.00/443k [00:00<?, ?B/s]

lug_Latn.jsonl:   0%|          | 0.00/427k [00:00<?, ?B/s]

lmo_Latn.jsonl:   0%|          | 0.00/443k [00:00<?, ?B/s]

lus_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

lua_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

lvs_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

luo_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

mag_Deva.jsonl:   0%|          | 0.00/608k [00:00<?, ?B/s]

mal_Mlym.jsonl:   0%|          | 0.00/689k [00:00<?, ?B/s]

mfe_Latn.jsonl:   0%|          | 0.00/415k [00:00<?, ?B/s]

mai_Deva.jsonl:   0%|          | 0.00/616k [00:00<?, ?B/s]

min_Arab.jsonl:   0%|          | 0.00/515k [00:00<?, ?B/s]

mhr_Cyrl.jsonl:   0%|          | 0.00/539k [00:00<?, ?B/s]

mar_Deva.jsonl:   0%|          | 0.00/633k [00:00<?, ?B/s]

min_Latn.jsonl:   0%|          | 0.00/431k [00:00<?, ?B/s]

mlt_Latn.jsonl:   0%|          | 0.00/443k [00:00<?, ?B/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/535k [00:00<?, ?B/s]

mni_Beng.jsonl:   0%|          | 0.00/645k [00:00<?, ?B/s]

mos_Latn.jsonl:   0%|          | 0.00/428k [00:00<?, ?B/s]

mri_Latn.jsonl:   0%|          | 0.00/443k [00:00<?, ?B/s]

mni_Mtei.jsonl:   0%|          | 0.00/621k [00:00<?, ?B/s]

mya_Mymr.jsonl:   0%|          | 0.00/741k [00:00<?, ?B/s]

nqo_Nkoo.jsonl:   0%|          | 0.00/586k [00:00<?, ?B/s]

nso_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

nld_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

npi_Deva.jsonl:   0%|          | 0.00/620k [00:00<?, ?B/s]

myv_Cyrl.jsonl:   0%|          | 0.00/546k [00:00<?, ?B/s]

nob_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

nob_Latn_radical.jsonl:   0%|          | 0.00/431k [00:00<?, ?B/s]

nno_Latn.jsonl:   0%|          | 0.00/428k [00:00<?, ?B/s]

nus_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

nya_Latn.jsonl:   0%|          | 0.00/439k [00:00<?, ?B/s]

oci_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

oci_Latn_aran1260.jsonl:   0%|          | 0.00/445k [00:00<?, ?B/s]

ory_Orya.jsonl:   0%|          | 0.00/643k [00:00<?, ?B/s]

pap_Latn.jsonl:   0%|          | 0.00/433k [00:00<?, ?B/s]

pan_Guru.jsonl:   0%|          | 0.00/623k [00:00<?, ?B/s]

pag_Latn.jsonl:   0%|          | 0.00/424k [00:00<?, ?B/s]

pes_Arab.jsonl:   0%|          | 0.00/512k [00:00<?, ?B/s]

plt_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

pbt_Arab.jsonl:   0%|          | 0.00/511k [00:00<?, ?B/s]

quy_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

pol_Latn.jsonl:   0%|          | 0.00/439k [00:00<?, ?B/s]

ron_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

por_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

rus_Cyrl.jsonl:   0%|          | 0.00/550k [00:00<?, ?B/s]

run_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

sag_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

prs_Arab.jsonl:   0%|          | 0.00/502k [00:00<?, ?B/s]

sin_Sinh.jsonl:   0%|          | 0.00/633k [00:00<?, ?B/s]

shn_Mymr.jsonl:   0%|          | 0.00/794k [00:00<?, ?B/s]

scn_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

sat_Olck.jsonl:   0%|          | 0.00/650k [00:00<?, ?B/s]

san_Deva.jsonl:   0%|          | 0.00/631k [00:00<?, ?B/s]

slk_Latn.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

smo_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

snd_Arab.jsonl:   0%|          | 0.00/498k [00:00<?, ?B/s]

slv_Latn.jsonl:   0%|          | 0.00/426k [00:00<?, ?B/s]

som_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

snd_Deva.jsonl:   0%|          | 0.00/632k [00:00<?, ?B/s]

sot_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

spa_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

srp_Cyrl.jsonl:   0%|          | 0.00/524k [00:00<?, ?B/s]

srd_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

sna_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

ssw_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

swe_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

szl_Latn.jsonl:   0%|          | 0.00/436k [00:00<?, ?B/s]

tam_Taml.jsonl:   0%|          | 0.00/696k [00:00<?, ?B/s]

swh_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

sun_Latn.jsonl:   0%|          | 0.00/430k [00:00<?, ?B/s]

taq_Latn.jsonl:   0%|          | 0.00/425k [00:00<?, ?B/s]

tha_Thai.jsonl:   0%|          | 0.00/644k [00:00<?, ?B/s]

tpi_Latn.jsonl:   0%|          | 0.00/458k [00:00<?, ?B/s]

tel_Telu.jsonl:   0%|          | 0.00/637k [00:00<?, ?B/s]

tat_Cyrl.jsonl:   0%|          | 0.00/531k [00:00<?, ?B/s]

tgk_Cyrl.jsonl:   0%|          | 0.00/551k [00:00<?, ?B/s]

tir_Ethi.jsonl:   0%|          | 0.00/518k [00:00<?, ?B/s]

taq_Tfng.jsonl:   0%|          | 0.00/586k [00:00<?, ?B/s]

tso_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

tuk_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

tsn_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

tum_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

tur_Latn.jsonl:   0%|          | 0.00/437k [00:00<?, ?B/s]

tyv_Cyrl.jsonl:   0%|          | 0.00/562k [00:00<?, ?B/s]

udm_Cyrl.jsonl:   0%|          | 0.00/551k [00:00<?, ?B/s]

twi_Latn_akua1239.jsonl:   0%|          | 0.00/430k [00:00<?, ?B/s]

twi_Latn_asan1239.jsonl:   0%|          | 0.00/435k [00:00<?, ?B/s]

uig_Arab.jsonl:   0%|          | 0.00/545k [00:00<?, ?B/s]

umb_Latn.jsonl:   0%|          | 0.00/427k [00:00<?, ?B/s]

uzs_Arab.jsonl:   0%|          | 0.00/536k [00:00<?, ?B/s]

vec_Latn.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

urd_Arab.jsonl:   0%|          | 0.00/519k [00:00<?, ?B/s]

uzn_Latn.jsonl:   0%|          | 0.00/439k [00:00<?, ?B/s]

ukr_Cyrl.jsonl:   0%|          | 0.00/533k [00:00<?, ?B/s]

wol_Latn.jsonl:   0%|          | 0.00/422k [00:00<?, ?B/s]

vmw_Latn.jsonl:   0%|          | 0.00/445k [00:00<?, ?B/s]

war_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

vie_Latn.jsonl:   0%|          | 0.00/472k [00:00<?, ?B/s]

ydd_Hebr.jsonl:   0%|          | 0.00/541k [00:00<?, ?B/s]

wuu_Hans.jsonl:   0%|          | 0.00/415k [00:00<?, ?B/s]

yue_Hant.jsonl:   0%|          | 0.00/408k [00:00<?, ?B/s]

yor_Latn.jsonl:   0%|          | 0.00/459k [00:00<?, ?B/s]

xho_Latn.jsonl:   0%|          | 0.00/431k [00:00<?, ?B/s]

zgh_Tfng.jsonl:   0%|          | 0.00/583k [00:00<?, ?B/s]

zsm_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

zul_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

Downloading data:   0%|          | 0/220 [00:00<?, ?files/s]

aeb_Arab.jsonl:   0%|          | 0.00/512k [00:00<?, ?B/s]

afr_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

acm_Arab.jsonl:   0%|          | 0.00/514k [00:00<?, ?B/s]

apc_Arab_sout3123.jsonl:   0%|          | 0.00/505k [00:00<?, ?B/s]

als_Latn.jsonl:   0%|          | 0.00/467k [00:00<?, ?B/s]

acq_Arab.jsonl:   0%|          | 0.00/517k [00:00<?, ?B/s]

ace_Arab.jsonl:   0%|          | 0.00/508k [00:00<?, ?B/s]

apc_Arab_nort3139.jsonl:   0%|          | 0.00/504k [00:00<?, ?B/s]

ace_Latn.jsonl:   0%|          | 0.00/452k [00:00<?, ?B/s]

amh_Ethi.jsonl:   0%|          | 0.00/533k [00:00<?, ?B/s]

arb_Arab.jsonl:   0%|          | 0.00/519k [00:00<?, ?B/s]

ars_Arab.jsonl:   0%|          | 0.00/520k [00:00<?, ?B/s]

ary_Arab.jsonl:   0%|          | 0.00/514k [00:00<?, ?B/s]

arb_Latn.jsonl:   0%|          | 0.00/462k [00:00<?, ?B/s]

arz_Arab.jsonl:   0%|          | 0.00/514k [00:00<?, ?B/s]

arg_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

awa_Deva.jsonl:   0%|          | 0.00/638k [00:00<?, ?B/s]

ayr_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

azb_Arab.jsonl:   0%|          | 0.00/523k [00:00<?, ?B/s]

ast_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

asm_Beng.jsonl:   0%|          | 0.00/643k [00:00<?, ?B/s]

azj_Latn.jsonl:   0%|          | 0.00/475k [00:00<?, ?B/s]

bam_Latn.jsonl:   0%|          | 0.00/445k [00:00<?, ?B/s]

ban_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

bak_Cyrl.jsonl:   0%|          | 0.00/553k [00:00<?, ?B/s]

bem_Latn.jsonl:   0%|          | 0.00/469k [00:00<?, ?B/s]

bjn_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

bel_Cyrl.jsonl:   0%|          | 0.00/579k [00:00<?, ?B/s]

bod_Tibt.jsonl:   0%|          | 0.00/747k [00:00<?, ?B/s]

bho_Deva.jsonl:   0%|          | 0.00/636k [00:00<?, ?B/s]

bjn_Arab.jsonl:   0%|          | 0.00/531k [00:00<?, ?B/s]

ben_Beng.jsonl:   0%|          | 0.00/653k [00:00<?, ?B/s]

bos_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

bul_Cyrl.jsonl:   0%|          | 0.00/558k [00:00<?, ?B/s]

cat_Latn.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

bug_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

ceb_Latn.jsonl:   0%|          | 0.00/467k [00:00<?, ?B/s]

cat_Latn_vale1252.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

cjk_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

chv_Cyrl.jsonl:   0%|          | 0.00/546k [00:00<?, ?B/s]

ckb_Arab.jsonl:   0%|          | 0.00/552k [00:00<?, ?B/s]

cmn_Hant.jsonl:   0%|          | 0.00/424k [00:00<?, ?B/s]

ces_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

cmn_Hans.jsonl:   0%|          | 0.00/429k [00:00<?, ?B/s]

crh_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

dan_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

dik_Latn.jsonl:   0%|          | 0.00/434k [00:00<?, ?B/s]

cym_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

dyu_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

deu_Latn.jsonl:   0%|          | 0.00/464k [00:00<?, ?B/s]

dzo_Tibt.jsonl:   0%|          | 0.00/786k [00:00<?, ?B/s]

ell_Grek.jsonl:   0%|          | 0.00/595k [00:00<?, ?B/s]

epo_Latn.jsonl:   0%|          | 0.00/442k [00:00<?, ?B/s]

ekk_Latn.jsonl:   0%|          | 0.00/441k [00:00<?, ?B/s]

eus_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

ewe_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

fao_Latn.jsonl:   0%|          | 0.00/452k [00:00<?, ?B/s]

fil_Latn.jsonl:   0%|          | 0.00/474k [00:00<?, ?B/s]

fij_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

fon_Latn.jsonl:   0%|          | 0.00/475k [00:00<?, ?B/s]

fur_Latn.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

fin_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

fuv_Latn.jsonl:   0%|          | 0.00/433k [00:00<?, ?B/s]

gaz_Latn.jsonl:   0%|          | 0.00/467k [00:00<?, ?B/s]

fra_Latn.jsonl:   0%|          | 0.00/472k [00:00<?, ?B/s]

hat_Latn.jsonl:   0%|          | 0.00/432k [00:00<?, ?B/s]

glg_Latn.jsonl:   0%|          | 0.00/458k [00:00<?, ?B/s]

gla_Latn.jsonl:   0%|          | 0.00/477k [00:00<?, ?B/s]

gle_Latn.jsonl:   0%|          | 0.00/470k [00:00<?, ?B/s]

gug_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

guj_Gujr.jsonl:   0%|          | 0.00/639k [00:00<?, ?B/s]

hau_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

heb_Hebr.jsonl:   0%|          | 0.00/491k [00:00<?, ?B/s]

hne_Deva.jsonl:   0%|          | 0.00/634k [00:00<?, ?B/s]

hrv_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

hun_Latn.jsonl:   0%|          | 0.00/460k [00:00<?, ?B/s]

hin_Deva.jsonl:   0%|          | 0.00/645k [00:00<?, ?B/s]

hye_Armn.jsonl:   0%|          | 0.00/577k [00:00<?, ?B/s]

ibo_Latn.jsonl:   0%|          | 0.00/469k [00:00<?, ?B/s]

ilo_Latn.jsonl:   0%|          | 0.00/468k [00:00<?, ?B/s]

isl_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

ita_Latn.jsonl:   0%|          | 0.00/465k [00:00<?, ?B/s]

ind_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

jav_Latn.jsonl:   0%|          | 0.00/445k [00:00<?, ?B/s]

kaa_Latn.jsonl:   0%|          | 0.00/464k [00:00<?, ?B/s]

jpn_Jpan.jsonl:   0%|          | 0.00/475k [00:00<?, ?B/s]

kab_Latn.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

kac_Latn.jsonl:   0%|          | 0.00/477k [00:00<?, ?B/s]

kam_Latn.jsonl:   0%|          | 0.00/441k [00:00<?, ?B/s]

kas_Deva.jsonl:   0%|          | 0.00/625k [00:00<?, ?B/s]

kat_Geor.jsonl:   0%|          | 0.00/697k [00:00<?, ?B/s]

kea_Latn.jsonl:   0%|          | 0.00/442k [00:00<?, ?B/s]

kan_Knda.jsonl:   0%|          | 0.00/683k [00:00<?, ?B/s]

kbp_Latn.jsonl:   0%|          | 0.00/488k [00:00<?, ?B/s]

kas_Arab.jsonl:   0%|          | 0.00/536k [00:00<?, ?B/s]

kaz_Cyrl.jsonl:   0%|          | 0.00/558k [00:00<?, ?B/s]

khk_Cyrl.jsonl:   0%|          | 0.00/560k [00:00<?, ?B/s]

khk_Mong.jsonl:   0%|          | 0.00/763k [00:00<?, ?B/s]

khm_Khmr.jsonl:   0%|          | 0.00/743k [00:00<?, ?B/s]

kjh_Cyrl.jsonl:   0%|          | 0.00/567k [00:00<?, ?B/s]

kir_Cyrl.jsonl:   0%|          | 0.00/558k [00:00<?, ?B/s]

kik_Latn.jsonl:   0%|          | 0.00/478k [00:00<?, ?B/s]

kin_Latn.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

kmb_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

ktu_Latn.jsonl:   0%|          | 0.00/458k [00:00<?, ?B/s]

kmr_Latn.jsonl:   0%|          | 0.00/453k [00:00<?, ?B/s]

knc_Arab.jsonl:   0%|          | 0.00/519k [00:00<?, ?B/s]

lim_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

kor_Hang.jsonl:   0%|          | 0.00/466k [00:00<?, ?B/s]

lij_Latn.jsonl:   0%|          | 0.00/462k [00:00<?, ?B/s]

lin_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

lao_Laoo.jsonl:   0%|          | 0.00/668k [00:00<?, ?B/s]

knc_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

lit_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

ltg_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

ltz_Latn.jsonl:   0%|          | 0.00/460k [00:00<?, ?B/s]

lld_Latn.jsonl:   0%|          | 0.00/453k [00:00<?, ?B/s]

lld_Latn_gard1241.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

lua_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

lmo_Latn.jsonl:   0%|          | 0.00/461k [00:00<?, ?B/s]

lug_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

luo_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

lvs_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

mai_Deva.jsonl:   0%|          | 0.00/643k [00:00<?, ?B/s]

lus_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

mar_Deva.jsonl:   0%|          | 0.00/664k [00:00<?, ?B/s]

mal_Mlym.jsonl:   0%|          | 0.00/720k [00:00<?, ?B/s]

mfe_Latn.jsonl:   0%|          | 0.00/433k [00:00<?, ?B/s]

mag_Deva.jsonl:   0%|          | 0.00/635k [00:00<?, ?B/s]

min_Arab.jsonl:   0%|          | 0.00/539k [00:00<?, ?B/s]

mni_Beng.jsonl:   0%|          | 0.00/676k [00:00<?, ?B/s]

mlt_Latn.jsonl:   0%|          | 0.00/462k [00:00<?, ?B/s]

mos_Latn.jsonl:   0%|          | 0.00/443k [00:00<?, ?B/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/559k [00:00<?, ?B/s]

min_Latn.jsonl:   0%|          | 0.00/449k [00:00<?, ?B/s]

mhr_Cyrl.jsonl:   0%|          | 0.00/555k [00:00<?, ?B/s]

mri_Latn.jsonl:   0%|          | 0.00/462k [00:00<?, ?B/s]

mya_Mymr.jsonl:   0%|          | 0.00/774k [00:00<?, ?B/s]

myv_Cyrl.jsonl:   0%|          | 0.00/563k [00:00<?, ?B/s]

nld_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

nob_Latn_radical.jsonl:   0%|          | 0.00/448k [00:00<?, ?B/s]

nob_Latn.jsonl:   0%|          | 0.00/441k [00:00<?, ?B/s]

nno_Latn.jsonl:   0%|          | 0.00/444k [00:00<?, ?B/s]

npi_Deva.jsonl:   0%|          | 0.00/647k [00:00<?, ?B/s]

nqo_Nkoo.jsonl:   0%|          | 0.00/613k [00:00<?, ?B/s]

oci_Latn_aran1260.jsonl:   0%|          | 0.00/464k [00:00<?, ?B/s]

nso_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

nya_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

oci_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

nus_Latn.jsonl:   0%|          | 0.00/483k [00:00<?, ?B/s]

ory_Orya.jsonl:   0%|          | 0.00/669k [00:00<?, ?B/s]

pag_Latn.jsonl:   0%|          | 0.00/438k [00:00<?, ?B/s]

pan_Guru.jsonl:   0%|          | 0.00/652k [00:00<?, ?B/s]

pbt_Arab.jsonl:   0%|          | 0.00/523k [00:00<?, ?B/s]

plt_Latn.jsonl:   0%|          | 0.00/473k [00:00<?, ?B/s]

pap_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

pes_Arab.jsonl:   0%|          | 0.00/531k [00:00<?, ?B/s]

prs_Arab.jsonl:   0%|          | 0.00/523k [00:00<?, ?B/s]

por_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

quy_Latn.jsonl:   0%|          | 0.00/450k [00:00<?, ?B/s]

pol_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

rus_Cyrl.jsonl:   0%|          | 0.00/568k [00:00<?, ?B/s]

run_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

ron_Latn.jsonl:   0%|          | 0.00/465k [00:00<?, ?B/s]

sag_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

san_Deva.jsonl:   0%|          | 0.00/655k [00:00<?, ?B/s]

sat_Olck.jsonl:   0%|          | 0.00/677k [00:00<?, ?B/s]

slv_Latn.jsonl:   0%|          | 0.00/442k [00:00<?, ?B/s]

scn_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

sin_Sinh.jsonl:   0%|          | 0.00/654k [00:00<?, ?B/s]

slk_Latn.jsonl:   0%|          | 0.00/451k [00:00<?, ?B/s]

smo_Latn.jsonl:   0%|          | 0.00/468k [00:00<?, ?B/s]

shn_Mymr.jsonl:   0%|          | 0.00/830k [00:00<?, ?B/s]

sot_Latn.jsonl:   0%|          | 0.00/467k [00:00<?, ?B/s]

sna_Latn.jsonl:   0%|          | 0.00/455k [00:00<?, ?B/s]

som_Latn.jsonl:   0%|          | 0.00/460k [00:00<?, ?B/s]

snd_Arab.jsonl:   0%|          | 0.00/520k [00:00<?, ?B/s]

srd_Latn.jsonl:   0%|          | 0.00/465k [00:00<?, ?B/s]

swh_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

spa_Latn.jsonl:   0%|          | 0.00/468k [00:00<?, ?B/s]

swe_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

tat_Cyrl.jsonl:   0%|          | 0.00/553k [00:00<?, ?B/s]

ssw_Latn.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

sun_Latn.jsonl:   0%|          | 0.00/446k [00:00<?, ?B/s]

srp_Cyrl.jsonl:   0%|          | 0.00/546k [00:00<?, ?B/s]

tgk_Cyrl.jsonl:   0%|          | 0.00/573k [00:00<?, ?B/s]

szl_Latn.jsonl:   0%|          | 0.00/453k [00:00<?, ?B/s]

taq_Tfng.jsonl:   0%|          | 0.00/611k [00:00<?, ?B/s]

tam_Taml.jsonl:   0%|          | 0.00/730k [00:00<?, ?B/s]

taq_Latn.jsonl:   0%|          | 0.00/441k [00:00<?, ?B/s]

tha_Thai.jsonl:   0%|          | 0.00/673k [00:00<?, ?B/s]

tir_Ethi.jsonl:   0%|          | 0.00/540k [00:00<?, ?B/s]

tel_Telu.jsonl:   0%|          | 0.00/662k [00:00<?, ?B/s]

tuk_Latn.jsonl:   0%|          | 0.00/463k [00:00<?, ?B/s]

tpi_Latn.jsonl:   0%|          | 0.00/477k [00:00<?, ?B/s]

tsn_Latn.jsonl:   0%|          | 0.00/471k [00:00<?, ?B/s]

tso_Latn.jsonl:   0%|          | 0.00/467k [00:00<?, ?B/s]

tyv_Cyrl.jsonl:   0%|          | 0.00/579k [00:00<?, ?B/s]

vie_Latn.jsonl:   0%|          | 0.00/491k [00:00<?, ?B/s]

tum_Latn.jsonl:   0%|          | 0.00/483k [00:00<?, ?B/s]

urd_Arab.jsonl:   0%|          | 0.00/540k [00:00<?, ?B/s]

vec_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

uig_Arab.jsonl:   0%|          | 0.00/569k [00:00<?, ?B/s]

ukr_Cyrl.jsonl:   0%|          | 0.00/554k [00:00<?, ?B/s]

twi_Latn_akua1239.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

twi_Latn_asan1239.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

umb_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

tur_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

uzn_Latn.jsonl:   0%|          | 0.00/457k [00:00<?, ?B/s]

vmw_Latn.jsonl:   0%|          | 0.00/474k [00:00<?, ?B/s]

ydd_Hebr.jsonl:   0%|          | 0.00/565k [00:00<?, ?B/s]

xho_Latn.jsonl:   0%|          | 0.00/447k [00:00<?, ?B/s]

war_Latn.jsonl:   0%|          | 0.00/473k [00:00<?, ?B/s]

wol_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

zsm_Latn.jsonl:   0%|          | 0.00/454k [00:00<?, ?B/s]

yor_Latn.jsonl:   0%|          | 0.00/477k [00:00<?, ?B/s]

zul_Latn.jsonl:   0%|          | 0.00/456k [00:00<?, ?B/s]

zgh_Tfng.jsonl:   0%|          | 0.00/611k [00:00<?, ?B/s]

yue_Hant.jsonl:   0%|          | 0.00/423k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

OLDI...

README.md:   0%|          | 0.00/17.3k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/46 [00:02<?, ?it/s]

Resolving data files:   0%|          | 0/46 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/46 [00:00<?, ?files/s]

bam_Latn.jsonl:   0%|          | 0.00/1.88M [00:00<?, ?B/s]

ben_Beng.jsonl:   0%|          | 0.00/3.18M [00:00<?, ?B/s]

ace_Arab.jsonl:   0%|          | 0.00/2.45M [00:00<?, ?B/s]

arz_Arab.jsonl:   0%|          | 0.00/2.30M [00:00<?, ?B/s]

ary_Arab.jsonl:   0%|          | 0.00/2.40M [00:00<?, ?B/s]

ace_Latn.jsonl:   0%|          | 0.00/1.89M [00:00<?, ?B/s]

ban_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/1.87M [00:00<?, ?B/s]

dzo_Tibt.jsonl:   0%|          | 0.00/3.91M [00:00<?, ?B/s]

crh_Latn.jsonl:   0%|          | 0.00/1.93M [00:00<?, ?B/s]

bjn_Latn.jsonl:   0%|          | 0.00/1.90M [00:00<?, ?B/s]

bug_Latn.jsonl:   0%|          | 0.00/1.93M [00:00<?, ?B/s]

bho_Deva.jsonl:   0%|          | 0.00/3.11M [00:00<?, ?B/s]

bjn_Arab.jsonl:   0%|          | 0.00/2.45M [00:00<?, ?B/s]

dik_Latn.jsonl:   0%|          | 0.00/2.00M [00:00<?, ?B/s]

fra_Latn.jsonl:   0%|          | 0.00/2.04M [00:00<?, ?B/s]

fuv_Latn.jsonl:   0%|          | 0.00/1.85M [00:00<?, ?B/s]

fur_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

kas_Arab.jsonl:   0%|          | 0.00/2.49M [00:00<?, ?B/s]

hne_Deva.jsonl:   0%|          | 0.00/3.12M [00:00<?, ?B/s]

ita_Latn.jsonl:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

kas_Deva.jsonl:   0%|          | 0.00/2.97M [00:00<?, ?B/s]

gug_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

lmo_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

knc_Latn.jsonl:   0%|          | 0.00/1.90M [00:00<?, ?B/s]

lim_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

mni_Beng.jsonl:   0%|          | 0.00/3.37M [00:00<?, ?B/s]

kir_Cyrl.jsonl:   0%|          | 0.00/2.69M [00:00<?, ?B/s]

ltg_Latn.jsonl:   0%|          | 0.00/1.88M [00:00<?, ?B/s]

lij_Latn.jsonl:   0%|          | 0.00/1.99M [00:00<?, ?B/s]

mag_Deva.jsonl:   0%|          | 0.00/3.14M [00:00<?, ?B/s]

knc_Arab.jsonl:   0%|          | 0.00/2.74M [00:00<?, ?B/s]

mri_Latn.jsonl:   0%|          | 0.00/1.95M [00:00<?, ?B/s]

nqo_Nkoo.jsonl:   0%|          | 0.00/2.92M [00:00<?, ?B/s]

nus_Latn.jsonl:   0%|          | 0.00/2.18M [00:00<?, ?B/s]

pbt_Arab.jsonl:   0%|          | 0.00/2.40M [00:00<?, ?B/s]

prs_Arab.jsonl:   0%|          | 0.00/2.37M [00:00<?, ?B/s]

scn_Latn.jsonl:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

shn_Mymr.jsonl:   0%|          | 0.00/4.06M [00:00<?, ?B/s]

srd_Latn.jsonl:   0%|          | 0.00/2.01M [00:00<?, ?B/s]

szl_Latn.jsonl:   0%|          | 0.00/1.93M [00:00<?, ?B/s]

spa_Latn.jsonl:   0%|          | 0.00/1.98M [00:00<?, ?B/s]

taq_Tfng.jsonl:   0%|          | 0.00/3.08M [00:00<?, ?B/s]

taq_Latn.jsonl:   0%|          | 0.00/1.86M [00:00<?, ?B/s]

zgh_Tfng.jsonl:   0%|          | 0.00/2.95M [00:00<?, ?B/s]

vec_Latn.jsonl:   0%|          | 0.00/1.93M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/284878 [00:00<?, ? examples/s]

Done.

In [ ]:
def get_language(language_names, corpora):
    final_dfs = {}

    for lang_name in language_names:
        codes = get_iso_codes(lang_name)
        if not codes:
            print(f" {lang_name} ISO code not found.")
            continue

        a2 = codes['alpha_2']
        a3 = codes['alpha_3']

        # Словарь для хранения всех найденных вариантов
        candidates = {}
        print(f"Collecting {lang_name} ({a2}/{a3})...")

        # FLORES+
        if 'flores' in corpora and a3:
            subset_source = loaded_corpora['flores'].filter(lambda x: x['iso_639_3'] == a3, keep_in_memory=True)
            subset_target = loaded_corpora['flores'].filter(lambda x: x['iso_639_3'] == 'eng', keep_in_memory=True)
            if len(subset_source) > 0:
                candidates["FLORES+"] = [{'source': s, 'target': t} for s, t in zip(subset_source['text'], subset_target['text'])]


        # OLDI
        if 'oldi' in corpora and a3:
            subset_source = loaded_corpora['oldi'].filter(lambda x: x['iso_639_3'] == a3, keep_in_memory=True)
            subset_target = loaded_corpora['oldi'].filter(lambda x: x['iso_639_3'] == 'eng', keep_in_memory=True)
            if len(subset_target) > 0:
                candidates["OLDI"] = [{'source': s, 'target': t} for s, t in zip(subset_source['text'], subset_target['text'])]


        # SMOL
        if a2:
            for prefix in ['smolsent', 'smoldoc', 'gatitos']:
                config_name = f"{prefix}__en_{a2}"
                try:
                    ds_dict = load_dataset("google/smol", config_name)
                    split = 'devtest' if 'devtest' in ds_dict else list(ds_dict.keys())[0]
                    ds = ds_dict[split]

                    en_col = next((c for c in ['sentence_eng', 'text_en', 'en', 'src'] if c in ds.column_names), None)
                    native_col = next((c for c in ['sentence_native', 'text_native', a2, 'trgs', 'trg'] if c in ds.column_names), None)

                    if en_col and native_col:
                        smol_p = []
                        for en_txt, nat_txt in zip(ds[en_col], ds[native_col]):
                            # Убираем короткие строки
                            if len(str(en_txt).split()) < 3:
                                continue

                            # native -> Source, английский -> Target
                            smol_p.append({'source': nat_txt, 'target': en_txt})

                        if smol_p: candidates[f"SMOL_{prefix}"] = smol_p
                except:
                    continue

        # Tatoeba
        target_code = a3 if a3 else a2
        if target_code:
            tgt_lang = target_code.lower()
            lang_pair_config = f"{tgt_lang}-eng"

            tatoeba_configs = [
                ("Tatoeba_Test", "Helsinki-NLP/tatoeba_mt"),
                ("Tatoeba_Train", "Helsinki-NLP/tatoeba_mt_train")
            ]

            for split_name, ds_path in tatoeba_configs:
                try:
                    ds = load_dataset(
                        ds_path,
                        name=lang_pair_config,
                        split="test")

                    tatoeba_p = []
                    for ex in ds:
                        s_str = ex.get('source_text', ex.get('sourceString', ''))
                        t_str = ex.get('target_text', ex.get('targetString', ''))
                        s_lang = str(ex.get('source_lang', ex.get('sourceLang', ''))).lower()
                        if len(str(t_str).split()) > 1:
                          if tgt_lang in s_lang:
                              tatoeba_p.append({'source': s_str, 'target': t_str})
                          else:
                              tatoeba_p.append({'source': t_str, 'target': s_str})

                    if tatoeba_p:
                        candidates[split_name] = tatoeba_p

                except Exception as e:
                    # print(f"Ошибка при обработке {split_name}: {e}")
                    pass

        if candidates:
            best_key = max(candidates, key=lambda k: len(candidates[k]))
            best_pairs = candidates[best_key]

            df = pd.DataFrame(best_pairs)
            df = df.dropna(subset=['source', 'target']).reset_index(drop=True)
            for col in ['source', 'target']:
                df[col] = df[col].astype(str).str.replace('[', '', regex=False).str.replace(']', '', regex=False)
            df['source_dataset'] = best_key
            df['language'] = lang_name
            final_dfs[lang_name] = df
            print(f"{lang_name} -> {best_key} (размер: {len(df)})")
        else:
            print(f"{lang_name} ({a2}/{a3}) не найден.")

    return final_dfs

In [ ]:
sentences = get_language(['Chamorro', 'Igbo', 'Georgian', 'Korean', 'Basque'], loaded_corpora)

Collecting Chamorro (ch/cha)...

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

README.md:   0%|          | 0.00/113k [00:00<?, ?B/s]

en_ch.jsonl:   0%|          | 0.00/359k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

README.md:   0%|          | 0.00/12.1k [00:00<?, ?B/s]

tatoeba_mt.py:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/796k [00:00<?, ?B/s]

cha-eng/train-00000-of-00001.parquet:   0%|          | 0.00/1.75M [00:00<?, ?B/s]

cha-eng/test-00000-of-00001.parquet:   0%|          | 0.00/8.77k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/12958 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/227 [00:00<?, ? examples/s]

Chamorro -> Tatoeba_Train (размер: 219)
Collecting Igbo (ig/ibo)...

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

en_ig.jsonl:   0%|          | 0.00/260k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

en_ig.jsonl:   0%|          | 0.00/1.46M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Igbo -> FLORES+ (размер: 1012)
Collecting Georgian (ka/kat)...

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Georgian -> FLORES+ (размер: 1012)
Collecting Korean (ko/kor)...

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

en_ko.jsonl:   0%|          | 0.00/276k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

en_ko.jsonl:   0%|          | 0.00/901k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Korean -> FLORES+ (размер: 1012)
Collecting Basque (eu/eus)...

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/222640 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Filter:   0%|          | 0/284878 [00:00<?, ? examples/s]

Basque -> FLORES+ (размер: 1012)

In [ ]:
sentences['Chamorro']

,source,target,source_dataset,language
0,Ågang i polisia!,Call the police!,Tatoeba_Train,Chamorro
1,Amerikanu gue'.,He is American.,Tatoeba_Train,Chamorro
2,Amerikanu gue'.,She is American.,Tatoeba_Train,Chamorro
3,Amerikanu hamyo.,You are American.,Tatoeba_Train,Chamorro
4,Amerikanu hao.,You are American.,Tatoeba_Train,Chamorro
...,...,...,...,...
214,Umatungo' i dos palao'an.,The two women know each other.,Tatoeba_Train,Chamorro
215,Umo'mak hamyo gi tåsi.,You swam in the ocean.,Tatoeba_Train,Chamorro
216,Umo'mak hao gi tåsi.,You swam in the ocean.,Tatoeba_Train,Chamorro
217,"Unu, dos, tres, kuåttru', singku', sais, siett...","One, two, three, four, five, six, seven, eight...",Tatoeba_Train,Chamorro
218,Ya'-na si Tom malågu.,Tom likes to run.,Tatoeba_Train,Chamorro

In [ ]:
sentences['Igbo']['target'][0]

'"We now have 4-month-old mice that are non-diabetic that used to be diabetic," he added.'

## TYP data

In [ ]:
para_df = pd.read_csv('/content/parameters.csv')

In [ ]:
para_df.head()

,ID,Name,Description,ColumnSpec,Patrons,Grambank_ID_desc,Boundness,Flexivity,Gender_or_Noun_Class,Locus_of_Marking,Word_Order,Informativity
0,GB020,Are there definite or specific articles?,## Are there definite or specific articles?\r\...,NaN,JLA JC,GB020 ARTDef,NaN,NaN,NaN,NaN,NaN,definitearticles
1,GB021,Do indefinite nominals commonly have indefinit...,## Do indefinite/non-specific nominals commonl...,NaN,JLA JC,GB021 ARTIndef,NaN,NaN,NaN,NaN,NaN,indef
2,GB022,Are there prenominal articles?,## Are there prenominal articles?\r\n\r\n## Su...,NaN,JLA JC,GB022 ARTPre,NaN,NaN,NaN,NaN,0.0,NaN
3,GB023,Are there postnominal articles?,## Are there postnominal articles?\r\n\r\n## S...,NaN,JLA JC,GB023 ARTPost,NaN,NaN,NaN,NaN,1.0,NaN
4,GB024,What is the order of numeral and noun in the NP?,## What is the order of numeral and noun in th...,NaN,HJH,GB024 NUMOrder,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
para_df['Description'] = para_df['Description'].str.split('## Examples').str[0]

In [ ]:
print(para_df['Description'][1])

## Do indefinite/non-specific nominals commonly have indefinite/non-specific articles?

## Summary
For this feature, we need explicit support that indefinite/non-specific NPs commonly occur with an indefinite/non-specific article. Three or more examples of indefinite/non-specific nominals occurring with an indefinite/non-specific article is sufficient to code 1.

An indefinite article is a marker that accompanies the indefinite noun and expresses notions such as non-specificity and indefiniteness. Sometimes these notions of non-specificity and indefiniteness are summed up in the term ‘identifiability’. A language does not necessarily have both a non-specific/indefinite and a specific/definite marker. These markers often stem from very different sources (numerals and demonstratives) and need not be similar in formal expression or position.

The formal expression is irrelevant; articles can be free, bound, or marked by suprasegmental markers such as tone. Articles are different from demonstratives in that demonstratives occur in a paradigm of markers that have a clear spatial deictic function. As demonstratives can grammaticalize into definite or specific articles, they form a natural continuum, making it hard to define discrete categories. Articles are more grammaticalized, i.e. are often [obligatory](https://github.com/grambank/grambank/wiki/Obligatoriness) in certain contexts that require definite or specific reference. Definite or specific articles can also grammaticalize from pronouns meaning ‘a certain’. As articles necessarily accompany nouns, it is in these cases that it is necessary to investigate whether the marker can occur independently or not; if it can it is most likely a pronoun and not an article. Articles can be homophonous with pronouns and demonstratives, and also with classifiers.

## Procedure
1. Code 1 if indefinite NPs commonly occur with an indefinite/non-specific article. Three or more examples are sufficient.
2. Code 1 if there is evidence (three or more examples) of a demonstrative or numeral for 1 that has grammaticalized into an indefinite article. Look for explicit analysis from the author that they are indefinite articles or look at the environments in which they occur, for example, whether they occur in different positions depending on whether they are functioning as an indefinite article or not.
3. Code 0 if there are no indefinite articles.
4. Code 0 if there are less than three examples of indefinite/non-specific articles occurring with indefinite NPs and note this in the comments.
5. Code ? if it is unclear whether there are indefinite articles due to limited analysis from the author or because there are not enough examples.

In [ ]:
!unzip '/content/values.zip'

Archive:  /content/values.zip
  inflating: values.csv

In [ ]:
val_df = pd.read_csv('/content/values.csv')

In [ ]:
val_df.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
0,GB020-abad1241,abad1241,GB020,?,NaN,Author states there is a possible example of a...,s_OaPaul_Gabadi[17],Oa & Paul 2013:17,JLA
1,GB021-abad1241,abad1241,GB021,?,NaN,Author states there is a possible example of a...,s_OaPaul_Gabadi[17],Oa & Paul 2013:17,JLA
2,GB022-abad1241,abad1241,GB022,?,NaN,Author states there is a possible example of a...,s_OaPaul_Gabadi[17],Oa & Paul 2013:17,JLA
3,GB023-abad1241,abad1241,GB023,?,NaN,Author states there is a possible example of a...,s_OaPaul_Gabadi[17],Oa & Paul 2013:17,JLA
4,GB024-abad1241,abad1241,GB024,2,GB024-2,NaN,s_OaPaul_Gabadi[15],Oa & Paul 2013:15,JLA

In [ ]:
subset_ibo = val_df[val_df['Language_ID'] == 'nucl1417']
subset_ibo.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
284818,GB020-nucl1417,nucl1417,GB020,0,GB020-0,NaN,g_Emenanjo_Igbo_2015[279-300],Emenanjo (2015:279-300),JLA
284819,GB021-nucl1417,nucl1417,GB021,0,GB021-0,NaN,g_Emenanjo_Igbo_2015[279-300],Emenanjo (2015:279-300),JLA
284820,GB022-nucl1417,nucl1417,GB022,0,GB022-0,NaN,g_Emenanjo_Igbo_2015[279-300],Emenanjo (2015:279-300),JLA
284821,GB023-nucl1417,nucl1417,GB023,0,GB023-0,NaN,g_Emenanjo_Igbo_2015[279-300],Emenanjo (2015:279-300),JLA
284822,GB024-nucl1417,nucl1417,GB024,2,GB024-2,NaN,g_Emenanjo_Igbo_2015[279-282],Emenanjo (2015:279-282),JLA

In [ ]:
subset_ibo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194 entries, 284818 to 285011
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              194 non-null    object
 1   Language_ID     194 non-null    object
 2   Parameter_ID    194 non-null    object
 3   Value           194 non-null    object
 4   Code_ID         188 non-null    object
 5   Comment         0 non-null      object
 6   Source          194 non-null    object
 7   Source_comment  194 non-null    object
 8   Coders          194 non-null    object
dtypes: object(9)
memory usage: 19.2+ KB

In [ ]:
subset_basque = val_df[val_df['Language_ID'] == 'basq1248']
subset_basque.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
38204,GB020-basq1248,basq1248,GB020,1,GB020-1,NaN,g_HualdeUrbana_Basque[119],Hualde (2003:119),JG;JLA;RHA
38205,GB021-basq1248,basq1248,GB021,1,GB021-1,NaN,g_HualdeUrbana_Basque[122],Hualde (2003:122),JG;JLA;RHA
38206,GB022-basq1248,basq1248,GB022,0,GB022-0,NaN,"g_HualdeUrbana_Basque[119, 122]","Hualde (2003:119, 122)",JG;JLA;RHA
38207,GB023-basq1248,basq1248,GB023,1,GB023-1,NaN,"g_HualdeUrbana_Basque[119, 122]","Hualde (2003:119, 122)",JG;JLA;RHA
38208,GB024-basq1248,basq1248,GB024,1,GB024-1,NaN,"g_HualdeUrbana_Basque[113, 118]","Hualde (2003:113, 118)",JG;JLA;RHA

In [ ]:
subset_geor = val_df[val_df['Language_ID'] == 'nucl1302']
subset_geor.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
283897,GB020-nucl1302,nucl1302,GB020,0,GB020-0,NaN,g_Hewitt_Georgian[62],Hewitt 1995:62,JSA;TWE
283898,GB021-nucl1302,nucl1302,GB021,0,GB021-0,NaN,g_Hewitt_Georgian[62],Hewitt 1995:62,JSA;TWE
283899,GB022-nucl1302,nucl1302,GB022,0,GB022-0,NaN,g_Hewitt_Georgian[62],Hewitt 1995:62,JSA;TWE
283900,GB023-nucl1302,nucl1302,GB023,0,GB023-0,NaN,g_Hewitt_Georgian[62],Hewitt 1995:62,JSA;TWE
283901,GB024-nucl1302,nucl1302,GB024,1,GB024-1,NaN,g_Hewitt_Georgian[54-56],Hewitt 1995:54-56,JSA;TWE

In [ ]:
subset_cha = val_df[val_df['Language_ID'] == 'cham1312']
subset_cha.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
73226,GB020-cham1312,cham1312,GB020,1,GB020-1,NaN,typ_Cooreman_Chamorro_1987[26],Cooreman 1987:26,NP
73227,GB021-cham1312,cham1312,GB021,0,GB021-0,Chung says that indefinite articles are common...,typ_Chung_Chamorro_Lexical[21],Chung 2012:21,NP
73228,GB022-cham1312,cham1312,GB022,1,GB022-1,NaN,typ_Cooreman_Chamorro_1987[26],Cooreman 1987:26,NP
73229,GB023-cham1312,cham1312,GB023,0,GB023-0,"Not mentioned, judged absent",g_Topping_Chamorro;typ_Chung_Chamorro_Agreement,Topping 1973; Chung 1998,NP
73230,GB024-cham1312,cham1312,GB024,1,GB024-1,NaN,typ_Chung_Chamorro_Agreement[47-48],Chung 1998:47-48,NP

In [ ]:
subset_kor = val_df[val_df['Language_ID'] == 'kore1280']
subset_kor.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
181676,GB020-kore1280,kore1280,GB020,0,GB020-0,NaN,g_Sohn_Korean[276-278],Sohn (1994:276-278),MM;NH
181677,GB021-kore1280,kore1280,GB021,0,GB021-0,Nominals that are unmarked for definiteness (b...,"g_Sohn_Korean[113-114, 224, 276-280];g_Sohn_Ko...","Sohn (1994: 113-114, 224, 276-280); Sohn (1999...",JP;MM;NH
181678,GB022-kore1280,kore1280,GB022,0,GB022-0,NaN,g_Sohn_Korean_1999[265],Sohn (1999:265),MM;NH
181679,GB023-kore1280,kore1280,GB023,0,GB023-0,NaN,"g_Sohn_Korean[113-114, 224, 276-280];g_Sohn_Ko...","Sohn (1994: 113-114, 224, 276-280); Sohn (1999...",JP;MM;NH
181680,GB024-kore1280,kore1280,GB024,2,GB024-2,NaN,"g_Sohn_Korean_1999[265, 296]","Sohn (1999:265, 296)",MM;NH

In [ ]:
subset_eng = val_df[val_df['Language_ID'] == 'stan1293']
subset_eng.head()

,ID,Language_ID,Parameter_ID,Value,Code_ID,Comment,Source,Source_comment,Coders
357551,GB020-stan1293,stan1293,GB020,1,GB020-1,The definite article is 'the.',g_HuddlestonPullum_English[368],Huddleston & Pullum (2002:368),IC;JG;JLA
357552,GB021-stan1293,stan1293,GB021,1,GB021-1,The indefinite article is 'a' or at times 'an',g_HuddlestonPullum_English[371],Huddleston & Pullum (2002:371),IC;JG;JLA
357553,GB022-stan1293,stan1293,GB022,1,GB022-1,NaN,g_HuddlestonPullum_English[368],Huddleston & Pullum (2002:368),IC;JG;JLA
357554,GB023-stan1293,stan1293,GB023,0,GB023-0,NaN,g_HuddlestonPullum_English[368-371],Huddleston & Pullum (2002:368-371),IC;JG;JLA
357555,GB024-stan1293,stan1293,GB024,1,GB024-1,NaN,"g_HuddlestonPullum_English[363, 385-387]","Huddleston & Pullum (2002:363, 385-387)",IC;JG;JLA

In [ ]:
subset_eng.info()

<class 'pandas.core.frame.DataFrame'>
Index: 195 entries, 357551 to 357745
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              195 non-null    object
 1   Language_ID     195 non-null    object
 2   Parameter_ID    195 non-null    object
 3   Value           195 non-null    object
 4   Code_ID         195 non-null    object
 5   Comment         56 non-null     object
 6   Source          195 non-null    object
 7   Source_comment  195 non-null    object
 8   Coders          195 non-null    object
dtypes: object(9)
memory usage: 15.2+ KB

In [ ]:
master_df = subset_ibo[['Parameter_ID', 'Value']].rename(columns={'Value': 'Igbo'})

In [ ]:
master_df = master_df.merge(
    subset_basque[['Parameter_ID', 'Value']].rename(columns={'Value': 'Basque'}),
    on='Parameter_ID',
    how='left'
)
master_df = master_df.merge(
    subset_geor[['Parameter_ID', 'Value']].rename(columns={'Value': 'Georgian'}),
    on='Parameter_ID',
    how='left'
)
master_df = master_df.merge(
    subset_cha[['Parameter_ID', 'Value']].rename(columns={'Value': 'Chamorro'}),
    on='Parameter_ID',
    how='left'
)
master_df = master_df.merge(
    subset_kor[['Parameter_ID', 'Value']].rename(columns={'Value': 'Korean'}),
    on='Parameter_ID',
    how='left'
)
master_df = master_df.merge(
    subset_eng[['Parameter_ID', 'Value']].rename(columns={'Value': 'English'}),
    on='Parameter_ID',
    how='left'
)

In [ ]:
master_df = master_df.merge(
    para_df[['ID', 'Name', 'Description']].rename(columns={'ID': 'Parameter_ID'}),
    on='Parameter_ID',
    how='left'
)

In [ ]:
master_df.head()

,Parameter_ID,Igbo,Basque,Georgian,Chamorro,Korean,English,Name,Description
0,GB020,0,1,0,1,0,1,Are there definite or specific articles?,## Are there definite or specific articles?\r\...
1,GB021,0,1,0,0,0,1,Do indefinite nominals commonly have indefinit...,## Do indefinite/non-specific nominals commonl...
2,GB022,0,0,0,1,0,1,Are there prenominal articles?,## Are there prenominal articles?\r\n\r\n## Su...
3,GB023,0,1,0,0,0,0,Are there postnominal articles?,## Are there postnominal articles?\r\n\r\n## S...
4,GB024,2,1,1,1,2,1,What is the order of numeral and noun in the NP?,## What is the order of numeral and noun in th...

In [ ]:
hyperlink_pattern = r'\[([^\]]+)\]\([^\)]+\)'
master_df['Description'] = master_df['Description'].str.replace(hyperlink_pattern, r'\1', regex=True)

In [ ]:
def create_typ_prompt(df):
    all_columns = df.columns.tolist()
    start_idx = all_columns.index('Parameter_ID') + 1
    end_idx = all_columns.index('Name')
    languages = all_columns[start_idx:end_idx]

    all_prompts = {}
    for lang in languages:
        if lang == 'English':
            continue

        lang_prompts = []
        for _, row in df.iterrows():
            prompt = f"""
Feature ID: {row['Parameter_ID']}: {row['Name']}
{lang} Value: Code {row[lang]}

English Value: Code {row['English']}

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
{row['Description']}
This is the end of the summary for feature {row['Parameter_ID']}: "{row['Name']}".
"""
            lang_prompts.append(prompt)

        all_prompts[lang] = lang_prompts

    return all_prompts, languages
prompts, languages = create_typ_prompt(master_df)

In [ ]:
print(prompts['Korean'][0])

## Prompts

In [ ]:
def get_glossed_para(source_list, target_list, gloss_list, lang_name):
    if not source_list:
        return ""

    # Сначала собираем только те примеры, где глосс реально существует
    glossed_examples = []
    simple_examples = []

    for src, tgt, gloss in zip(source_list, target_list, gloss_list):
        has_gloss = (
            isinstance(gloss, str) and
            gloss.strip() != "" and
            gloss.lower() != 'nan'
        )

        if has_gloss:
            line = (f"{lang_name}: {src}\n"
                    f"Morphological gloss: {gloss}\n"
                    f"English translation: {tgt}")
            glossed_examples.append(line)
        else:
            line = (f"{lang_name}: {src}\n"
                    f"English translation: {tgt}")
            simple_examples.append(line)

    # Если нашли хотя бы один пример с глоссом — берем ТОЛЬКО их
    if glossed_examples:
        block_header = f"To help with the translation, here are some example {lang_name}-English parallel sentences with morphological glosses:\n"
        final_examples = glossed_examples
    else:
        # Если глоссов нет вообще — берем простые примеры
        block_header = f"To help with the translation, here are some example {lang_name}-English parallel sentences:\n"
        final_examples = simple_examples

    return block_header + "\n\n".join(final_examples)

In [ ]:
def generate_zeroshot_prompt(lang_name, sentence):
    instruction = f"""Translate the following sentence from {lang_name} to English: {sentence}

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that  you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

Now write the translation:
{lang_name}: {sentence}
English:"""
    return instruction

In [ ]:
def generate_typology_prompt(lang_name, sentence, typological_info):
    instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the following sentence from {lang_name} to English: {sentence}

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

To help with the translation, here is typological information for both languages:

{typological_info}

Now write the translation:
{lang_name}: {sentence}
English:

"""
    return instruction

In [ ]:
def get_parallel_examples_block(source_list, target_list, lang_name):
    if not source_list:
      return ""

    block_header = f"To help with the translation, here are some example {lang_name}-English parallel sentences and words:\n"

    example_lines = []
    for src, tgt in zip(source_list, target_list):
        line = f"{lang_name}: {src}\nEnglish translation: {tgt}"
        example_lines.append(line)

    return block_header + "\n".join(example_lines)

In [ ]:
def generate_para_prompt(lang_name, sentence, parallel_examples):
    instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the following sentence from {lang_name} to English: {sentence}

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

{parallel_examples}

Now write the translation:
{lang_name}: {sentence}
English:

"""
    return instruction

In [ ]:
def generate_paratyp_prompt(lang_name, sentence, typological_info, parallel_examples):
    instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the following sentence from {lang_name} to English: {sentence}

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

{parallel_examples}

To help with the translation, here is typological information for both languages:

{typological_info}
Now write the translation:
{lang_name}: {sentence}
English:

"""
    return instruction

In [ ]:
def generate_glossed_prompt(lang_name, sentence, glossed_data):
    instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the following sentence from {lang_name} to English: {sentence}

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

{glossed_data}

Now write the translation:
{lang_name}: {sentence}
English:

"""
    return instruction

In [ ]:
# def generate_full_prompt(lang_name, sentence, typological_info, glossed_data):
#     instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the following sentence from {lang_name} to English: {sentence}

# Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
# Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
# It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

# {glossed_data}

# To help with the translation, here is typological information for both languages:

# {typological_info}

# Now write the translation:
# {lang_name}: {sentence}
# English:

# """
#     return instruction

In [ ]:
def generate_full_prompt(lang_name, sentence, typological_info, glossed_data):
    instruction = f"""{lang_name} is a language that exhibits specific typological characteristics. Translate the sentence from {lang_name} to English using available data.

If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak {lang_name}. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

{glossed_data}

To help with the translation, here is typological information for both languages:

{typological_info}

Now write the translation:
{lang_name}: {sentence}
English:

"""
    return instruction

In [ ]:
final_prompts_typ = {}

separator = "\n___\n"

for lang, prompts_list in prompts.items():
    current_intro = f"""The following typological features describe the grammatical features of {lang} and English including word order, verbal tense, nominal case, and other language universals. Each feature is assigned a value that indicates the extent to which the language tends to exhibit that feature.
"""
    current_outro = f"—\nThis is the end of the typological feature summary for {lang} and English."

    body = separator.join(prompts_list)

    final_combined_prompt = f"{current_intro}\n{body}\n\n{current_outro}"

    final_prompts_typ[lang] = final_combined_prompt

print(final_prompts_typ['Chamorro'][:1000])

The following typological features describe the grammatical features of Chamorro and English including word order, verbal tense, nominal case, and other language universals. Each feature is assigned a value that indicates the extent to which the language tends to exhibit that feature.


Feature ID: GB020: Are there definite or specific articles?
Chamorro Value: Code 1

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Are there definite or specific articles?

## Summary
An article is a marker that accompanies the noun and expresses notions such as (non-)specificity and (in)definiteness. Sometimes these notions of specificity and definiteness are summed up in the term 'identifiability'. The formal expression is irrelevant; articles can be free, bound, or marked by suprasegmental markers such as tone.
Art

# Experiment - Grammar Data

In [ ]:
%%capture
!pip install rapidfuzz

In [ ]:
igbo_df = pd.read_csv('/content/emenanjo2015_parallel_extracted.csv')
georgian_df = pd.read_csv('/content/hewitt1995georgian_parallel_extracted.csv')
chamorro_df = pd.read_csv('/content/chung2020_parallel_extracted.csv')
basque_df = pd.read_csv('/content/hualde2003_parallel_extracted.csv')
korean_df = pd.read_csv('/content/martin1992_parallel_extracted.csv')

In [ ]:
igbo_df.head()

,type,example_id,object_language,gloss,translation,source_ref,page_hint,context_before,context_after
0,inline,NaN,oke,NaN,male,NaN,=== PAGE 59 ===,In noun class languages as those found in Afri...,"The use of oke ‘male’, nwunyè ‘female’ to mark..."
1,inline,NaN,nwunyè,NaN,female,NaN,=== PAGE 59 ===,In noun class languages as those found in Afri...,"The use of oke ‘male’, nwunyè ‘female’ to mark..."
2,inline,NaN,uri/akwukwo mmuo,NaN,different indigenous writing systems,NaN,=== PAGE 69 ===,Different indigenous writing systems called ur...,But the orthography first used in a pan-Igbo w...
3,inline,NaN,Òtu Sùbakwanù Ìgbò,NaN,Society for Promoting Igbo Language and Cultur...,NaN,=== PAGE 72 ===,the emergence of learned societies like the Ig...,All of the above are designed to complement th...
4,inline,NaN,bùre-è-kì,NaN,break,NaN,=== PAGE 85 ===,In the unvarnished speech of the Type A rustic...,In view of the restrictions observed above abo...

In [ ]:
kor_df= korean_df['gloss'].dropna()
kor_df.head() # нет глосс

Series([], Name: gloss, dtype: float64)

In [ ]:
import pandas as pd
from rapidfuzz import fuzz

def deduplicate_parallel_df(df, text_col='object_language', trans_col='translation', threshold=90):

    df = df.drop_duplicates(subset=[text_col, trans_col]).copy()

    unique_indices = []
    seen_strings = []

    for idx, row in df.iterrows():
        current_text = str(row[text_col])

        is_duplicate = False
        for seen in seen_strings:
            if fuzz.ratio(current_text, seen) > threshold:
                is_duplicate = True
                break

        if not is_duplicate:
            unique_indices.append(idx)
            seen_strings.append(current_text)

    return df.loc[unique_indices]

In [ ]:
import unicodedata

def full_text_clean(text):
    if not isinstance(text, str):
        return text
    fixed_chars = []
    for char in text:
        cp = ord(char)
        if 0xf000 <= cp <= 0xf0ff:
            fixed_chars.append(chr(cp - 0xf000))
        else:
            fixed_chars.append(char)
    text = "".join(fixed_chars)

    text = text.replace('\xa0', ' ')

    text = unicodedata.normalize('NFC', text)

    return " ".join(text.split()).strip()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
def process_language_data(df, lang_name, typology_dict=None):
    # 1. Очистка
    cols_to_fix = ['object_language', 'translation']
    for col in cols_to_fix:
      if col in df.columns:
          print(f"Чистим колонку: {col}...")
          df[col] = df[col].apply(full_text_clean)
    df = deduplicate_parallel_df(df, threshold=90)

    # 2. Сплит
    train, test = train_test_split(
            df,
            test_size=0.2,
            random_state=42,
            shuffle=True
        )

    is_single_word = test['object_language'].astype(str).str.strip().str.contains(r'^\S+$', na=False)

    words_to_move = test[is_single_word]

    test = test[~is_single_word].copy()

    result = {
        'train': {
            'source': train['object_language'].tolist(),
            'target': train['translation'].tolist(),
            'glosses': train['gloss'].tolist()
        },
        'test': {
            'source': test['object_language'].tolist(),
            'target': test['translation'].tolist()
        },
        'typology': typology_dict.get(lang_name, "No info") if typology_dict else "No info"
    }

    return result

In [ ]:
multilingual_corpus = {}

multilingual_corpus['Igbo'] = process_language_data(igbo_df, 'Igbo', final_prompts_typ)
multilingual_corpus['Basque'] = process_language_data(basque_df, 'Basque', final_prompts_typ)

Чистим колонку: object_language...
Чистим колонку: translation...
Чистим колонку: object_language...
Чистим колонку: translation...

In [ ]:
multilingual_corpus['Georgian'] = process_language_data(georgian_df, 'Georgian', final_prompts_typ)
multilingual_corpus['Korean'] = process_language_data(korean_df, 'Korean', final_prompts_typ)
multilingual_corpus['Chamorro'] = process_language_data(chamorro_df, 'Chamorro', final_prompts_typ)

Чистим колонку: object_language...
Чистим колонку: translation...
Чистим колонку: object_language...
Чистим колонку: translation...
Чистим колонку: object_language...
Чистим колонку: translation...

In [ ]:
def count_tokens(text, model="gpt-5.2"):
    try:
        enc = tiktoken.encoding_for_model(model)
    except:
        enc = tiktoken.get_encoding("o200k_base")
    return len(enc.encode(str(text)))

stats_list = []

for lang in multilingual_corpus.keys():
    train_texts = [str(s) for s in multilingual_corpus[lang]['train']['source']]
    test_texts = [str(s) for s in multilingual_corpus[lang]['test']['source']]

    train_tokens = sum(count_tokens(t) for t in train_texts)

    test_tokens = sum(count_tokens(t) for t in test_texts)

    stats_list.append({
        'Language': lang,
        'Train_Examples': len(train_texts),
        'Train_Tokens': train_tokens,
        'Test_Examples': len(test_texts),
        'Test_Tokens': test_tokens,
        'Total_Tokens': train_tokens + test_tokens
    })

df_stats = pd.DataFrame(stats_list)

display(df_stats)
df_stats.to_csv('df_stats.csv', index=False)

,Language,Train_Examples,Train_Tokens,Test_Examples,Test_Tokens,Total_Tokens
0,Igbo,820,7528,139,1537,9065
1,Basque,2304,31076,554,7592,38668
2,Georgian,827,16526,157,4002,20528
3,Korean,401,5419,87,1194,6613
4,Chamorro,1844,30053,428,7268,37321

In [ ]:
import json

def prepare_batch(lang_name, prompts_list, truncate=False, model_name="gpt-5.2", limit=100, reasoning=False):

    filename = f"batch_{lang_name}.jsonl"
    target_prompts = prompts_list[:limit]

    with open(filename, 'w', encoding='utf-8') as f:
        for i, prompt in enumerate(target_prompts):

            if truncate:
                prompt = truncate_to_limit(prompt, model=model_name)

            if reasoning == True:
                entry = {

                    "custom_id": f"request-{lang_name}-{i}",
                    "method": "POST",
                    "url": "/v1/responses",
                    "body": {
                        "model": f"{model_name}",
                        "input": [
                            {
                                "role": "system",
                                "content":[{"type": "input_text", "text": "You are a professional translator and only output the result."}]
                            },
                            {"role": "user", "content": [{"type": "input_text", "text":prompt}]}
                        ],
                        "max_output_tokens": 10000,
                        "reasoning": {
                                      "effort": "high"
                                  }
                        # ,
                        # "temperature": 0.3
                    }
                }

            if reasoning == False:

                entry = {
                "custom_id": f"request-{lang_name}-{i}",
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": f"{model_name}",
                    "messages": [
                        {
                            "role": "system",
                            "content": "You are a professional translator and only output the result."
                        },
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": 0.3
                }
            }
            json_line = json.dumps(entry, ensure_ascii=False)
            f.write(json_line + '\n')

    print(f"{filename} - ({len(target_prompts)}).")

In [ ]:
def check_batch_statuses(batch_jobs_dict):
    print(f"{'Язык':<15} | {'Статус':<12} | {'Завершено':<18} | {'ID задания'}")
    print("-" * 70)

    for lang, b_id in batch_jobs_dict.items():
        try:
            job = client.batches.retrieve(b_id)
            counts = job.request_counts
            progress = f"{counts.completed}/{counts.total}" if counts else "N/A"

            print(f"{lang:<15} | {job.status:<12} | {progress:<18} | {b_id}")

            if job.status == "failed" and job.errors:
                for error in job.errors.data:
                    print(f"   └─ Ошибка: {error.message}")

        except Exception as e:
            print(f"{lang:<15} | ОШИБКА: {e}")

In [ ]:
def get_language_results(lang_name, batch_job_id, multilingual_corpus, benchmark=None):
    # 1. Получаем статус и данные из API
    job = client.batches.retrieve(batch_job_id)

    if job.status != "completed":
        print(f" Задание для {lang_name} еще не готово. Статус: {job.status}")
        return None

    file_response = client.files.content(job.output_file_id)

    # 2. Ищем текст
    if benchmark is not None:
        if lang_name in benchmark:
            source_sentences = benchmark[lang_name]['source']
            reference_sentences = benchmark[lang_name]['target']
        else:
            print(f"Ошибка: {lang_name} не найден в benchmark")
            return None
    else:
        source_sentences = multilingual_corpus[lang_name]['test']['source']
        reference_sentences = multilingual_corpus[lang_name]['test']['target']

    results_list = []

    # 3. Парсим результаты
    for line in file_response.text.splitlines():
        res = json.loads(line)

        parts = res['custom_id'].split('-')
        idx = int(parts[-1])

        message = res['response']['body']['choices'][0]['message']
        full_text = message.get('content', "").strip()

        prediction = full_text.split('\n')[0].strip()

        # Сопоставляем по индексу
        source = source_sentences[idx]
        reference = reference_sentences[idx]

        # Считаем базовую метрику
        score = chrf.compute(predictions=[prediction], references=[[reference]])['score']

        results_list.append({
            "Lang": lang_name,
            "Index": idx,
            "Source": source,
            "Reference": reference,
            "LLM_Translation": prediction,
            "ChrF": round(score, 2),
            "Status": job.status
        })

    df_res = pd.DataFrame(results_list)
    if not df_res.empty:
        df_res = df_res.sort_values("Index").reset_index(drop=True)

    return df_res

In [ ]:
def generate_multilingual_prompts(multilingual_corpus, benchmark=None, train_limit=None, mode='zeroshot', cache_typ=None):
    all_translation_prompts = {}

    cache_lookup = {}
    if cache_typ is not None:
        cache_lookup = cache_typ.set_index(['language', 'sentence'])['typology_context'].to_dict()

    for lang_name, data in multilingual_corpus.items():
        # 1. Извлекаем данные трейна
        source_train = data['train']['source']
        target_train = data['train']['target']
        gloss_train = data['train'].get('glosses', [])

        # 2. Срезаем обучающие данные по лимиту
        if train_limit is not None:
            source_train = source_train[:train_limit]
            target_train = target_train[:train_limit]
            if gloss_train:
                gloss_train = gloss_train[:train_limit]

        # 3. Генерируем блок примеров
        if not gloss_train:
            gloss_train = [None] * len(source_train)

        glossed_para_data = get_glossed_para(
            source_train,
            target_train,
            gloss_train,
            lang_name
        )
        para_data = get_parallel_examples_block(
            source_train,
            target_train,
            lang_name
        )

        # 4. Генерируем промпты для тестовой выборки
        lang_prompts = []

        if benchmark is not None:
            # Eсли текущего языка нет в датасете:
            if lang_name in benchmark:
                test_sources = benchmark[lang_name]['source']
            else:
                test_sources = []
        else:
            test_sources = data.get('test', {}).get('source', [])

        for test_sent in test_sources:
            if cache_typ is not None and mode in ['typ', 'paratyp', 'full']:
                current_typology = cache_lookup.get((lang_name, test_sent))
                if current_typology is None:
                    current_typology = data.get('typology')
            else:
                current_typology = data.get('typology')

            prompt = None
            if mode == 'zeroshot':
                prompt = generate_zeroshot_prompt(lang_name, test_sent)

            elif mode == 'typ':
                prompt = generate_typology_prompt(lang_name, test_sent, current_typology)

            elif mode == 'paratyp':
                prompt = generate_paratyp_prompt(lang_name, test_sent, current_typology, para_data)

            elif mode == 'para':
                prompt = generate_para_prompt(lang_name, test_sent, para_data)

            elif mode == 'paragloss':
                prompt = generate_glossed_prompt(lang_name, test_sent, glossed_para_data)

            elif mode == 'full':
                prompt = generate_full_prompt(lang_name, test_sent, current_typology, glossed_para_data)

            if prompt is not None:
                lang_prompts.append(prompt)

        all_translation_prompts[lang_name] = lang_prompts
        print(f"Создано промптов для {lang_name}: {len(lang_prompts)}")

    return all_translation_prompts

In [ ]:
def submit_batches(client, lang_name=None, endpoint='completions', storage_path='active_batch_jobs.json', base_dir='/content'):
    """
    Создает и отправляет Batch-задание для указанного языка.
    Сохраняет ID задания в JSON-файл, не перезаписывая старые данные.
    """
    filename = os.path.join(base_dir, f'batch_{lang_name}.jsonl')

    if endpoint == 'completions':
        api_endpoint = "/v1/chat/completions"
        description = f"{lang_name} Research Translation"
    elif endpoint == 'responses':
        api_endpoint = "/v1/responses"
        description = f"{lang_name} Research Translation (Reasoning)"
    else:
        raise ValueError(f"Неподдерживаемый эндпоинт: {endpoint}")

    try:
        with open(filename, "rb") as f:
            batch_file = client.files.create(
                file=f,
                purpose="batch"
            )

        batch_job = client.batches.create(
            input_file_id=batch_file.id,
            endpoint=api_endpoint,
            completion_window="24h",
            metadata={"description": description}
        )

        print(f"Успешно отправлен {lang_name}: Batch ID = {batch_job.id}")

    except FileNotFoundError:
        print(f"Файл {filename} не найден, пропускаем.")
        return {}
    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")
        return {}

    active_batch_jobs = {}
    if os.path.exists(storage_path):
        try:
            with open(storage_path, 'r', encoding='utf-8') as f:
                active_batch_jobs = json.load(f)
        except json.JSONDecodeError:

            active_batch_jobs = {}

    active_batch_jobs[lang_name] = batch_job.id

    with open(storage_path, 'w', encoding='utf-8') as f:
        json.dump(active_batch_jobs, f, ensure_ascii=False, indent=4)
    print(f"ID задания для {lang_name} сохранен в {storage_path}")

    return active_batch_jobs

## Zero-Shot

In [ ]:
all_zeroshot_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=None, mode='zeroshot')
print(all_zeroshot_prompts['Igbo'][1])
print(all_zeroshot_prompts['Basque'][0])

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 113
Translate the following sentence from Igbo to English: Dr. Ehud Ur, ọkammụta nke ọgwụ na Mahadum Dalhousie nọ na Halifax, Nova Scotia na onye isi oche nke ngalaba ụlọ ọgwụ na sayensi ahụ nke Òtù Ọrịa Shuga ndị Kanada dọrọ aka na ntị na nnyocha ahụ ka nọ n’oge ndị mbụ ya.

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that  you do not speak Igbo. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

Now write the translation:
Igbo: Dr. Ehud Ur, ọkammụta nke ọgwụ na Mahadum Dalhousie nọ na Halifax, Nova Scotia na onye isi oche nke ngalaba ụlọ ọgwụ na sayensi ahụ nke Òtù Ọrịa Shuga ndị Kanada dọrọ aka na ntị na nnyocha ahụ ka nọ n’oge ndị mbụ ya.
English:
Translate the following sentence from Basque to English: “Diabetiko izateari utzi dioten 4 hilabeteko saguak ditugu orain” gehitu zuen.

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that  you do not speak Basque. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

Now write the translation:
Basque: “Diabetiko izateari utzi dioten 4 hilabeteko saguak ditugu orain” gehitu zuen.
English:

In [ ]:
for lang, prompts in all_zeroshot_prompts.items():
    prepare_batch(lang, prompts, limit=100)

batch_Igbo.jsonl - (100).
batch_Basque.jsonl - (100).
batch_Georgian.jsonl - (100).
batch_Korean.jsonl - (100).
batch_Chamorro.jsonl - (100).

In [ ]:
active_batch_jobs = submit_batches(client, multilingual_corpus, endpoint = 'completions')

In [ ]:
active_batch_jobs

{'Igbo': 'batch_69a2b8dec88881908e88c76c359ec916',
 'Basque': 'batch_69a2b8dfd6b88190b3862911e28f0c36',
 'Georgian': 'batch_69a2b8e099508190bd9d91d77cd403a5',
 'Korean': 'batch_69a2b8e1806c819087fccd4e1061c3fb',
 'Chamorro': 'batch_69a2b8e23c5481908b554c14846d692d'}

In [ ]:
check_batch_statuses(active_batch_jobs)

In [ ]:
dfs = {}

for lang_name, batch_id in active_batch_jobs.items():
    try:
        df_lang = get_language_results(lang_name, batch_id, multilingual_corpus)

        if df_lang is not None:
            dfs[lang_name] = df_lang
            df_lang.to_csv(f'results_{lang_name}_zeroshot.csv', index=False)
            print(f"Файл для {lang_name} сохранен.")
    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")

## Typological Prompt

In [ ]:
all_typ_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=None, mode='typ', cache_typ=cache_df)

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 113

In [ ]:
print(all_typ_prompts['Igbo'][1])

Igbo is a language that exhibits specific typological characteristics. Translate the following sentence from Igbo to English: Dr. Ehud Ur, ọkammụta nke ọgwụ na Mahadum Dalhousie nọ na Halifax, Nova Scotia na onye isi oche nke ngalaba ụlọ ọgwụ na sayensi ahụ nke Òtù Ọrịa Shuga ndị Kanada dọrọ aka na ntị na nnyocha ahụ ka nọ n’oge ndị mbụ ya.

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak Igbo. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

To help with the translation, here is typological information for both languages:

The following typological features describe the grammatical features of Igbo and English including word order, verbal tense, nominal case, and other language universals. Each feature is assigned a value that indicates the extent to which the language tends to exhibit that feature.


Feature ID: GB024: What is the order of numeral and noun in the NP?
Igbo Value: Code 2

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## What is the order of numeral and noun in the NP?

## Summary
This feature focuses on the order of cardinal numerals (not ordinal numerals) and nouns in quantified noun phrases. In some languages only one order (Numeral-Noun or Noun-Numeral) is possible. In other languages both orders may be possible. This can take the form of free variation (where Numeral-Noun and Noun-Numeral order can occur interchangeably). The order may also depend on some other grammatical category which is neutral with respect to pragmaticality (e.g. definiteness). If the order depends on the noun, consider only the orders that apply to an open class of nouns and disregard orders that are restricted to a specific closed class of nouns.

## Procedure
1. Consider only phrases with the meaning 'X (numeral) units of Y (noun)' in their pragmatically neutral form. It does not matter what kind of construction is required (e.g. attributive *two books* or relative *books that are two*) or what word class the root or modifying form of the cardinal numerals belongs to, e.g. *two-ing books* (verb) or *two-some books* (noun) apply to this question.
2. If the numeral always precedes the noun, code 1.
3. If the numeral always follows the noun, code 2.
4. If a closed class of nouns requires a different order than an open class, disregard the closed class and code the order that applies to the open class.
5. If both orders occur for an open class of nouns, that is if some numerals precede and some follow, or there is a free choice or there is a choice depending on some other factor (e.g. definiteness), code 3.


This is the end of the summary for feature GB024: "What is the order of numeral and noun in the NP?".

___

Feature ID: GB401: Is there a class of patient-labile verbs?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Is there a class of patient-labile verbs?

## Summary

The term ‘labileʼ is the most commonly used label for verbs which can be used transitively or intransitively without any formal change.
A distinction is made between patient lability, more commonly referred to as P)-lability, and agent lability or A)-lability.
P-lability stands for patient-preserving lability, that is, the P argument is preserved in the intransitive construction, as in _I broke **the stick**_[P] / _**The stick** broke_. A-lability stands for agent-preserving lability, that is the A argument is preserved in the intransitive construction, as in _**John**_[A] _drinks tea / **John** drinks_.

This question asks only about P-labile verbs. Semantically, two things can happen with P-labile verbs. In case of (a) argument structure modifying P-lability, an otherwise transitive verb is used in the intransitive construction encoding an argument structure from which the A argument of the transitive construction is absent. In case of (b) less common argument structure preserving P-lability, the verb in its intransitive use implies the same participants with the same roles as in its transitive use, but in the intransitive use, the A argument is not expressed and is interpreted as non-specific.

## Procedure
1. Search for the terms ‘labile’, ‘lability’, ‘ambitransitive’ and ‘semitransitive’ in the description. If these terms are not mentioned, look up the sections on valency and transitivity in the description.
2. If no such sections exists, search for examples containing terms such as ‘burn’, ‘melt’ and ‘break’/‘broke’ and consider the relevant examples.
3. Decide whether you can find support for a set of P-labile verbs, according to the definition above. If you find examples for at least two verbs, code as 1.
4. If the source has detailed sections on valence and transitivity and labile verbs are not mentioned, code as 0.
5. If you cannot find enough information, code as ?.


This is the end of the summary for feature GB401: "Is there a class of patient-labile verbs?".

___

Feature ID: GB313: Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?

## Summary
This feature identifies phonologically independent possessive pronouns that are not formed by the application of regular possessive morphology or core case marking to more general pronominal forms. Instead, languages that qualify for a 1 code for this feature form at least some possessive pronouns through some process other than the usual possessive marking, or, frequently, with suppletive forms. Note that special adnominal possessive pronouns are most commonly found in the first and second person.

To qualify as ‘special adnominal possessive pronouns’, the possessive pronouns must not be identical to the pronominal forms used for core arguments. It is not necessary for the possessive pronouns to be dedicated solely to the function of possession, provided that the criteria above are satisfied.

## Procedure
1. Identify the regular possessive construction(s) of the language, including all possessive constructions used with full nominal possessors (e.g. English *X’s Y*, and *Y of X’s*).
2. Identify the construction(s) used to express possession with a pronominal possessor.
3. If the pronominal possessors in the constructions identified in step 2 are regular formations that are identical to any constructions identified in step 1, code 0.
4. If any of these possessive pronoun formation processes identified in 2 are different from those in 1 and result in forms that are *not* identical to the corresponding pronominal forms used to express core (S, A and P) arguments in this language, code 1.
4. If the pronominal possessors in any constructions identified in step 2 are expressed using phonologically independent, *suppletive* forms, code 1.
5. If no phonologically independent possessive pronouns exist, code 0 and include a comment to note the non-existence of the target forms.
6. If the phonologically independent pronouns used in adnominal possession are unmarked (bare), are identical to pronominal forms used for core (S, A and P) arguments, and are used in simple juxtaposition with the possessum nominal, code 0.
7. If the possessive pronouns that have triggered a 1 code are not entirely dedicated to the function of possession, please indicate in the comments any other functions these forms have.


This is the end of the summary for feature GB313: "Are there special adnominal possessive pronouns that are not formed by an otherwise regular process?".

___

Feature ID: GB400: Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?

## Summary
This question concerns languages which can index the person of an argument (S, A or P)) somewhere in the clause (i.e. either on the verb or by clitics). The question asks whether person categories are not distinguished under certain circumstances. In order for there to be neutralization, there needs to be something to ‘neutralize’ to begin with, i.e. languages without person indexing should be coded 0 for this feature. All person categories should be neutralized for the language to be coded as 1. Do not consider phonologically independent pronouns for this question. Consider only independent clauses. Consider only the moods which allow all person categories of the language to be expressed (that is, ignore imperatives, jussives, etc.)

## Procedure
1. Consider the section in the grammar that deals with verbal morphology, specifically the sections on (pronominal) agreement or argument cross-referencing.
2. If no argument is indexed on verbs, code 0.
3. If some arguments are indexed, check if there are any mentions in the sections on TAM, voice or negation of these markers being deleted under the respective circumstances. Ignore clause types which are incompatible with some person categories, e.g. imperatives. Consider only independent clauses.
5. If the indexes are deleted, code 1 and add a comment on the conditions.
6. If they are never deleted, code 0.


This is the end of the summary for feature GB400: "Are all person categories neutralized in some voice, tense, aspect, mood and/or negation?".

___

Feature ID: GB140: Is verbal predication marked by the same negator as all of the following types of predication: locational, existential and nominal?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Is verbal predication marked by the same negator as all of the following types of predication: locational, existential and nominal?

## Summary
This feature pertains only to the negative marker itself, be it an independent particle, verb, auxiliary, clitic or affix. This feature covers three kinds of non-verbal negation: locational (*The dog is not in the kitchen.*), existential (*Hogwarts does not exist.*) or nominal predication (*Ursula is not a witch.*).

## Procedure
1. Find the section in the available descriptive literature that deals with negation.
2. Find the sections that describe locational, existential and nominal predication.
3. If at least one of these three has a different negator from verbal negation, code this feature as 0.
4. If you can only find information on one of these three, and it is expressed with the same negator as verbal negation, code as ?.
5. If the source is extensive and only brings up 2 out of 3 of the functions, we can probably safely assume that if the third one was different it would have bene mentioned. Therefore we can code 1. However if the description is minimal, we should code ? because the author could just have missed the third kind of function.
6. If you cannot find information on any of these three categories of non-verbal negation, code as ?.


This is the end of the summary for feature GB140: "Is verbal predication marked by the same negator as all of the following types of predication: locational, existential and nominal?".

___

Feature ID: GB138: Can standard negation be marked clause-initially?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Can standard negation be marked clause-initially?

## Summary
This feature focuses on standard negation, or the construction(s) that mark negation of (at least) dynamic (i.e. non-stative) verbal predicates in declarative mood. It is possible that the same negation construction will be used for other purposes as well (e.g. with stative or non-verbal predicates), but clauses involving predicates other than the aforementioned dynamic verbal predicates in declarative mood should be disregarded.

The position ‘clause-initial’ includes prefixes on clause-initial verbs, even if the negator is not the left-most prefix, but suffixes on clause-initial verbs do not count as clause-initial negation. If the negator consists of two obligatory elements and only one is clause-initial, this is sufficient to count as clause-initial negation and to trigger a 1 for this feature. As with other word order features in this dataset, we are concerned with the order of the negative marker when the clause has its canonical intransitive or transitive word order. We are not interested in cases of argument omission or pragmatically marked constructions (e.g. focus); these should be disregarded in coding this feature.

## Procedure

1. Find the section in the available descriptive literature that deals with negation.
2. Consider all the described standard negation constructions (i.e. those that negate dynamic verbal predicates in declarative mood).
3. If the negative marker is clause-initial in any construction identified in step 2, code 1.
4. If there are multiple markers of standard negation and one is clause-initial, code 1 (and if the other is clause final, code 1 for GB137	Can standard negation be marked clause-finally? as well).
5. If there is no clause-initial marker of clausal negation, code 0.
6. If clause-initial markers of clausal negation only occur in pragmatically marked constructions, or with non-verbal or stative predicates, or in non-declarative clauses, code 0.
7. If a marker of standard negation only occurs clause-initially as a result of argument omission (and occurs in a non-initial position when independent nominal or pronominal arguments are included), code 0.


This is the end of the summary for feature GB138: "Can standard negation be marked clause-initially?".

___

Feature ID: GB203: What is the order of the adnominal collective universal quantifier ('all') and the noun?
Igbo Value: Code 2

English Value: Code 3

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## What is the order of the adnominal collective universal quantifier (‘all’) and the noun?

## Summary
This feature is concerned with the ordering of a universal quantifier (‘all’) and the noun. As with other word order features in this database, this is focused specifically on adnominal quantification in pragmatically unmarked contexts. In languages that do not have a distinction between collective and distributive universal quantifiers (‘all’ vs. ‘every’), a quantifier that could be translated as ‘all’ and has a primarily plural use will be a sufficient target for this feature.

There are four possible codes for this feature, reflecting the fact that the collective universal quantifier might occur strictly before or strictly after the noun, may be allowed in both of these relative positions, or may not be present in a language. A 0 code is also applicable when the language does not allow a basic construction with an adnominal collective universal quantifier and a noun (e.g. if only a floating construction is used).

Orders that result from constructions like quantifier float (e.g. English *The children have **all** come.*) should be disregarded for the purposes of coding this feature.

## Procedure
1. If there is a collective universal quantifier, or a general universal quantifier that can be translated as ‘all’, and that quantifier occurs only before the noun (UQ-N), code 1.
2. If there is a collective universal quantifier, or a general universal quantifier that can be translated as ‘all’, and that quantifier occurs only after the noun (N-UQ), code 2.
3. If the collective universal quantifier or equivalent can occur either before or after the noun (UQ-N *or* N-UQ) in non-quantifier float constructions, code 3.
4. If there is no collective universal quantifier or other universal quantifier that can be translated as ‘all’ and be used in an adnominal construction, code 0.
5. If there is no mention of universal quantifiers at all, code ? and note that there is insufficient information to make a determination.


This is the end of the summary for feature GB203: "What is the order of the adnominal collective universal quantifier ('all') and the noun?".

___

Feature ID: GB091: Can the A argument be indexed by a suffix/enclitic on the verb in the simple main clause?
Igbo Value: Code 0

English Value: Code 1

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Can the A argument be indexed by a suffix/enclitic on the verb in the simple independent clause?


## Summary
Is there a phonologically bound A argument) index that follows its verbal host (i.e. attaches to it as a suffix or an enclitic)?

## Procedure
1. Consider the section in the grammar that deals with verbal morphology, specifically the subsections on (pronominal) agreement or argument cross-referencing.
2. Code 1 if there is a phonologically bound element that indexes the A argument on the verb or auxiliary. The index needs to follow the verbal host it is bound to.
3. If there is some variation in the position of the A index conditioned by the verb (e.g. most verbs code the A argument with a suffix, but a couple use a prefix), consider only the patterns which occur with large classes of verbs.
4. If the verb shows overt indexing only with some arguments (e.g. only with animate arguments or only with first person singular arguments, the situation known as differential argument indexing), this still counts as 1.
5. If the A argument is indexed but not by a suffix or enclitic, code 0.
6. If there is no indexing of the A argument, code 0.
7. If only a small set of verbs (fewer than a dozen) indexes A arguments, code 0.
8. Ignore all other ways of indexing arguments (e.g. via a stem alternation, stress or tone), they are not covered by any of the Grambank features.


This is the end of the summary for feature GB091: "Can the A argument be indexed by a suffix/enclitic on the verb in the simple main clause?".

___

Feature ID: GB092: Can the A argument be indexed by a prefix/proclitic on the verb in the simple main clause?
Igbo Value: Code 1

English Value: Code 0

—
Below is a short summary of the grammatical feature, an explanation of the process for assigning the feature’s
code, and examples of the feature from other languages including interlinear glossed text.
—
## Can the A argument be indexed by a prefix/proclitic on the verb in the simple independent clause?



In [ ]:
for lang, prompts in all_typ_prompts.items():
    prepare_batch(lang, prompts, limit=100)

batch_Igbo.jsonl - (100).
batch_Basque.jsonl - (100).
batch_Georgian.jsonl - (100).
batch_Korean.jsonl - (100).
batch_Chamorro.jsonl - (100).

In [ ]:
active_batch_jobs = submit_batches(client, multilingual_corpus, endpoint = 'completions')

In [ ]:
check_batch_statuses(active_batch_jobs)

In [ ]:
dfs = {}

for lang_name, batch_id in active_batch_jobs.items():
    try:
        df_lang = get_language_results(lang_name, batch_id, multilingual_corpus)

        if df_lang is not None:
            dfs[lang_name] = df_lang
            df_lang.to_csv(f'results_{lang_name}_typ.csv', index=False)
            print(f"Файл для {lang_name} сохранен.")
    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")

## Parallel only

(future work)

In [ ]:
#all_para_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=200, mode='para')

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 113

In [ ]:
#print(all_para_prompts['Igbo'][1])

Igbo is a language that exhibits specific typological characteristics. Translate the following sentence from Igbo to English: Dr. Ehud Ur, ọkammụta nke ọgwụ na Mahadum Dalhousie nọ na Halifax, Nova Scotia na onye isi oche nke ngalaba ụlọ ọgwụ na sayensi ahụ nke Òtù Ọrịa Shuga ndị Kanada dọrọ aka na ntị na nnyocha ahụ ka nọ n’oge ndị mbụ ya.

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak Igbo. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

To help with the translation, here are some example Igbo-English parallel sentences and words:
Igbo: àkụ̀ nà ụ̀ba
English translation: material and non-material resources (=wealth)
Igbo: Onwu bù ndù.
English translation: Death is life.
Igbo: àmăde á lEÙ-òlu
English translation: Amade will sleep.
Igbo: -kèle
English translation: greet
Igbo: Ùnù èjè ahia
English translation: Did(pl.) you go to market?
Igbo: òrigò / òri`o`ò`
English translation: an eater because one cannot be anything else
Igbo: ibhhe
English translation: thing
Igbo: ù͠shì͠à
English translation: neatness
Igbo: nnà
English translation: father
Igbo: -wèbà
English translation: take into
Igbo: ò̄dì̄rì̄bendī
English translation: traditionality
Igbo: i-rī-go
English translation: to have eaten
Igbo: O nà-eso ha ème ya
English translation: He does it in their company.
Igbo: O jù rù ya mà ò gà-àbì a u bò chì ahù ?
English translation: He asked her whether she would come on that day?
Igbo: if͠ò͠
English translation: to wash
Igbo: o͠zò͠
English translation: gorilla
Igbo: ihye mmaÛ
English translation: thing of beauty
Igbo: eqe
English translation: teeth
Igbo: òrimaòri?
English translation: one with a big appetite
Igbo: O nàtààra yà ego nye Àda
English translation: He got money from him and gave it to Ada.
Igbo: Mmirī nà-àgu ya agu
English translation: He is thirsty.
Igbo: wèmìna ūkwu ūlò
English translation: Withdraw completely from public view.
Igbo: m/mū nà ya
English translation: I am she/he
Igbo: O gà-àtùposi ya
English translation: He will put spots on it.
Igbo: Azu`Ûtaala mÛ akwà ahù`
English translation: I have bought that cloth.
Igbo: bì-re-è-kì
English translation: break
Igbo: imèrịrịrị
English translation: to still do
Igbo: ejèrè hà
English translation: They went.
Igbo: àh͠ù͠
English translation: body, trunk
Igbo: ulo Agu
English translation: Agu’s house
Igbo: o-ji-ī / o-ji-eÛ
English translation: black (ness)
Igbo: Koo le ihe bu tere ihe a ?
English translation: What must have brought this about?
Igbo: Ūmù̄nnà nà-èbiko ōnu
English translation: Kinsmen live together.
Igbo: èbee
English translation: (place) where?
Igbo: -bubàta
English translation: carry inside
Igbo: īfu n’anya
English translation: to love/admire
Igbo: O chōrō m̄
English translation: He’s looking for me.
Igbo: o zùgò
English translation: enough
Igbo: Ogu tùrù àsị
English translation: Ogu told a lie.
Igbo: Ryê
English translation: Eat (it)!
Igbo: N̄gī zī kwō
English translation: You(sg) too!
Igbo: -mya
English translation: lose dignity
Igbo: Kà
English translation: Let…; That…
Igbo: -kuzi
English translation: teach
Igbo: Nwatā à èriele nrī
English translation: This child has eating the food.
Igbo: Nwaànyī à gà-àbīa (echī)
English translation: This woman will come (tomorrow).
Igbo: -bi͠a
English translation: come
Igbo: O gbàrà ōsō gawa ūlo
English translation: He went home running.
Igbo: gbùrùgbùru
English translation: roundness
Igbo: ihe ojiī
English translation: black thing
Igbo: u͠xu͠
English translation: bat
Igbo: Òwe
English translation: Let it be so; Amen
Igbo: onye
English translation: one who… / thing/person
Igbo: O rīelà nri ahù èri
English translation: He has really eaten the food.
Igbo: O kwùola yà
English translation: He has said it.
Igbo: Mà hà kwè, mà hà èkweghī
English translation: Whether they agree or they do not agree
Igbo: -zà
English translation: sweep
Igbo: Àdâ bùrù ibù
English translation: Ada is fat.
Igbo: Ndi à cha bìà rà òriri
English translation: All these came in the feasting.
Igbo: Gi ma onye gara
English translation: You, the one who went
Igbo: Lò̄kwa ngwa ǹgwa:
English translation: Come back quickly.
Igbo: O nò nà ya
English translation: He is at it.
Igbo: Ùfufè bùsàsìrì akwụkwọ ahù èbusàsị
English translation: The wind really blew the leaves about.
Igbo: Ò gaghī` àlu` ya, ò bù`kwà ya?
English translation: He will not marry her; is it so?
Igbo: ōnú̄ù
English translation: mouth
Igbo: Nwaànyi à nò nà di.
English translation: This woman is married.
Igbo: O zùrù yà àzụ̀rụ̀ n’ebe ahù
English translation: He really bought it there.
Igbo: ezi okwu
English translation: True
Igbo: Gī kwa nu
English translation: You yourself
Igbo: Ò daÛbàrò mÙmadù ípùò mewe ihe enweÛro isi.
English translation: It is of no use for one to go out and do something worthless.
Igbo: Òle jèrè ù nyàahù ?
English translation: How many people went yesterday?
Igbo: bo͠tù͠lù͠
English translation: bottle
Igbo: ozu
English translation: corpse
Igbo: Gi nī (bù n ke à)?
English translation: What (is this)?
Igbo: mmèvò
English translation: the act of behaving and exposing another to ridicule
Igbo: ọ bụlàdị
English translation: even if
Igbo: Ùka, ò jèrè ahịa?
English translation: Uka did she go to the market?
Igbo: ntụ̀ghari
English translation: (the act of) turning about
Igbo: ma njàkìrì
English translation: bluff, take carelessly to
Igbo: isi kote èbù, Èbù àgbaa ya
English translation: (It is) the head that invites the wasp, the wasp will attack it.
Igbo: ma uka
English translation: teach or make to become talkative
Igbo: A nà-àgba motò àga Legòs
English translation: People go to Lagos in vehicles.
Igbo: O gà ibīa, echī.
English translation: He is going to come tomorrow.
Igbo: E jì azīzà azà ūlo.
English translation: People sweep the house with a broom.
Igbo: O na-èchèzọka ihe
English translation: He is always forgetting about things.
Igbo: Mū nà gī, ànyì jèrè ahīa?
English translation: Did you(sg) and I go to market?
Igbo: mÙmadu` mkpu`mkpu`
English translation: short man
Igbo: Àkwa o` zuÛ`tara màrà mmaÛ
English translation: The egg (which) she bought is good.
Igbo: Mmanụ à gbazèrè àgbàzè
English translation: This oil has really melted.
Igbo: O wūū n’aka ha kà ō gà īwūūsa ya
English translation: It is on his hand that it will be poured.
Igbo: Kwùo yā.
English translation: Say it out.
Igbo: Etè m chò à
English translation: I wanted it.
Igbo: O tòsìrì i`laÛala ugbu à
English translation: He ought to have go by now.
Igbo: -bì̄à
English translation: to come
Igbo: afi͠a
English translation: market
Igbo: è͠no͠
English translation: four
Igbo: O chòrò nri
English translation: He wants food.
Igbo: Àn aa (kà o dì )?
English translation: How (does it look)?
Igbo: O kwèsì`rì` irīchaala nri ahù
English translation: He ought to have eaten up that food.
Igbo: O wūū n’unù kà ō gà īwūūsa ya
English translation: It is on you(pl) that he will pour it.
Igbo: Ndi à fù chò rò nri
English translation: These very ones want food.
Igbo: bhì͠a
English translation: stuff with
Igbo: Erīghi` nri anaÛghi` àdí` mmá n’àhu`
English translation: Not to eat is bad for the body.
Igbo: u͠ryi͠a͠
English translation: a sharp cut
Igbo: Kà Chike gbàsìrì ōsō, ō kpò̄rō òriri.
English translation: After the race, Chike called a party
Igbo: Gèkaa ntì`
English translation: Please, listen.
Igbo: ihe ogologo
English translation: long thing
Igbo: O nà-èmevòka ndi mmadụ
English translation: He is always behaving and exposing others to ridicule.
Igbo: Àda gààrà èje Āba
English translation: Ada was to have gone to Aba.
Igbo: oke
English translation: male
Igbo: Gi nà ya ùnù gà-àbi a echī?
English translation: You and him will you(pl) come tomorrow?
Igbo: Ọhà nà eẓe
English translation: The commoners and the nobility
Igbo: ibī n’ EBE
English translation: to live at a PLACE
Igbo: Ūmù̄nnà nà-ègbu mmàdù
English translation: Kinsmen destroy one.
Igbo: O nà-àzū ahī̄a ù̄gbu à
English translation: He is right now selling and buying.
Igbo: īfu anya
English translation: to be amazed at
Igbo: O gà mbià, echī.
English translation: He certainly will come tomorrow.
Igbo: o`-hu`-uÛ`
English translation: new (ness)
Igbo: Ànyí àgáwálá nzùkó
English translation: We have started to go to meetings.
Igbo: -iwe
English translation: swallow
Igbo: O jì ya èhiri isi èhiri
English translation: He is really using it for laying his head on.
Igbo: O gbùrù ya
English translation: He killed it.
Igbo: Àda sò Uzo èje akwūkwō
English translation: Ada goes with Uzo to school.
Igbo: Ego à i nyèèrè m, ò pùtàrà gīnī?
English translation: This money you have given me, what is it for?
Igbo: ezhì
English translation: pig
Igbo: Nwaànyi à kpà àhù.
English translation: This woman is robust.
Igbo: òcha
English translation: whiteness
Igbo: O` gà irī nri
English translation: He is going to eat food.
Igbo: ibùbàtà
English translation: to carry into
Igbo: Kò mo` há.
English translation: He doesn’t know a thing.
Igbo: ngwʱùgwʱù
English translation: parcel; wrapping
Igbo: ulo ego
English translation: the house of money (bank)
Igbo: o͠rì͠à
English translation: sickness
Igbo: O rìrì elu/elu
English translation: He climbed up.
Igbo: E tìnyèwànyèrè ego etinyewanye
English translation: They have really increased the cost.
Igbo: n’ ìhì nà
English translation: because
Igbo: ele
English translation: deer
Igbo: O gà-àzụ̀ta ya echi
English translation: He will buy it tomorrow.
Igbo: E ji ego àcho mma
English translation: People use money to look for beauty.
Igbo: (N ke à bù ) gi nī ?
English translation: What (is this)?
Igbo: ù͠kpo͠
English translation: twenty
Igbo: mkpòsa
English translation: (the act of) throwing upon
Igbo: Iseleukwu operates a ten-vowel system even though /e/ and /ε/ sounds seem to be in free variation as found in (the) –ne and –nε negative morpheme
English translation: Iseleukwu operates a ten-vowel system even though /e/ and /ε/ sounds seem to be in free variation as found in the –ne and –nε negative morpheme.
Igbo: mma̋
English translation: beauty
Igbo: e kwùrù
English translation: An unidentified person has said…
Igbo: anūmànù̄
English translation: animal world
Igbo: Ùwe à tùpòsìrì àtùposi
English translation: This dress really has spots on it.
Igbo: Èbee dì ihe à?
English translation: Where (is this)? (Where are we?).
Igbo: O chōrō yà
English translation: He’s looking for him.
Igbo: ezè
English translation: titled man, king
Igbo: NÙnennà
English translation: female personal name
Igbo: ù͠di͠ri͠
English translation: type
Igbo: ezê
English translation: tooth
Igbo: sùkulù
English translation: school
Igbo: Òle (kà ha dì )?
English translation: How many (are they)?
Igbo: ndi
English translation: people who, things/which… persons
Igbo: Nna ha gbàrà ohù
English translation: Their father owned slaves.
Igbo: ù͠fo͠
English translation: leftover
Igbo: O gà gbàghà maì
English translation: He now trades in wine
Igbo: Ekwùla ihe à!
English translation: Don’t say this. It is too close to call!
Igbo: Ō lòkwala ngwa ǹgwa
English translation: He has returned quickly.
Igbo: eze̋
English translation: teeth
Igbo: O maÛ–àbi`a akwu`kwo`
English translation: He will not come to school
Igbo: Ō gbàala ōsò:
English translation: He has run away.
Igbo: Rie jī.
English translation: Eat some yam.
Igbo: Deème
English translation: Well done
Igbo: Yanwà ò gà-àbi a taà?
English translation: She herself will you come today?
Igbo: ur͠ywe
English translation: weight
Igbo: Yaa
English translation: Yes (indeed)
Igbo: imèsi
English translation: to do persistently
Igbo: O dī-àcho ya
English translation: He is not looking for it.
Igbo: Ihe a tìpìàsìrì ètipi a
English translation: This thing is thoroughly broken to bits.
Igbo: ūnò̄ agūꜜ
English translation: leopard’s house
Igbo: Òwère bà?a
English translation: come in
Igbo: bèe yaÛ mkpu`mkpu` mÛkpu`mkpu`
English translation: cut it up in short/small bits/lumps
Igbo: o͠dvu͠
English translation: pestle
Igbo: Àmaghī m ihe ō bùlà bànyere ya
English translation: I do not know anything about it.
Igbo: dìe
English translation: endure
Igbo: O gà-èmeriri
English translation: He will have to/must do it
Igbo: O mèvòrò yà èmevò
English translation: He really exposed him to ridicule.
Igbo: Ònye mèrè ihe à?
English translation: Who did this?
Igbo: O gbàrà egbè
English translation: He fired a gun.
Igbo: ngwerì
English translation: (the act of) grinding to fine pieces
Igbo: mbè
English translation: tortoise
Igbo: Ǹdàalū
English translation: Thank you
Igbo: Nri o` zù`tàrà màrà mmaÛ
English translation: The food (which) she bought is good.
Igbo: Unù jèrè ozi.
English translation: You(pl) went on an errand.
Igbo: O rìrì nri ahuù ntàki ri .
English translation: He ate the food, a little.
Igbo: Ihe gī màsì rì Àda; ò bu ghī ya?
English translation: Ada loves you; is it not correct?
Igbo: O bù ìtìbolibo
English translation: He is a stack illiterate
Igbo: Kà o mesia
English translation: So long
Igbo: ndù͠
English translation: life
Igbo: ò-zi-za
English translation: answering
Igbo: ànyī nà gī
English translation: we and you
Igbo: Ùwe à, ì tìrì taà, ò pùtàrà gīnī?
English translation: This dress you are putting on today, what does it represent?
Igbo: Kèdu ebe o gàrà?
English translation: Which place did he go to?
Igbo: -webàta
English translation: take inside
Igbo: Hà èjè ahīa
English translation: Did they go to market?
Igbo: Gàanù` ju`o` yaÛ echìchè ya bhànyere O`phara
English translation: Go and ask him what he thinks about Opara.
Igbo: Ùwe n ke a, ò gà-àmasi gī ?
English translation: Would you like this dress?

Now write the translation:
Igbo: Dr. Ehud Ur, ọkammụta nke ọgwụ na Mahadum Dalhousie nọ na Halifax, Nova Scotia na onye isi oche nke ngalaba ụlọ ọgwụ na sayensi ahụ nke Òtù Ọrịa Shuga ndị Kanada dọrọ aka na ntị na nnyocha ahụ ka nọ n’oge ndị mbụ ya.
English:

## Parallel + TYP

In [ ]:
all_paratyp_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=100, mode='paratyp')

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 113

In [ ]:
print(all_paratyp_prompts['Basque'][1])

Basque is a language that exhibits specific typological characteristics. Translate the following sentence from Basque to English: Ehud Ur doktoreak ohartarazi du ikerketa hasierako fasean dagoela oraindik. Doktorea medikuntza-irakaslea da Halifax-eko (Eskozia Berria) Dalhousie Unibertsitatean eta Kanadako Diabetes Elkarteko atal kliniko eta zientifikoko zuzendaria da.

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak Basque. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

To help with the translation, here are some example Basque-English parallel sentences and words:
Basque: San Vicenteren besoa hautsi dute.
English translation: They broke Saint Vincent's arm.
Basque: genien
English translation: we had it to them
Basque: Gaurko ekitaldian epaimahaiek sariak banatuko dituzte.
English translation: In today's ceremony, the committee members will distribute the prizes.
Basque: Jauzi(ka)/salto(ka) egin dute.
English translation: They jumped.
Basque: Ez dakizkidan gaiez mintzatu nahi nuen.
English translation: I wanted to speak about subjects I don't know.
Basque: Mikel lodi(a) dago.
English translation: Mikel is fat.
Basque: Esan behar nuena esanda dago.
English translation: What I had to say has been said.
Basque: Jende asko agertu da, baina ez ikasle asko.
English translation: Many people showed up, but not many students.
Basque: Ematen du Jon nekatuta dagoela.
English translation: It seems that Jon is tired.
Basque: Badiat beldurra ez dakikan zein abilki jokatu zen behin Sarako jaun hauzapez bat, [zeinak izena baitzuen Erremundegibehere].
English translation: I am afraid that you don't know how cleverly acted a mayor of Sara, whose name was Erremundegibehere.
Basque: Norena da liburu au?
English translation: Whose is this book?
Basque: osoa
English translation: ‘whole’
Basque: Berrogoi ta hamar metretan... igortzen zukeen bere burdin-pikorra.
English translation: He probably threw its cannonball... fifty meters away.
Basque: eman iezazkiguzue
English translation: give them to us! (you-PL)
Basque: Ez dela etorri esan didate.
English translation: They told me that she/he didn't come.
Basque: Sp eterno > Bermeo otorno
English translation: ‘funeral’
Basque: Joan dira enarak, hasi da negua.
English translation: The sparrows have left, winter has begun.
Basque: Neuk emango diet informea atzoko bileran eskatu zidatenei.
English translation: I will give the report to those who requested it at the meeting yesterday.
Basque: Egunaren ederra!
English translation: The beauty of the day! (How beautiful is the day today!)
Basque: egon > ogon
English translation: ‘be, stay’
Basque: Nik ez ditut aurkitu... bila nenbiltzanak.
English translation: I did not find ... the ones that I was looking for.
Basque: Horren lotsa naiz.
English translation: I am ashamed of that.
Basque: Nor ez da etorri?
English translation: Who didn't come?
Basque: Etxe bat erosi behar dut Bilbon.
English translation: I need to buy a house in Bilbao.
Basque: Jonek bere burua gorroto du.
English translation: Jon hates himself.
Basque: Jaunaren legeko esi biguna urratuko balitz
English translation: if the soft fence of the Lord broke
Basque: Miren bilbotarra/bilbotar da.
English translation: Miren is from Bilbao.
Basque: Bi udaltzainek ukatu dute bidaian Rubioren bizkartzain izan zirenik.
English translation: Two police officers have denied that they had been Rubio's bodyguards during the trip.
Basque: Mila aldiz esana diot hori Mireni.
English translation: I have said this to Miren a thousand times.
Basque: jo
English translation: money
Basque: Badut ikusi
English translation: I HAVE seen.
Basque: Pozaldi bakoitzak berekin dakar onaze ta nekea.
English translation: Every moment of happiness brings with it suffering and fatigue.
Basque: Bost umerekin eta oinez etorri zen Bilbotik.
English translation: She came from Bilbao with five children and on foot.
Basque: Espainolek iduri dute ez dakitela borrokatzen elgar sangratu gäbe.
English translation: Spaniards seem not to know [that they don't know] how to fight without bleeding each other.
Basque: Gurasoek sufritu dute gehienJgehienalgehienik.
English translation: The parents suffered the most.
Basque: Inkesta batek erakutsi du Hegoaldeko biztanleak pozik bizi direla.
English translation: A survey has shown that citizens from the South (of the Basque Country) are happy with their lives.
Basque: aulki(aren) azpian
English translation: under the chair
Basque: Mikelek Joni bere beso(etako) bat hautsi dio.
English translation: Mikel broke Jon one of his arms.
Basque: Nola esan du Jonek uste duela Peruk egin beharko litzatekeela?
English translation: How did Jon say Peru thinks it should be made?
Basque: Euskara batu-a erdi-alde-ko euskalki-an eraiki izan-a erabaki znzen-a iza-n ze-la.
English translation: That the constructing of Standard Basque on the [basis of the] central dialect was the correct decision.
Basque: Zuk Bilbon etxe bat erostea behar dut.
English translation: I need for you to buy a house in Bilbao.
Basque: Nolako gereziak dituen gereziondo horrek!
English translation: Such cherries in that cherry tree!
Basque: Haurra isilik/bakarrik/zutik da(go).
English translation: The child is quiet/alone/standing.
Basque: Obra hori da [Oteizak Bilboko museoari utzi nahi liokeena].
English translation: It is this work that Oteiza would like to bequeath his works to the Bilbao Museum.
Basque: mutildgaz
English translation: with the boy
Basque: Lehenago, nork ere pagatzen baitzuen barrika arno gehienik-eta, hura zukan pasatzen bozetan.
English translation: ‘Before, whoever paid the most barrels of wine (and) that one won the election.’
Basque: Uste nuen nar honek tela hain handia.
English translation: Idiot that I am, I thought it was so big
Basque: Nik alproja horiek adiskide(ak) ditut.
English translation: Those curs are my friends.
Basque: Berrogoi urtez holaxet izkiriatu ukan ditu(...) bere berriak.
English translation: He wrote his news in this way during forty years.
Basque: Untzi bat agertu da ostertzean.
English translation: A ship appeared in the horizon.
Basque: Gai horretan Epi eta Bias ados daude elkarrekin.
English translation: Ernie and Bert agree with each other on that topic.
Basque: *Peruk liburu bat oparitu zion bere alabari gaixorik.
English translation: Peru gave a book to his sick daughter.
Basque: Bulegoan dago, ez etxean.
English translation: He is at the office, not at home.
Basque: hurrengo egunean
English translation: the next day
Basque: zu bezalako jende azkarra
English translation: intelligent people like you
Basque: Liburu hau da [lagunek iaz eskaini zidaten]-a.
English translation: This book is the one my friends offered me last year.
Basque: goizean
English translation: in the morning
Basque: GURE IKASLEAK ere joan dira.
English translation: Even OUR STUDENTS went/OUR STUDENTS also went.
Basque: Horretaz mintzatu naiz.
English translation: I talked about that.
Basque: Jonek Aitor anaia du.
English translation: Aitor is Jon's brother.
Basque: Esango al zeniguke zerbait azkenik?
English translation: Would you tell us something finally?
Basque: Liburuari interesgarria deritzot.
English translation: I consider the book interesting.
Basque: Bi mendik elgar atxeman lirote behar bada, bainan ez zuek.
English translation: Two mountains could join together, maybe, but not you two.
Basque: Ameriketan, hamabietan bazkaltzen dute.
English translation: In America, they have lunch at twelve.
Basque: Begi zorrotzak izan ditut hutsak ikusteko, batez ere, huts horiek geure buruarenak, neronenak barne, direnean.
English translation: I had sharp eyes to detect errors, especially when these errors are our own, including mine.
Basque: Soilik kolpe hartu nuen lekuan ukitzen badut egiten dit min.
English translation: Only if I touch where I was hit does it hurt.
Basque: Zu azkarragoa zara, Koldo baino.
English translation: You are faster than Koldo.
Basque: Guk gizon indartsu baina koldarrak genituen.
English translation: Our men were strong but coward.
Basque: Banekien Mikel berandu etorriko zena.
English translation: I knew that Mikel would arrive late.
Basque: Emanen ere didazu, nere bizi zaren-a, aurreko egun hartan han eman zenidana.
English translation: (You), who are my life, you'll give me what you gave me that day.
Basque: Ukatu du inor etorri denik.
English translation: He/she denied that anybody came.
Basque: Lanean ari da.
English translation: He is working.
Basque: Jon etorri da.
English translation: Jon has come.
Basque: Ibai hura igaro dute.
English translation: They crossed that river.
Basque: ados jarri dira?
English translation: What do they agree with?
Basque: Alderdiek suetenak jarraitzeko erregutu diote ETAri.
English translation: The parties have urged ETA for the ceasefire to continue.
Basque: KOTXEA ETXEAN utzi nuen atzo
English translation: I left THE CAR AT HOME yesterday.
Basque: Guk ezin egin detzakeguken lanak egiten dituzte.
English translation: They do jobs that we can't.
Basque: Koldo goiz esnatzen bada, ni are goizago esnatzen naiz.
English translation: ‘If Koldo wakes up early, I wake up even earlier.’
Basque: Elizak pobreei dirua emanerazten digu.
English translation: The Church makes us give money to the poor.
Basque: ezin joatea
English translation: not to be able to go
Basque: bere burua engainatzen denean...
English translation: when one deceives himself...
Basque: Erregeak soldaduei haur guztiak hilerazi zizkien.
English translation: The king made the soldiers kill all the children.
Basque: Uste duzun baino handiagoa da.
English translation: It is bigger than you think.
Basque: Beti dabiltza diruak pilotzen.
English translation: They are always piling up money.
Basque: ez ote da dagoeneko istilu garratzik sortu arlo honetan?
English translation: Have there not been bitter fights already in this area?
Basque: Etorri bezala joango dira.
English translation: They will go just as they have/will come.
Basque: Ez dut uste inor etorriko dela esan dutenik.
English translation: I don't think they said that anybody will come.
Basque: Mikelek deitxü eiii ddotzo Mireneri.
English translation: Mikel has called Mary.
Basque: Miren bilbotarra/gaztea duzu.
English translation: Miren is from Bilbao/young.
Basque: Joni irudi-tu/tzen zaio Xabier ez dela etorriko.
English translation: It seems to Jon that Xabier will not come (lit. 'Jon seems that...').
Basque: Buruan ontsa sartua zuen etsaiari ez zuela amorrik eginen.
English translation: He had it well put into his mind that he would not surrender to the enemy.
Basque: goiz etorriko dira
English translation: they will arrive early
Basque: Animaliek desio dute.
English translation: Animals desire it.
Basque: Garazi oso urduri/lasai/gaixo dago.
English translation: Garazi is very nervous/calm/sick.
Basque: Nork galdetu du ea liburua JONEK erosi duen?
English translation: Who asked whether it was Jon that bought the book?
Basque: jakingo banu, esango nizuke
English translation: if I knew it, I would tell you-sg
Basque: Kontrabandoa pasatu dute.
English translation: They passed the contraband.
Basque: ez dut zakurrik ikusi
English translation: I haven't seen any dogs
Basque: nire gusturako, ez da oso ona
English translation: for my taste, it is not very good
Basque: Deliberatu dute zuk eta nik paper guziaklguzien biltzea.
English translation: They decided upon you and I gathering all the paper.
Basque: Nik ezingo nuke inolaz ere han bizi.
English translation: I would not be able to live there in any way.
Basque: Batasunak erronka berriei nola aurre egin eztabaidatuko dute hamabost estatuburuek.
English translation: The fifteen heads of state will discuss how the European Union may confront the new challenges.
Basque: Β mutttakaz
English translation: with the boys
Basque: Xabierrek kotxea sartu du.
English translation: Xabier has put the car inside.
Basque: merkatuan erosi dituzun sagarrak
English translation: the apples that you bought in the market.
Basque: Zakurrak hondakinak usnatu zituen.
English translation: The dog smelled (all) the garbage.
Basque: Ez dakit zure laguna etorriko d-entba-da.
English translation: I don't know whether your friend will come.
Basque: Zeure buruan baino ez duzu pentsatzen.
English translation: You only think about yourself.
Basque: Jonek eta Mirenek elkarrekin afalduko dute.
English translation: John and Mary will have dinner together.
Basque: Ez daukat diru askorik.
English translation: I don't have much money.
Basque: Ez dadila etor hona!
English translation: Let him not come here!
Basque: Gaixoa den-dena jaten behartu zuten erizainek.
English translation: The nurses forced a sick person to eat all.
Basque: etor bedi
English translation: may it/he/she come
Basque: Gaur gauza inportante batzuk ahaztu dituzu/ditugu.
English translation: Today you/we forgot important things.
Basque: Jonek liburu hori irakurri du?
English translation: Has Jon read that book?
Basque: Politika horrek prezioak jeitsierazi zituen.
English translation: That policy made prices go down.
Basque: atetatik > atet[t:]ik
English translation: ‘from the doors’
Basque: Jonen etxeko izan ditu itoginak.
English translation: Jon's house ROOF/WHAT has had leaks.
Basque: Esango dizuet zer den film, hori, ikusi gabe lasai geldi zaitezten.
English translation: I will tell you what that movie is, so you remain relaxed without seeing it.
Basque: Orduan hil bazina, zureak egin zukeen, (...), Jainkoaren presentziaz eta gloriaz ez zinen sekulan gozatuko.
English translation: If you had died then, you would have been lost (...), you would have never enjoyed the presence and the glory of the Lord.
Basque: Lagunez, adiskideez eta etxekoez mintzatu ziren.
English translation: They were talking about acquaintances, friends and family.
Basque: Joxeren host liburu eta sei aldizkariak.
English translation: Joxe's five books and six magazines.
Basque: Semea joan zaio Ameriketara Mikeli.
English translation: Mikel's son went to America.
Basque: Pellori ez zaio arraina gustatzen, baina Josebari bai.
English translation: Pello doesn't like fish, but Joseba does.
Basque: Horrela gertatu denik esan gäbe ezin gelditu.
English translation: Impossible to remain without saying that it happened that way.
Basque: Errieta(n) egin dute.
English translation: They disputed.
Basque: nahi duzun arte
English translation: until you want (to meet again)
Basque: eman diguzu
English translation: you have given it to us
Basque: Elkarrekin hasi dira borrokan.
English translation: They started fighting each other.
Basque: ikhusiz debruak zonbat sofriarazten dioen haren alaba maiteari
English translation: upon seeing how the devil made his dear daughter suffer
Basque: Gogoratu naizena hori/horretaz da.
English translation: What I recall is that.
Basque: Kalte behintzat ez dizu horrek egingo.
English translation: At least that will not do any harm.
Basque: Berba egitean, aitaren antza dauka.
English translation: She takes after her father in (the way/act of) speaking.
Basque: barazki eta gozoki saltzaileak
English translation: vegetable and candy sellers
Basque: kadenaz-ere nehork esteka ziroen
English translation: ... nobody could tie him even with chains
Basque: Ez naiz oroit [zer erran nuen orduan],
English translation: I don't remember what I said at that moment.
Basque: Gu aipatu gaitut.
English translation: I mentioned us.
Basque: Epi eta Bias elkarren ondoan jezarri dira.
English translation: Ernie and Bert sat next to each other.
Basque: Bazekien, baina ahaztu egin du.
English translation: S/he did know, but s/he has forgotten.
Basque: denetarako balio du
English translation: it is good for everything
Basque: Gaitasunari garrantzia gehiago eman diogu erabilerari baino.
English translation: We have given more importance to competence than to usage.
Basque: Bada, Euskal Herri-art kontrako-a gerta-tzen da.
English translation: Well, in the Basque Country, the opposite happens.
Basque: Harritu egin nau haurrak gezurra esan (izan)a-k.
English translation: The child's having said a lie surprised me.
Basque: Bere buruaren erretratuak lotsa ematen dio Amaiari.
English translation: The portrait of herself causes embarrassment to Amaia.
Basque: Zakurra ikusi du.
English translation: S/he has seen the dog.
Basque: Sartu naizenean erizaina medikutzat hartu dut.
English translation: When I went in, I took the nurse for a doctor.
Basque: Gurasoei Bilbon etxe bat erosi nahi diet.
English translation: I want to buy my parents a house in Bilbao.
Basque: Zatoz!
English translation: Come! (you, POL).
Basque: Sail hori, nola dago eratua?
English translation: How is that section organized?
Basque: mahaia
English translation: the table
Basque: astoaren gainean..., amatzera zoaken emazte bat
English translation: on the donkey,... a woman who was certainly about to give birth
Basque: (Aldabako bikariuak konjuratuko balitu,) denak ilko lirake.
English translation: (If the vicar of Aldaba exorcized them,) all would die.
Basque: ia ezin gehiago egin dezakezula ikusirik...
English translation: seeing that you cannot do almost anything more...
Basque: Nerea abesten dago.
English translation: Nerea is singing.
Basque: Epi eta Bias elkarri bizkarra emanda jezarri dira.
English translation: Ernie and Bert sat back to back.
Basque: Inori ez zaio ezer gertatu.
English translation: Nothing happened to anyone.
Basque: Ezer gertatu ez balitz bezala hitz egin zidan.
English translation: She talked to me as if nothing had happened.
Basque: Ez du JONEK eskaera sinatu.
English translation: JON did not sign the petition.
Basque: Etsaiek elkarrenganik urrundu gaituzte.
English translation: Enemies have distanced us from each other.
Basque: Epik eta Blasek opariak eman dizkiote bata besteari.
English translation: Ernie and Bert have presents to each other.
Basque: har ezazu liburu-tto hunen fruitu-a, barren-eko mami-a:
English translation: Take the fruit of this little book, its internal substance.
Basque: Zakurra bidean gelditu da.
English translation: The dog stopped/remained in the way.
Basque: Ezer ez dio inork Mikeli eman.
English translation: No one gave anything to Mikel (intended meaning).
Basque: Galdetu dit ea ez zaion poeta haundi bat iruditzen.
English translation: He asked me whether he does not seem a great poet to him.
Basque: Geure burua aipatu dut, eta ez dakit zuzen mintzatu naizen, nik behintzat ez baitut Hipokratesekin zer ikusirik.
English translation: I have mentioned ourselves, and I don't know if I said it right, for I have nothing to do with Hypocrates.
Basque: Zilegi bekit, Iauna, (...) argitasun ontaz mintzatzen.
English translation: Sir, allow me to speak about this clarity (...)·
Basque: Hamarretan berriro saiatu delako lortu da.
English translation: It was achieved because it was tried again at ten.
Basque: ea denak lotsatu egiten ziren beren lanaz
English translation: [I asked him] whether all were ashamed of their job.
Basque: Akusatuak bere aita hil izana onartu zuen.
English translation: The defendant admitted having killed his/her father.
Basque: *Jonek lasai daki ikasgaia.
English translation: Jon knows the lesson calmly.
Basque: Oin-ez dabiltza.
English translation: They're walking. (lit., 'going on foot')
Basque: Etxean egongo da.
English translation: S/he is probably at home.
Basque: Liburua apurtua duzu.
English translation: That book you've got is ruined/You have ruined the book.
Basque: Zenbat jende ez den etorri!
English translation: How many people didn't come!
Basque: trenez etorri gara

In [ ]:
for lang, prompts in all_paratyp_prompts.items():
    prepare_batch(lang, prompts, limit=100)

batch_Igbo.jsonl - (177).
batch_Basque.jsonl - (200).
batch_Georgian.jsonl - (200).
batch_Korean.jsonl - (108).
batch_Chamorro.jsonl - (200).

In [ ]:
stats_list = []

for lang in multilingual_corpus.keys():
    train_texts = [str(s) for s in multilingual_corpus[lang]['train']['source']]
    test_texts = [str(s) for s in multilingual_corpus[lang]['test']['source'][:100]]

    train_tokens = sum(count_tokens(t) for t in train_texts)

    test_tokens = sum(count_tokens(t) for t in test_texts)

    stats_list.append({
        'Language': lang,
        'Train_Examples': len(train_texts),
        'Train_Tokens': train_tokens,
        'Test_Examples': len(test_texts),
        'Test_Tokens': test_tokens,
        'Total_Tokens': train_tokens + test_tokens
    })

df_final_stats = pd.DataFrame(stats_list)

display(df_final_stats)
df_stats.to_csv('df_final_stats.csv', index=False)

,Language,Train_Examples,Train_Tokens,Test_Examples,Test_Tokens,Total_Tokens
0,Igbo,849,7359,100,1167,8526
1,Basque,2186,29049,100,1487,30536
2,Georgian,833,15959,100,2611,18570
3,Korean,394,5184,100,1384,6568
4,Chamorro,1768,28293,100,1703,29996

In [ ]:
active_batch_jobs_para = submit_batches(client, multilingual_corpus, endpoint = 'completions')

In [ ]:
df_igbo = get_language_results('Basque', active_batch_jobs['Basque'], multilingual_corpus)

In [ ]:
dfs = {}

for lang_name, batch_id in active_batch_jobs_para.items():
    try:
        df_lang = get_language_results(lang_name, batch_id, multilingual_corpus)

        if df_lang is not None:
            dfs[lang_name] = df_lang
            df_lang.to_csv(f'results_{lang_name}_para.csv', index=False)
            print(f"Файл для {lang_name} сохранен.")
    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")

## PARA + GLOSS

(future work)

In [ ]:
# all_paragloss_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=100, mode='paragloss')

In [ ]:
# print(all_paragloss_prompts['Igbo'][0])

In [ ]:
# for lang, prompts in all_paragloss_prompts.items():
#     prepare_batch(lang, prompts, limit=100)

In [ ]:
# active_batch_jobs = {}

# for lang_name in multilingual_corpus.keys():
#     filename = f"batch_{lang_name}.jsonl"

#     try:
#         batch_file = client.files.create(
#             file=open(filename, "rb"),
#             purpose="batch"
#         )

#         batch_job = client.batches.create(
#             input_file_id=batch_file.id,
#             endpoint="/v1/chat/completions",
#             completion_window="24h",
#             metadata={"description": f"{lang_name} Research Translation (Only Glossed)"}
#         )

#         active_batch_jobs[lang_name] = batch_job.id
#         print(f"Отправлен {lang_name}: Batch ID = {batch_job.id}")
#         with open('active_batch_jobs.json', 'w', encoding='utf-8') as f:
#             json.dump(active_batch_jobs, f, ensure_ascii=False, indent=4)

#     except FileNotFoundError:
#         print(f"Файл {filename} не найден, пропускаем.")

# print("\nВсе задания отправлены.")

In [ ]:
# check_batch_statuses(active_batch_jobs)

In [ ]:
# dfs = {}

# for lang_name, batch_id in active_batch_jobs.items():
#     try:
#         df_lang = get_language_results(
#             lang_name=lang_name,
#             batch_job_id=batch_id,
#             multilingual_corpus=multilingual_corpus,
#             benchmark=sentences,
#             external_benchmarks=True
#         )

#         if df_lang is not None:
#             dfs[lang_name] = df_lang
#             filename = f'results_{lang_name}_paragloss.csv'
#             df_lang.to_csv(filename, index=False)
#             print(f"Файл для {lang_name} сохранен: {filename}")
#         else:
#             # Это сработает, если статус задания еще не "completed"
#             print(f"{lang_name}: результаты пока не готовы.")

#     except Exception as e:
#         print(f"Ошибка при обработке {lang_name}: {e}")

## Gloss + TYP + Para

In [ ]:
all_translation_prompts = generate_multilingual_prompts(multilingual_corpus, external_benchmarks=True, benchmark=sentences, train_limit=500, mode='paratyp')

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 113

In [ ]:
print(all_translation_prompts['Chamorro'][0])

Chamorro is a language that exhibits specific typological characteristics. Translate the following sentence from Chamorro to English: ['hafa tatatmanu hao']

Now write the translation. If you are not sure what the translation should be, then give your best guess. Do not say that you do not speak Chamorro. Do not say you do not have enough information, you must make a guess. If your translation is wrong, that is fine, but you have to provide a translation.
Your translation must be on the first line of your response, with no other text before the translation. Only explain your reasoning after providing the translation.
It is crucial that you only give the translation on the first line of your response, otherwise you will fail.

To help with the translation, here are some example Chamorro-English parallel sentences with morphological glosses:
Chamorro: Ti ya-ña håo i nana sa’ ti apropósitu håo para i hagå-ña.
Morphological gloss: not like-AGR you the mother because not AGR.suitable you
for the daughter-AGR
English translation: The mother does not like you because you are not suitable for her daughter.

Chamorro: Mañe’lu-ña hit famalåo’an si Antonio.
Morphological gloss: PL.sibling-AGR we.INCL PL.woman UNM Antonio
English translation: We (incl.) are Antonio’s sisters.

Chamorro: i che’lu-ña palåo’an si Juan
Morphological gloss: the sibling-AGR female UNM Juan
English translation: Juan’s sister

Chamorro: Mungnga madililing i neni taiguennåo.
Morphological gloss: don’t AGR.PASS.carry the baby like.that
English translation: Don’t carry the baby like that.

Chamorro: Maguf i geftåo na biha.
Morphological gloss: AGR.happy the generous L old.woman
English translation: The generous old woman was happy.

Chamorro: Siha i famagu’un fuma’gåsi i kareta.
Morphological gloss: PL the PL.child WH[SBJ].wash the car
English translation: The children are the ones who washed the car.

Chamorro: Ha na’ma’åsi’ yu’ i patgun.
Morphological gloss: AGR[3SG] make.pity me the child
English translation: The child made me feel sorry.

Chamorro: I putin kurason u fanmågung.
Morphological gloss: the hurt.L heart AGR AGR.healed
English translation: The heartaches are going to heal.

Chamorro: Pinayuni as nanå-ña si Manuel.
Morphological gloss: AGR.PASS.accustomed.to OBL mother-AGR UNM Manuel
English translation: Manuel’s mother is used to him (i.e. Manuel is known by his mother).

Chamorro: Tres na tintågu’ manmasotta ni ma’gas.
Morphological gloss: three L servant AGR.PASS.release OBL boss
English translation: Three servants were released by the boss.

Chamorro: Para i tenda hit guatu gi un ora.
Morphological gloss: to the store we.INCL to.there LCL a hour
English translation: We (incl.) are heading to the store in an hour.

Chamorro: Håfa na klasin nengkanu’ in kanu’ durantin i gera?
Morphological gloss: what?
L
sort.L
food
AGR eat
during.L
the
war
English translation: What types of food did you (pl.) eat during the war?

Chamorro: Sa’ mampus malångu gui’.
Morphological gloss: because so.much AGR[SG].sick he
English translation: Because he was so sick.

Chamorro: Si Kanåriu hinasson-ña na manlili’i’ gui’ birak.
Morphological gloss: UNM Kanåriu WH[OBJ].think-AGR COMP AGR.ANTIP.see.PROG she ghost
English translation: ‘Kanåriu thought that she was seeing a ghost.’

Chamorro: Hami yan si Juan che’lu-hu, humåhanåo ham påpa’ yan i asaguan-måmi.
Morphological gloss: we.EXCL with UNM Juan sibling-AGR AGR.go.PROG we.EXCL down with the spouse-AGR
English translation: My brother Juan and I were going down with our (excl.) wives.

Chamorro: Aprubetcha i tiempu ni manå’i håo.
Morphological gloss: make.use.of the time COMP AGR.PASS.give you
English translation: Make use of the time that you are given.

Chamorro: Si Juan ha fa’nå’gui yu’ mandåggåo talåya.
Morphological gloss: UNM Juan AGR teach me AGR.INF.ANTIP.throw fishing.net
English translation: Juan taught me how to cast a fishing net.

Chamorro: Månu na un fåhan i painetå-mu?
Morphological gloss: where? COMP AGR buy the comb-AGR
English translation: Where did you buy your comb?

Chamorro: As Matuis
Morphological gloss: OBL Matuis
English translation: As Matuis (name of a mountainous region in northern Saipan)

Chamorro: Måttu un na’maguf na nutisia.
Morphological gloss: AGR.arrive a pleasant L news
English translation: A piece of good news came.

Chamorro: Ma tutuhun manggera i taotåo giya Bosnia ...
Morphological gloss: AGR begin AGR.INF.make.war the person LCL Bosnia
English translation: The people began to make war in Bosnia...

Chamorro: Si Vincent bisiosu yanggin kumuentus na tåotåo.
Morphological gloss: UNM Vincent AGR.vicious if AGR.speak L person
English translation: Vincent is a vicious person when he talks.

Chamorro: Hu nå’yi i maseta meggai na odda’.
Morphological gloss: AGR add.to the vase much L dirt
English translation: I put a lot of soil in the vase.

Chamorro: Ti para u masångan pat matungu’ ni ottru.
Morphological gloss: not FUT AGR PASS.say or PASS.know OBL other
English translation: It will not be said or known by another person.

Chamorro: Ha nå’i guatu ni na’-ña ya sinangåni na para u chotchu.
Morphological gloss: AGR give to.there OBL food-AGR and.then AGR.PASS.say.to COMP FUT AGR ANTIP.eat
English translation: She gave him his food and told him that he should eat.

Chamorro: Yanggin taigui guini, pues esta guaha chumuli’.
Morphological gloss: if AGR.not.be.at here then already AGR.exist
chumuli’
English translation: If it’s not here, then someone took it.

Chamorro: Talang kada pidåsun kåtni ya u manå’yi presiu.
Morphological gloss: weigh each piece.L meat and.then AGR PASS.add price
English translation: Weigh each piece of meat so we can put a price on them.

Chamorro: Ma’udai yu’ gi batkun airin dångkulu para Amerika.
Morphological gloss: AGR.ride I LCL airplane.L big to America
English translation: I rode on a big airplane to America.

Chamorro: Ilek-ña si Orasima’-san nu guiya ...
Morphological gloss: say-AGR UNM Orasima’-san OBL him
English translation: ‘Orasima’-san said to himself...’

Chamorro: Månu na lupis para un håtmi?
Morphological gloss: which? L skirt FUT AGR put.on
English translation: Which skirt are you going to wear?

Chamorro: Ti ha li’i’ i nana malak månu i lahi-ña.
Morphological gloss: not AGR see the mother AGR.go.to where? the son-AGR
English translation: The mother did not see where her son had gone.

Chamorro: Mafa’nå’gui i lahi-hu taimanu mañugun fodo’ gi as tihu-ña.
Morphological gloss: AGR.PASS.teach the son-AGR how? AGR.ANTIP.drive bulldozer OBL uncle-AGR
English translation: My son was taught how to operate a bulldozer by his uncle.

Chamorro: Umali’i’ yu’ lokkui’ yan i doktu.
Morphological gloss: AGR.RECP.see I also with the doctor
English translation: I also met (lit. saw each other) with the doctor.

Chamorro: *Håfa para u na’kåti i patgun?
Morphological gloss: what? FUT AGR make.cry the child
English translation: What is going to make the child cry?

Chamorro: Bai hu gimin ennåo siha fuera ki sitbesa.
Morphological gloss: AGR drink that PL except than beer
English translation: I will drink those but not beer.

Chamorro: Ha na’kiba’ i matå-ña si Joaquin guatu gi as Lourdes.
Morphological gloss: AGR make.frown the face-AGR UNM Joaquin to.there LCL Lourdes
English translation: Joaquin made a face (lit. made his face frown) to Lourdes.

Chamorro: Manå’pagun i magågu gi tali anai umuchan dididi’.
Morphological gloss: AGR.damp the clothes LCL line when AGR.rain a.little
English translation: The clothes on the line became damp when it rained a little.

Chamorro: Påkaka’ sa’ hu keke’hunguk i rediu.
Morphological gloss: AGR.silent
because
AGR try.to.hear.PROG
the radio
English translation: Be quiet because I am trying to listen to the radio.

Chamorro: Håyi inayåo-mu salåppi’?
Morphological gloss: who? WH[OBJ].borrow-AGR money
English translation: Who did you borrow money from?

Chamorro: Goddi i chiba maseha taimanu na gineddi.
Morphological gloss: tie the goat at.all any.way COMP AGR.PASS.tie
English translation: Tie the goat any way it can be tied.

Chamorro: Ti tumunuk yu’ gi giput sa’ ha ispånta yu’ i bulan tåotåo.
Morphological gloss: not AGR.go.down I LCL party because AGR frighten me the much.L person
English translation: I did not attend the party because I was frightened by the large crowd.

Chamorro: Po’lunñaihun ha’ fan ennåo na problema sa’ ha na’malilinik ilu-hu.
Morphological gloss: put.awhile EMP please that L problem because AGR make.ache.PROG head-AGR
English translation: Please set that problem aside, because it is giving me a headache.

Chamorro: Achadangkulu i rainun rain Ispåña yan i rain Inglatera.
Morphological gloss: AGR.equally.big the kingdom.L king.L Spain and the king.L England
English translation: The king of Spain’s kingdom is as big as the King of England’s.

Chamorro: Bula sasata gi halum kollat chå’guan.
Morphological gloss: AGR.much bee LCL inside.L fence.L grass
English translation: There are lots of bees inside the hedges.

Chamorro: Tåya’ ga’lågu åntis di u fanmåttu i Ispañót.
Morphological gloss: AGR.not.exist dog before PRT AGR AGR.arrive the Spanish
English translation: There were no dogs before the Spanish arrived.

Chamorro: Ti gof maipi an puengi.
Morphological gloss: not AGR.very hot if evening
English translation: It’s not so hot when it’s evening.

Chamorro: Gof gai ganas chumotchu si Cecilia.
Morphological gloss: AGR.very
have
appetite
AGR.INF.ANTIP.eat
UNM
Cecilia
English translation: Cecilia has lots of appetite to eat.

Chamorro: Ya-hu umegga’ S.W.A.T. na mubi sa’ manachachapotsu’ i akta siha.
Morphological gloss: like-AGR AGR.INF.watch S.W.A.T. L movie because AGR.equally.good.at.shooting.PROG the actor PL
English translation: I like to watch S.W.A.T. movies because all the actors are sharp shooters (lit. the actors are equally good at shooting).

Chamorro: Gi sigundu biåhi ha na’matungu’ håyi gui’ si Jose ni mañe’lu-ña.
Morphological gloss: LCL second time AGR make.PASS.know who? he UNM Jose OBL PL.sibling-AGR
English translation: The second time, Joseph let his brothers know who he was.

Chamorro: Emi i mina’tressi na lettra gi atfabetikun Chamorro.
Morphological gloss: m the thirteenth L letter LCL alphabet.L Chamorro
English translation: M is the thirteenth letter of the Chamorro alphabet.

Chamorro: Siempri un chuda’ i hanum gigun un totpi i batdi.
Morphological gloss: indeed AGR spill the water as.soon.as AGR bump the
bucket
English translation: You are going to spill the water as soon as you bump the bucket.

Chamorro: Tai chotda si Jose tanduki.
Morphological gloss: AGR.not.have
green.banana
UNM
Jose
plantain
English translation: Jose doesn’t have any plantain bananas.

Chamorro: Kumahulu’ dångkulu na haggan.
Morphological gloss: AGR.go.up big L turtle
English translation: A large turtle came out (of the water).

Chamorro: i nilaksin Francisca siha na metyas
Morphological gloss: the WH[OBJ].sew.L Francisca PL L socks
English translation: the socks that Francisca sewed

Chamorro: I profesias sessu mangginin i manmenhalum siha na indibiduåt.
Morphological gloss: the prophecy often AGR.from the AGR.wise PL L individual
English translation: Prophecies often come from wise individuals.

Chamorro: Ha barohu si Manuel i liluk hålum gi hayu.
Morphological gloss: AGR drill UNM Manuel the nail inside LCL wood
English translation: Manuel drilled the nail into the wood.

Chamorro: Ti ha atotga si Miguel para u kundena i Aniti.
Morphological gloss: not AGR dare UNM Miguel FUT AGR condemn the Devil
English translation: Michael did not dare to condemn the Devil...

Chamorro: Kumu te’uk i timplåda, diliti mås hånum.
Morphological gloss: if AGR.thick the mixture dilute more water
English translation: If the mixture is too thick, dilute it with water.

Chamorro: Hu arerekla yu’ esta.
Morphological gloss: AGR fix.PROG me already
English translation: ‘I’ve already fixed myself up.’

Chamorro: Håfa sinangani håo as nanå-mu finahån-ña?
Morphological gloss: what? AGR.PASS.say.to you OBL mother-AGR WH[OBJ].buy-AGR
English translation: What did your mother tell you that she bought?

Chamorro: I kusineru ha sabureha i nina’lagu-ña.
Morphological gloss: the cook AGR taste the WH[OBJ].cook-AGR
English translation: The cook tasted the (food) he cooked.

Chamorro: Kåo siña un cho’guiyi yu’ fabot ya un yuti’ i basula?
Morphological gloss: Q can AGR do.for me favor and.then AGR discard the trash
English translation: Can you please do me a favor and throw out the trash?

Chamorro: Yanggin mampus atdit i patgun chetnot-ña
Morphological gloss: if so.much AGR.severe the child illness-AGR
English translation: When a child has a very serious illness...

Chamorro: In li’i’ un tåotåo ni ha u’usa i na’ån-mu para u fandulalak aniti ...
Morphological gloss: AGR see a person COMP AGR use.PROG the name-AGR FUT AGR ANTIP.chase devil
English translation: We (excl.) saw a person who was using your name to chase away demons.

Chamorro: Tåmpi i chetnut nu i gåsa sa’ i lalu’.
Morphological gloss: cover the sore OBL the gauze because.of the fly
English translation: Cover the sore with the gauze because of the flies.

Chamorro: I manamko’-ta åntis tumutuhun umusa Bo gi na’an Ramon.
Morphological gloss: the PL.elder-AGR before WH[SBJ].begin INF.use Bo LCL name.L Ramon
English translation: Our (incl.) elders were the ones to begin to use Bo as a nickname for Ramon.

Chamorro: i mañainan Tan Ignacia
Morphological gloss: the PL.parent.L Mrs. Ignacia
English translation: Tan Ignacia’s parents

Chamorro: Hu na’ayåo si Isidro ni kareta.
Morphological gloss: AGR make.borrow UNM Isidro OBL car
English translation: I let Isidro borrow the car.

Chamorro: Na’guaha amistå giya hågu.
Morphological gloss: make.exist integrity LCL you
English translation: Have integrity (within you).

Chamorro: Meggai ginimen-mu letchi.
Morphological gloss: AGR.many WH[OBJ].drink-AGR milk
English translation: You drank a lot of milk (in your lifetime).

Chamorro: Matungu’ ni famagu’un tumugi’ i na’ån-hu.
Morphological gloss: AGR.PASS.know OBL PL.child INF.write the name-AGR
English translation: The children know how to write my name (lit. how to write my name is known by the children).

Chamorro: Todu ha’ manma’å’ñåo pumunu’ siha.
Morphological gloss: all EMP AGR.afraid INF.kill them
English translation: ‘All are afraid to kill themselves.’

Chamorro: Håyi mås ekspirensiåo gi kontra todus hit?
Morphological gloss: who? more AGR.experienced LCL against all us.INCL
English translation: Who is the most experienced amongst us (incl.) all?

Chamorro: Ma pripåpara siha i familian Tuho’ para i inetnun-ñiha.
Morphological gloss: AGR prepare.PROG them the family.L Tuho’ for the meeting-AGR
English translation: ‘The Tuho’ families are preparing (themselves) for their reunion.’

Chamorro: Håyi fina’na’guem-mu?
Morphological gloss: who? WH[OBJ].teach-AGR
English translation: Who did you teach about (i.e. use as an example in your teaching)?

Chamorro: Huchum i trangka ya mungnga na u hålum i ga’lågu.
Morphological gloss: close
the gate
and.then
don’t
COMP
AGR
go.in
the dog
English translation: Close the gate so the dogs will not come in.

Chamorro: Puedi ti kånsit esti na dohlan.
Morphological gloss: hopefully not AGR.cancerous this L cyst
English translation: Hopefully this cyst is not cancerous.

Chamorro: Håyi mås gofli’un gi famagu’on-mu?
Morphological gloss: who? more AGR.amicable LCL PL.child-AGR
English translation: Who is the most amicable among your children?

Chamorro: I na’ån-ña i kabesånti si Benigno.
Morphological gloss: the name-AGR the leader UNM Benigno
English translation: The name of the leader is Ben.

Chamorro: Ti måfattu ha’ i infitmera para u li’i’ i hetnu.
Morphological gloss: not AGR.arrive.PROG EMP the nurse FUT AGR see the oven
English translation: The nurse still hadn’t come to (lit. so that she would) see the incubator.

Chamorro: Hågu yan guåhu para u pinenta i liga.
Morphological gloss: you and me FUT AGR PASS.paint the wall
English translation: You and me are going to paint the wall.

Chamorro: Håfa para u mapadesi ni atyu siha ni manhålum mandisipulu-ña.
Morphological gloss: what? FUT AGR PASS.endure by that PL COMP AGR.go.in AGR.INF.disciple-AGR
English translation: (He said) what would be endured by those who became his disciples.

Chamorro: Esta, ta ali’i’ dispues.
Morphological gloss: okay AGR RECP.see later
English translation: Okay, we’ll (incl.) see each other later.

Chamorro: Ilek-ña på’gu i radio’ na para u guaifun.
Morphological gloss: say-AGR
now
the radio
COMP
FUT
AGR
stormy
English translation: The radio announced today that it will be a stormy day.

Chamorro: Trabiha ti hu tataitai i lepblu ni ha nå’i yu’.
Morphological gloss: still not AGR read.PROG the book COMP AGR give me
English translation: I haven’t yet read the book that she gave me.

Chamorro: Sigi ha’ mås ma’åomenta i tiningo’-hu.
Morphological gloss: keep.on EMP more AGR.PASS.expand the knowledge-AGR
English translation: My knowledge keeps expanding (lit. being expanded) more.

Chamorro: i famalåo’an siha
Morphological gloss: the PL.woman PL
English translation: the women

Chamorro: Uma’achampa si Jesus yan i bisinu-ña.
Morphological gloss: AGR.RECP.compete.PROG UNM Jesus and the neighbor-AGR
English translation: Jesus and his neighbor are competing with each other.

Chamorro: Mampus disatentu håo.
Morphological gloss: so.much AGR.disrespectful you
English translation: You are very disrespectful.

Chamorro: Guaha nai ma lili’i’ palåo’an na å’a’paka’ magagu-ña ya anåkku’ påpa’ gaputilu-ña.
Morphological gloss: AGR.exist COMP AGR see.PROG woman COMP AGR.white.PROG clothes-AGR and.then AGR.long down hair-AGR
English translation: There were (times) when they saw a woman who had whitish clothes and long hair.

Chamorro: Manggågåo yu’ kalamendu’ gi bisinu.
Morphological gloss: AGR.ANTIP.request I tamarind LCL neighbor
English translation: I asked for tamarind from the neighbor.

Chamorro: Guaha siha matiriåt ha cho’gui gi finu’ Chamorro.
Morphological gloss: AGR.exist PL material AGR make LCL speech.L Chamorro
English translation: There are materials that he made in the Chamorro language.

Chamorro: Nuebu ha’ esti na mohon ni mapo’lu.
Morphological gloss: AGR.new EMP this L boundary.marker COMP AGR.PASS.put
English translation: This boundary marker that was placed is just new.

Chamorro: Hu adinganiyi si Maria as Nåna sa’ ma’å’ñåo nu i bidå-ña.
Morphological gloss: AGR talk.for UNM Maria OBL Mother because AGR.afraid OBL the WH[OBJ].do-AGR
English translation: I talked to Mother for Maria, because she is afraid of what she did.

Chamorro: I balin i biyeti kulang bålin un guaka.
Morphological gloss: the value.L the ticket seems.like value.L a cow
English translation: The cost of the ticket is almost the price of a cow.

Chamorro: Kuinentutusi håo.
Morphological gloss: AGR.PASS.speak.to.PROG you
English translation: She’s speaking to you (lit. you are being spoken to by her).

Chamorro: i tinituhun i tiempun para manånum
Morphological gloss: the NMLZ.begin.L the time.L for AGR.ANTIP.plant
English translation: the beginning of planting season

Chamorro: Maseha månu guatu si nanå-hu, todu i tiempu tåtti ha’ si tatå-hu gi santatti.
Morphological gloss: at.all where to.there UNM mother-AGR all the time AGR.behind.PROG EMP UNM father-AGR LCL DIR.behind
English translation: Wherever my mother went, all the time my father followed behind her.

Chamorro: Atyu muna’ guaguan sa’ duråpbli.
Morphological gloss: that is.why AGR.expensive because AGR.lasting
English translation: It is expensive because it is lasting.

Chamorro: Mana’sesetbi i cheggai gi huegun chongka.
Morphological gloss: AGR.PASS.use.PROG the small.cowrie LCL game.L chongka
English translation: The small cowrie is used in the chongka game.

Chamorro: Guaha gaigi gi papa’ lamasa.
Morphological gloss: AGR.exist AGR.be.at LCL under.L table
English translation: There’s someone who is under the table.


In [ ]:
for lang, prompts in all_translation_prompts.items():
    prepare_batch(lang, prompts, limit=100)

batch_Igbo.jsonl - (100).
batch_Basque.jsonl - (100).
batch_Georgian.jsonl - (100).
batch_Korean.jsonl - (100).
batch_Chamorro.jsonl - (100).

In [ ]:
active_batch_jobs = submit_batches(client, multilingual_corpus, endpoint = 'completions')

In [ ]:
check_batch_statuses(active_batch_jobs)

In [ ]:
dfs = {}

for lang_name, batch_id in active_batch_jobs.items():
    try:
        df_lang = get_language_results(
            lang_name=lang_name,
            batch_job_id=batch_id,
            multilingual_corpus=multilingual_corpus,
            benchmark=sentences,
            external_benchmarks=True
        )

        if df_lang is not None:
            dfs[lang_name] = df_lang
            filename = f'results_{lang_name}_gloss.csv'
            df_lang.to_csv(filename, index=False)
            print(f"Файл для {lang_name} сохранен: {filename}")
        else:
            print(f"{lang_name}: результаты пока не готовы.")

    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")

Файл для Igbo сохранен: results_Igbo_gloss.csv
Файл для Basque сохранен: results_Basque_gloss.csv
Файл для Georgian сохранен: results_Georgian_gloss.csv
Файл для Korean сохранен: results_Korean_gloss.csv
Файл для Chamorro сохранен: results_Chamorro_gloss.csv

# Reasoning

In [ ]:
all_reasoning_prompts = generate_multilingual_prompts(multilingual_corpus, benchmark=sentences, train_limit=100, mode='full')

Создано промптов для Igbo: 1012
Создано промптов для Basque: 1012
Создано промптов для Georgian: 1012
Создано промптов для Korean: 1012
Создано промптов для Chamorro: 219

In [ ]:
for lang, prompts in all_reasoning_prompts.items():
    prepare_batch(lang, prompts, truncate=True, limit=100, reasoning=True)

batch_Igbo.jsonl - (100).
batch_Basque.jsonl - (100).
batch_Georgian.jsonl - (100).
batch_Korean.jsonl - (100).
batch_Chamorro.jsonl - (100).

In [ ]:
active_batch_jobs_reasoning = submit_batches(client, lang_name='Korean', endpoint='responses', storage_path='active_batch_jobs.json', base_dir='/content')

In [ ]:
def get_language_results(lang_name, batch_job_id, multilingual_corpus, benchmark=None):
    job = client.batches.retrieve(batch_job_id)

    if job.status in ["failed", "expired", "cancelled"]:
        print(f"Задание для {lang_name} завершилось неудачно. Статус: {job.status}")
        # Если в объекте job есть описание ошибки, выводим его
        if hasattr(job, 'errors') and job.errors:
            print(f"Детали ошибки: {job.errors}")
        return None

    if job.status != "completed":
        print(f"Задание для {lang_name} еще не готово. Статус: {job.status}")
        return None

    file_response = client.files.content(job.output_file_id)

    if benchmark is not None:
        if lang_name in benchmark:
            source_sentences = benchmark[lang_name]['source']
            reference_sentences = benchmark[lang_name]['target']
        else:
            print(f"Ошибка: {lang_name} не найден в benchmark")
            return None
    else:
        source_sentences = multilingual_corpus[lang_name]['test']['source']
        reference_sentences = multilingual_corpus[lang_name]['test']['target']

    results_list = []

    for line in file_response.text.splitlines():
      if not line.strip(): continue
      res = json.loads(line)

      body = res.get('response', {}).get('body', {})
      outputs = body.get('output', [])

      prediction = "N/A"
      reasoning_summary = "N/A"

      for item in outputs:
          if item.get('type') == 'message':
              content_list = item.get('content', [])
              for content_item in content_list:
                  if content_item.get('type') == 'output_text':
                      prediction = content_item.get('text', "").strip()

          elif item.get('type') == 'reasoning':
            summary_list = item.get('summary', [])

            if isinstance(summary_list, list) and len(summary_list) > 0:
                texts = [
                    obj.get('text', "")
                    for obj in summary_list
                    if isinstance(obj, dict) and 'text' in obj
                ]
                reasoning_summary = "\n".join(texts).strip()

            elif isinstance(summary_list, str):
                reasoning_summary = summary_list

      # Если в блоке output summary пуст, проверяем верхний уровень body
      if (reasoning_summary == "N/A" or not reasoning_summary) and 'reasoning' in body:
          reasoning_summary = body['reasoning'].get('summary', "N/A")

      parts = res['custom_id'].split('-')
      idx = int(parts[-1])

      source = source_sentences[idx]
      reference = reference_sentences[idx]

      score = 0.0
      if prediction != "N/A":
          score = chrf.compute(predictions=[prediction], references=[[reference]])['score']

      results_list.append({
          "Lang": lang_name,
          "Index": idx,
          "Source": source,
          "Reference": reference,
          "LLM_Translation": prediction,
          "Reasoning_Summary": reasoning_summary,
          "ChrF": round(score, 2)
      })

    return pd.DataFrame(results_list).sort_values("Index").reset_index(drop=True)

In [ ]:
dfs = {}

for lang_name, batch_id in active_batch_jobs_reasoning.items():
    try:
        df_lang = get_language_results(lang_name, batch_id, multilingual_corpus, benchmark=sentences)

        if df_lang is not None:
            dfs[lang_name] = df_lang
            df_lang.to_csv(f'results_{lang_name}_reasoning_bench.csv', index=False)
            print(f"Файл для {lang_name} сохранен.")
    except Exception as e:
        print(f"Ошибка при обработке {lang_name}: {e}")

Файл для Igbo сохранен.
Файл для Chamorro сохранен.
Файл для Basque сохранен.
Файл для Georgian сохранен.
Файл для Korean сохранен.